// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"
)

const advanceDevClock = `-- name: AdvanceDevClock :one
INSERT INTO runtime_state (singleton, dev_clock_offset_seconds, updated_at)
VALUES (true, $1, $2)
ON CONFLICT (singleton) DO UPDATE
SET dev_clock_offset_seconds = runtime_state.dev_clock_offset_seconds + excluded.dev_clock_offset_seconds,
    updated_at = excluded.updated_at
RETURNING dev_clock_offset_seconds
`

type AdvanceDevClockParams struct {
	Seconds   int64
	UpdatedAt time.Time
}

// AdvanceDevClock moves the development clock @seconds further ahead, creating the singleton row when missing, and
// returns how far ahead it now runs.
func (q *Queries) AdvanceDevClock(ctx context.Context, arg AdvanceDevClockParams) (int64, error) {
	row := q.db.QueryRow(ctx, advanceDevClock, arg.Seconds, arg.UpdatedAt)
	var dev_clock_offset_seconds int64
	err := row.Scan(&dev_clock_offset_seconds)
	return dev_clock_offset_seconds, err
}

const getDevClockOffset = `-- name: GetDevClockOffset :one

SELECT dev_clock_offset_seconds
FROM runtime_state
WHERE singleton
`

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// GetDevClockOffset reads how far the development clock runs ahead of the system time; no row means not at all.
func (q *Queries) GetDevClockOffset(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDevClockOffset)
	var dev_clock_offset_seconds int64
	err := row.Scan(&dev_clock_offset_seconds)
	return dev_clock_offset_seconds, err
}

const notifyDevClock = `-- name: NotifyDevClock :exec
SELECT pg_notify($1::text, $2::text)
`

type NotifyDevClockParams struct {
	Channel string
	Payload string
}

// NotifyDevClock tells every replica that the development clock moved, once the transaction commits.
func (q *Queries) NotifyDevClock(ctx context.Context, arg NotifyDevClockParams) error {
	_, err := q.db.Exec(ctx, notifyDevClock, arg.Channel, arg.Payload)
	return err
}
