// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConnectionDestinations = `-- name: CountConnectionDestinations :one
SELECT count(*)
FROM destinations
WHERE org_id = $1 AND connection_id = $2 AND deleted_at IS NULL
`

type CountConnectionDestinationsParams struct {
	OrgID        int64
	ConnectionID pgtype.Int8
}

// CountConnectionDestinations counts the Destinations that are not deleted of a Connection, under the lock of the
// Connection's deletion, which a Destination's save takes in share mode.
func (q *Queries) CountConnectionDestinations(ctx context.Context, arg CountConnectionDestinationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConnectionDestinations, arg.OrgID, arg.ConnectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findConnectionByName = `-- name: FindConnectionByName :one
SELECT id
FROM connections
WHERE org_id = $1 AND name = $2 AND deleted_at IS NULL
`

type FindConnectionByNameParams struct {
	OrgID int64
	Name  string
}

// FindConnectionByName returns the id of the Connection that is not deleted and has the name.
func (q *Queries) FindConnectionByName(ctx context.Context, arg FindConnectionByNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, findConnectionByName, arg.OrgID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getConnection = `-- name: GetConnection :one
SELECT c.id, c.public_id, c.type, c.name, c.mattermost_server_url, c.bot_token_ciphertext, c.bot_token_key_id,
       c.bot_token_updated_at, c.bot_user_id, c.bot_username, c.proxy, c.proxy_password_ciphertext,
       c.proxy_password_key_id, c.proxy_password_updated_at, c.limiter_limit, c.limiter_per_seconds, c.created_at,
       c.version,
       (SELECT count(*)
        FROM destinations d
        WHERE d.org_id = c.org_id AND d.connection_id = c.id AND d.deleted_at IS NULL)::bigint AS destination_count
FROM connections c
WHERE c.org_id = $1 AND c.deleted_at IS NULL
  AND (c.public_id = $2::text
       OR ($2::text IS NULL AND c.id = $3::bigint))
`

type GetConnectionParams struct {
	OrgID    int64
	PublicID pgtype.Text
	ID       pgtype.Int8
}

type GetConnectionRow struct {
	ID                      int64
	PublicID                string
	Type                    string
	Name                    string
	MattermostServerUrl     pgtype.Text
	BotTokenCiphertext      []byte
	BotTokenKeyID           pgtype.Text
	BotTokenUpdatedAt       time.Time
	BotUserID               pgtype.Text
	BotUsername             pgtype.Text
	Proxy                   []byte
	ProxyPasswordCiphertext []byte
	ProxyPasswordKeyID      pgtype.Text
	ProxyPasswordUpdatedAt  pgtype.Timestamptz
	LimiterLimit            int64
	LimiterPerSeconds       int64
	CreatedAt               time.Time
	Version                 int64
	DestinationCount        int64
}

// GetConnection reads a Connection that is not deleted by its public_id, or by its id when public_id is null.
func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (GetConnectionRow, error) {
	row := q.db.QueryRow(ctx, getConnection, arg.OrgID, arg.PublicID, arg.ID)
	var i GetConnectionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Type,
		&i.Name,
		&i.MattermostServerUrl,
		&i.BotTokenCiphertext,
		&i.BotTokenKeyID,
		&i.BotTokenUpdatedAt,
		&i.BotUserID,
		&i.BotUsername,
		&i.Proxy,
		&i.ProxyPasswordCiphertext,
		&i.ProxyPasswordKeyID,
		&i.ProxyPasswordUpdatedAt,
		&i.LimiterLimit,
		&i.LimiterPerSeconds,
		&i.CreatedAt,
		&i.Version,
		&i.DestinationCount,
	)
	return i, err
}

const getDestinationTarget = `-- name: GetDestinationTarget :one
SELECT d.mattermost_team_id, d.mattermost_team_name, d.mattermost_channel_id, c.id, c.public_id, c.type, c.name,
       c.mattermost_server_url, c.bot_token_ciphertext, c.bot_token_key_id, c.bot_token_updated_at, c.proxy,
       c.proxy_password_ciphertext, c.proxy_password_key_id, c.proxy_password_updated_at, c.version
FROM destinations d
JOIN connections c ON c.org_id = d.org_id AND c.id = d.connection_id
WHERE d.org_id = $1 AND d.id = $2 AND d.type = 'mattermost' AND c.deleted_at IS NULL
`

type GetDestinationTargetParams struct {
	OrgID         int64
	DestinationID int64
}

type GetDestinationTargetRow struct {
	MattermostTeamID        pgtype.Text
	MattermostTeamName      pgtype.Text
	MattermostChannelID     pgtype.Text
	ID                      int64
	PublicID                string
	Type                    string
	Name                    string
	MattermostServerUrl     pgtype.Text
	BotTokenCiphertext      []byte
	BotTokenKeyID           pgtype.Text
	BotTokenUpdatedAt       time.Time
	Proxy                   []byte
	ProxyPasswordCiphertext []byte
	ProxyPasswordKeyID      pgtype.Text
	ProxyPasswordUpdatedAt  pgtype.Timestamptz
	Version                 int64
}

// GetDestinationTarget reads where a Mattermost Destination posts — its team and channel — with the Connection it
// posts through and that Connection's secrets as stored. A deleted Destination is read too, since its final edit still
// runs; its Connection must not be deleted.
func (q *Queries) GetDestinationTarget(ctx context.Context, arg GetDestinationTargetParams) (GetDestinationTargetRow, error) {
	row := q.db.QueryRow(ctx, getDestinationTarget, arg.OrgID, arg.DestinationID)
	var i GetDestinationTargetRow
	err := row.Scan(
		&i.MattermostTeamID,
		&i.MattermostTeamName,
		&i.MattermostChannelID,
		&i.ID,
		&i.PublicID,
		&i.Type,
		&i.Name,
		&i.MattermostServerUrl,
		&i.BotTokenCiphertext,
		&i.BotTokenKeyID,
		&i.BotTokenUpdatedAt,
		&i.Proxy,
		&i.ProxyPasswordCiphertext,
		&i.ProxyPasswordKeyID,
		&i.ProxyPasswordUpdatedAt,
		&i.Version,
	)
	return i, err
}

const insertConnection = `-- name: InsertConnection :one
INSERT INTO connections (
    org_id, public_id, type, name, mattermost_server_url, bot_token_ciphertext, bot_token_key_id,
    bot_token_updated_at, proxy, proxy_password_ciphertext, proxy_password_key_id, proxy_password_updated_at,
    limiter_limit, limiter_per_seconds, created_at, updated_at
)
VALUES (
    $1, $2, 'mattermost', $3, $4, $5, $6,
    $7::timestamptz, $8, $9,
    $10, $11, $12, $13,
    $14::timestamptz, $14::timestamptz
)
RETURNING id
`

type InsertConnectionParams struct {
	OrgID                   int64
	PublicID                string
	Name                    string
	ServerUrl               pgtype.Text
	BotTokenCiphertext      []byte
	BotTokenKeyID           pgtype.Text
	BotTokenUpdatedAt       time.Time
	Proxy                   []byte
	ProxyPasswordCiphertext []byte
	ProxyPasswordKeyID      pgtype.Text
	ProxyPasswordUpdatedAt  pgtype.Timestamptz
	LimiterLimit            int64
	LimiterPerSeconds       int64
	Now                     time.Time
}

// InsertConnection creates a Mattermost Connection.
func (q *Queries) InsertConnection(ctx context.Context, arg InsertConnectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertConnection,
		arg.OrgID,
		arg.PublicID,
		arg.Name,
		arg.ServerUrl,
		arg.BotTokenCiphertext,
		arg.BotTokenKeyID,
		arg.BotTokenUpdatedAt,
		arg.Proxy,
		arg.ProxyPasswordCiphertext,
		arg.ProxyPasswordKeyID,
		arg.ProxyPasswordUpdatedAt,
		arg.LimiterLimit,
		arg.LimiterPerSeconds,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listConnections = `-- name: ListConnections :many


SELECT c.id, c.public_id, c.type, c.name, c.mattermost_server_url, c.bot_token_ciphertext, c.bot_token_key_id,
       c.bot_token_updated_at, c.bot_user_id, c.bot_username, c.proxy, c.proxy_password_ciphertext,
       c.proxy_password_key_id, c.proxy_password_updated_at, c.limiter_limit, c.limiter_per_seconds, c.created_at,
       c.version,
       (SELECT count(*)
        FROM destinations d
        WHERE d.org_id = c.org_id AND d.connection_id = c.id AND d.deleted_at IS NULL)::bigint AS destination_count
FROM connections c
WHERE c.org_id = $1 AND c.deleted_at IS NULL
  AND ($2::text IS NULL OR c.type = $2::text)
  AND ($3::bigint IS NULL OR c.id > $3::bigint)
ORDER BY c.id
LIMIT $4
`

type ListConnectionsParams struct {
	OrgID    int64
	Type     pgtype.Text
	AfterID  pgtype.Int8
	PageSize int32
}

type ListConnectionsRow struct {
	ID                      int64
	PublicID                string
	Type                    string
	Name                    string
	MattermostServerUrl     pgtype.Text
	BotTokenCiphertext      []byte
	BotTokenKeyID           pgtype.Text
	BotTokenUpdatedAt       time.Time
	BotUserID               pgtype.Text
	BotUsername             pgtype.Text
	Proxy                   []byte
	ProxyPasswordCiphertext []byte
	ProxyPasswordKeyID      pgtype.Text
	ProxyPasswordUpdatedAt  pgtype.Timestamptz
	LimiterLimit            int64
	LimiterPerSeconds       int64
	CreatedAt               time.Time
	Version                 int64
	DestinationCount        int64
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// Connections (C-13.FR-1, FR-6): a messenger server or bot through which Destinations post. The bot token and the
// proxy password are read as ciphertexts only to build the Connection's client; reads show their status.
// ListConnections reads a page of the Connections that are not deleted, in id order after a cursor, filtered by type,
// each with the count of its Destinations that are not deleted.
func (q *Queries) ListConnections(ctx context.Context, arg ListConnectionsParams) ([]ListConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listConnections,
		arg.OrgID,
		arg.Type,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionsRow{}
	for rows.Next() {
		var i ListConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Type,
			&i.Name,
			&i.MattermostServerUrl,
			&i.BotTokenCiphertext,
			&i.BotTokenKeyID,
			&i.BotTokenUpdatedAt,
			&i.BotUserID,
			&i.BotUsername,
			&i.Proxy,
			&i.ProxyPasswordCiphertext,
			&i.ProxyPasswordKeyID,
			&i.ProxyPasswordUpdatedAt,
			&i.LimiterLimit,
			&i.LimiterPerSeconds,
			&i.CreatedAt,
			&i.Version,
			&i.DestinationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMattermostDestinations = `-- name: ListMattermostDestinations :many
SELECT id, public_id, name, connection_id, mattermost_team_id, mattermost_channel_id
FROM destinations
WHERE org_id = $1 AND type = 'mattermost' AND deleted_at IS NULL
ORDER BY id
`

type ListMattermostDestinationsRow struct {
	ID                  int64
	PublicID            string
	Name                string
	ConnectionID        pgtype.Int8
	MattermostTeamID    pgtype.Text
	MattermostChannelID pgtype.Text
}

// ListMattermostDestinations lists the Mattermost Destinations that are not deleted, in id order, with their
// Connection, team and channel, for muster doctor.
func (q *Queries) ListMattermostDestinations(ctx context.Context, orgID int64) ([]ListMattermostDestinationsRow, error) {
	rows, err := q.db.Query(ctx, listMattermostDestinations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMattermostDestinationsRow{}
	for rows.Next() {
		var i ListMattermostDestinationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.ConnectionID,
			&i.MattermostTeamID,
			&i.MattermostChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConnection = `-- name: LockConnection :one
SELECT id, public_id, type, version
FROM connections
WHERE org_id = $1 AND public_id = $2 AND deleted_at IS NULL
FOR NO KEY UPDATE
`

type LockConnectionParams struct {
	OrgID    int64
	PublicID string
}

type LockConnectionRow struct {
	ID       int64
	PublicID string
	Type     string
	Version  int64
}

// LockConnection locks a Connection that is not deleted for a change or its deletion.
func (q *Queries) LockConnection(ctx context.Context, arg LockConnectionParams) (LockConnectionRow, error) {
	row := q.db.QueryRow(ctx, lockConnection, arg.OrgID, arg.PublicID)
	var i LockConnectionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Type,
		&i.Version,
	)
	return i, err
}

const lockDemo = `-- name: LockDemo :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// LockDemo serializes the demo start-up step of replicas that start together, until the transaction ends.
func (q *Queries) LockDemo(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, lockDemo, key)
	return err
}

const markConnectionDeleted = `-- name: MarkConnectionDeleted :exec
UPDATE connections
SET deleted_at = $1::timestamptz, updated_at = $1::timestamptz, version = version + 1,
    bot_token_ciphertext = NULL, bot_token_key_id = NULL, proxy_password_ciphertext = NULL,
    proxy_password_key_id = NULL, telegram_webhook_secret_ciphertext = NULL, telegram_webhook_secret_key_id = NULL
WHERE org_id = $2 AND id = $3
`

type MarkConnectionDeletedParams struct {
	Now   time.Time
	OrgID int64
	ID    int64
}

// MarkConnectionDeleted soft-deletes a Connection and wipes its secrets: it leaves every list and reads as missing,
// the row stays for the history of its Destinations.
func (q *Queries) MarkConnectionDeleted(ctx context.Context, arg MarkConnectionDeletedParams) error {
	_, err := q.db.Exec(ctx, markConnectionDeleted, arg.Now, arg.OrgID, arg.ID)
	return err
}

const setBotIdentity = `-- name: SetBotIdentity :exec
UPDATE connections
SET bot_user_id = $1, bot_username = $2
WHERE org_id = $3 AND id = $4 AND deleted_at IS NULL
`

type SetBotIdentityParams struct {
	BotUserID   pgtype.Text
	BotUsername pgtype.Text
	OrgID       int64
	ID          int64
}

// SetBotIdentity records the bot that a successful Connection check found; it is not a change of the configuration.
func (q *Queries) SetBotIdentity(ctx context.Context, arg SetBotIdentityParams) error {
	_, err := q.db.Exec(ctx, setBotIdentity,
		arg.BotUserID,
		arg.BotUsername,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const updateConnection = `-- name: UpdateConnection :exec
UPDATE connections
SET name = $1, mattermost_server_url = $2, bot_token_ciphertext = $3,
    bot_token_key_id = $4, bot_token_updated_at = $5::timestamptz,
    bot_user_id = CASE WHEN $6::boolean THEN NULL ELSE bot_user_id END,
    bot_username = CASE WHEN $6::boolean THEN NULL ELSE bot_username END,
    proxy = $7, proxy_password_ciphertext = $8,
    proxy_password_key_id = $9,
    proxy_password_updated_at = $10, limiter_limit = $11,
    limiter_per_seconds = $12, updated_at = $13::timestamptz, version = version + 1
WHERE org_id = $14 AND id = $15
`

type UpdateConnectionParams struct {
	Name                    string
	ServerUrl               pgtype.Text
	BotTokenCiphertext      []byte
	BotTokenKeyID           pgtype.Text
	BotTokenUpdatedAt       time.Time
	ForgetBot               bool
	Proxy                   []byte
	ProxyPasswordCiphertext []byte
	ProxyPasswordKeyID      pgtype.Text
	ProxyPasswordUpdatedAt  pgtype.Timestamptz
	LimiterLimit            int64
	LimiterPerSeconds       int64
	Now                     time.Time
	OrgID                   int64
	ID                      int64
}

// UpdateConnection replaces the configured fields of a Mattermost Connection and its secrets as the write path
// computed them. A changed server URL or bot token forgets the bot the last check learned.
func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) error {
	_, err := q.db.Exec(ctx, updateConnection,
		arg.Name,
		arg.ServerUrl,
		arg.BotTokenCiphertext,
		arg.BotTokenKeyID,
		arg.BotTokenUpdatedAt,
		arg.ForgetBot,
		arg.Proxy,
		arg.ProxyPasswordCiphertext,
		arg.ProxyPasswordKeyID,
		arg.ProxyPasswordUpdatedAt,
		arg.LimiterLimit,
		arg.LimiterPerSeconds,
		arg.Now,
		arg.OrgID,
		arg.ID,
	)
	return err
}
