// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDestinationMentions = `-- name: GetDestinationMentions :one


SELECT mentions
FROM destinations
WHERE org_id = $1 AND id = $2
`

type GetDestinationMentionsParams struct {
	OrgID int64
	ID    int64
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// Mentions (C-12.FR-8, FR-12): the Mention settings of a Destination, the Owners a lifecycle event recorded, the Users
// a Mention names with the username of their Account link in an identity space, and the usernames of the user a
// footer names.
// GetDestinationMentions reads the Mention settings of a Destination.
func (q *Queries) GetDestinationMentions(ctx context.Context, arg GetDestinationMentionsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDestinationMentions, arg.OrgID, arg.ID)
	var mentions []byte
	err := row.Scan(&mentions)
	return mentions, err
}

const getEventOwners = `-- name: GetEventOwners :one
SELECT owner_user_id, previous_owner_user_id
FROM timeline_entries
WHERE org_id = $1 AND alert_group_id = $2 AND event_seq = $3::bigint
LIMIT 1
`

type GetEventOwnersParams struct {
	OrgID        int64
	AlertGroupID int64
	EventSeq     int64
}

type GetEventOwnersRow struct {
	OwnerUserID         pgtype.Int8
	PreviousOwnerUserID pgtype.Int8
}

// GetEventOwners reads the Owner after a lifecycle event of an Alert Group and the previous Owner it recorded.
func (q *Queries) GetEventOwners(ctx context.Context, arg GetEventOwnersParams) (GetEventOwnersRow, error) {
	row := q.db.QueryRow(ctx, getEventOwners, arg.OrgID, arg.AlertGroupID, arg.EventSeq)
	var i GetEventOwnersRow
	err := row.Scan(&i.OwnerUserID, &i.PreviousOwnerUserID)
	return i, err
}

const listFooterUsernames = `-- name: ListFooterUsernames :many
SELECT al.identity_space, al.username::text AS username
FROM alert_groups g
JOIN account_links al ON al.org_id = g.org_id
                     AND al.user_id = CASE g.status WHEN 'acknowledged' THEN g.owner_user_id
                                                    WHEN 'snoozed' THEN g.snoozed_by_user_id
                                                    WHEN 'resolved' THEN g.resolved_by_user_id END
WHERE g.org_id = $1 AND g.id = $2 AND al.username IS NOT NULL AND al.username <> ''
ORDER BY al.identity_space
`

type ListFooterUsernamesParams struct {
	OrgID int64
	ID    int64
}

type ListFooterUsernamesRow struct {
	IdentitySpace string
	Username      string
}

// ListFooterUsernames lists the usernames, by identity space, of the user the footer of an Alert Group names: its
// Owner while acknowledged, who snoozed it while snoozed, who resolved it while resolved.
func (q *Queries) ListFooterUsernames(ctx context.Context, arg ListFooterUsernamesParams) ([]ListFooterUsernamesRow, error) {
	rows, err := q.db.Query(ctx, listFooterUsernames, arg.OrgID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFooterUsernamesRow{}
	for rows.Next() {
		var i ListFooterUsernamesRow
		if err := rows.Scan(&i.IdentitySpace, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveUserPublicIDs = `-- name: ListLiveUserPublicIDs :many
SELECT public_id
FROM users
WHERE org_id = $1 AND status <> 'deleted' AND public_id = ANY($2::text[])
`

type ListLiveUserPublicIDsParams struct {
	OrgID     int64
	PublicIds []string
}

// ListLiveUserPublicIDs lists which of the public_ids name Users that are not deleted.
func (q *Queries) ListLiveUserPublicIDs(ctx context.Context, arg ListLiveUserPublicIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listLiveUserPublicIDs, arg.OrgID, arg.PublicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var public_id string
		if err := rows.Scan(&public_id); err != nil {
			return nil, err
		}
		items = append(items, public_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionUsers = `-- name: ListMentionUsers :many
SELECT u.id, u.public_id, u.name, u.login, coalesce(al.username, '')::text AS username
FROM users u
LEFT JOIN account_links al ON al.org_id = u.org_id AND al.user_id = u.id
                          AND al.identity_space = $1::text
WHERE u.org_id = $2 AND u.status <> 'deleted'
  AND (u.id = ANY($3::bigint[]) OR u.public_id = ANY($4::text[]))
ORDER BY u.id
`

type ListMentionUsersParams struct {
	IdentitySpace string
	OrgID         int64
	Ids           []int64
	PublicIds     []string
}

type ListMentionUsersRow struct {
	ID       int64
	PublicID string
	Name     string
	Login    string
	Username string
}

// ListMentionUsers reads the Users that are not deleted among the ids and the public_ids, with the username of their
// Account link in the identity space, empty without one.
func (q *Queries) ListMentionUsers(ctx context.Context, arg ListMentionUsersParams) ([]ListMentionUsersRow, error) {
	rows, err := q.db.Query(ctx, listMentionUsers,
		arg.IdentitySpace,
		arg.OrgID,
		arg.Ids,
		arg.PublicIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMentionUsersRow{}
	for rows.Next() {
		var i ListMentionUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Login,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
