// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*)
FROM users
WHERE org_id = $1 AND role = 'admin' AND status <> 'deleted'
`

// CountAdmins counts the Admins that are not deleted; a disabled Admin still counts.
func (q *Queries) CountAdmins(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    org_id, public_id, login, name, email, role, source, status, password_hash, password_changed_at, created_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'active', $8,
    $9, $10, $10
)
RETURNING id
`

type CreateUserParams struct {
	OrgID             int64
	PublicID          string
	Login             string
	Name              string
	Email             pgtype.Text
	Role              string
	Source            string
	PasswordHash      pgtype.Text
	PasswordChangedAt pgtype.Timestamptz
	CreatedAt         time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.OrgID,
		arg.PublicID,
		arg.Login,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Source,
		arg.PasswordHash,
		arg.PasswordChangedAt,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one

SELECT u.id, u.public_id, u.login, u.name, u.email, u.role, u.source, u.status, (u.password_hash IS NOT NULL)::boolean AS has_password,
       (u.oidc_subject IS NOT NULL)::boolean AS has_oidc_identity,
       (u.oidc_offline_token_ciphertext IS NOT NULL)::boolean AS has_offline_token,
       u.time_zone, u.language, u.last_sign_in_at, u.created_at, u.version,
       EXISTS (
           SELECT 1 FROM user_totp t
           WHERE t.org_id = u.org_id AND t.user_id = u.id AND t.enrolled_at IS NOT NULL
       ) AS totp_enabled
FROM users u
WHERE u.org_id = $1 AND u.id = $2
`

type GetUserParams struct {
	OrgID int64
	ID    int64
}

type GetUserRow struct {
	ID              int64
	PublicID        string
	Login           string
	Name            string
	Email           pgtype.Text
	Role            string
	Source          string
	Status          string
	HasPassword     bool
	HasOidcIdentity bool
	HasOfflineToken bool
	TimeZone        pgtype.Text
	Language        pgtype.Text
	LastSignInAt    pgtype.Timestamptz
	CreatedAt       time.Time
	Version         int64
	TotpEnabled     bool
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, arg.OrgID, arg.ID)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Login,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Source,
		&i.Status,
		&i.HasPassword,
		&i.HasOidcIdentity,
		&i.HasOfflineToken,
		&i.TimeZone,
		&i.Language,
		&i.LastSignInAt,
		&i.CreatedAt,
		&i.Version,
		&i.TotpEnabled,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :execrows
UPDATE users
SET name = $1, time_zone = $2, language = $3, updated_at = $4,
    version = version + 1
WHERE org_id = $5 AND id = $6
`

type UpdateProfileParams struct {
	Name      string
	TimeZone  pgtype.Text
	Language  pgtype.Text
	UpdatedAt time.Time
	OrgID     int64
	ID        int64
}

// UpdateProfile changes what the user edits in the profile: the display name, the time zone and the language.
func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProfile,
		arg.Name,
		arg.TimeZone,
		arg.Language,
		arg.UpdatedAt,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
