// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEntry = `-- name: InsertAuditEntry :exec

INSERT INTO audit_log (
    org_id, public_id, at, actor_kind, actor_user_id, actor_service_account_id, actor_name, api_token_id, token_name,
    transport, action, resource_type, resource_public_id, resource_name, diff, details, source_address
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17
)
`

type InsertAuditEntryParams struct {
	OrgID                 int64
	PublicID              string
	At                    time.Time
	ActorKind             string
	ActorUserID           pgtype.Int8
	ActorServiceAccountID pgtype.Int8
	ActorName             pgtype.Text
	ApiTokenID            pgtype.Int8
	TokenName             pgtype.Text
	Transport             string
	Action                string
	ResourceType          pgtype.Text
	ResourcePublicID      pgtype.Text
	ResourceName          pgtype.Text
	Diff                  []byte
	Details               []byte
	SourceAddress         *netip.Addr
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.OrgID,
		arg.PublicID,
		arg.At,
		arg.ActorKind,
		arg.ActorUserID,
		arg.ActorServiceAccountID,
		arg.ActorName,
		arg.ApiTokenID,
		arg.TokenName,
		arg.Transport,
		arg.Action,
		arg.ResourceType,
		arg.ResourcePublicID,
		arg.ResourceName,
		arg.Diff,
		arg.Details,
		arg.SourceAddress,
	)
	return err
}
