// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
)

const listDetachedPartitions = `-- name: ListDetachedPartitions :many
SELECT c.relname::text AS name
FROM pg_catalog.pg_class c
WHERE c.relkind = 'r'
  AND NOT c.relispartition
  AND starts_with(c.relname::text, $1::text)
  AND c.relnamespace = (SELECT n.oid FROM pg_catalog.pg_namespace n WHERE n.nspname = current_schema())
ORDER BY c.relname
`

// ListDetachedPartitions lists the tables of the current schema whose name starts with prefix and that are not
// partitions: a partition whose detach succeeded and whose drop did not.
func (q *Queries) ListDetachedPartitions(ctx context.Context, prefix string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDetachedPartitions, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartitions = `-- name: ListPartitions :many

SELECT c.relname::text AS name, i.inhdetachpending AS detach_pending
FROM pg_catalog.pg_inherits i
JOIN pg_catalog.pg_class c ON c.oid = i.inhrelid
JOIN pg_catalog.pg_class p ON p.oid = i.inhparent
WHERE p.relname = $1::text
  AND p.relnamespace = (SELECT n.oid FROM pg_catalog.pg_namespace n WHERE n.nspname = current_schema())
ORDER BY c.relname
`

type ListPartitionsRow struct {
	Name          string
	DetachPending bool
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// ListPartitions lists the partitions of a partitioned table of the current schema, with whether a DETACH
// CONCURRENTLY of it was interrupted.
func (q *Queries) ListPartitions(ctx context.Context, parent string) ([]ListPartitionsRow, error) {
	rows, err := q.db.Query(ctx, listPartitions, parent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPartitionsRow{}
	for rows.Next() {
		var i ListPartitionsRow
		if err := rows.Scan(&i.Name, &i.DetachPending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetention = `-- name: ListRetention :many
SELECT id, retention_stored_snapshots_days, retention_alert_details_days, retention_audit_log_days
FROM organizations
ORDER BY id
`

type ListRetentionRow struct {
	ID                           int64
	RetentionStoredSnapshotsDays int64
	RetentionAlertDetailsDays    int64
	RetentionAuditLogDays        int64
}

// ListRetention lists the retention periods of every Organization, in days.
func (q *Queries) ListRetention(ctx context.Context) ([]ListRetentionRow, error) {
	rows, err := q.db.Query(ctx, listRetention)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRetentionRow{}
	for rows.Next() {
		var i ListRetentionRow
		if err := rows.Scan(
			&i.ID,
			&i.RetentionStoredSnapshotsDays,
			&i.RetentionAlertDetailsDays,
			&i.RetentionAuditLogDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
