// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpDestinationVersion = `-- name: BumpDestinationVersion :one
UPDATE destinations
SET version = version + 1, updated_at = $1::timestamptz
WHERE org_id = $2 AND id = $3
RETURNING version
`

type BumpDestinationVersionParams struct {
	Now   time.Time
	OrgID int64
	ID    int64
}

// BumpDestinationVersion gives a Destination whose Secrets changed its next version, the ETag of its Secrets.
func (q *Queries) BumpDestinationVersion(ctx context.Context, arg BumpDestinationVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpDestinationVersion, arg.Now, arg.OrgID, arg.ID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM destination_secrets
WHERE org_id = $1 AND destination_id = $2 AND name = $3
`

type DeleteSecretParams struct {
	OrgID         int64
	DestinationID int64
	Name          string
}

// DeleteSecret deletes a Secret of a Destination; no row when it does not exist.
func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret, arg.OrgID, arg.DestinationID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBodyServiceAccount = `-- name: GetBodyServiceAccount :one
SELECT public_id, name
FROM service_accounts
WHERE org_id = $1 AND id = $2
`

type GetBodyServiceAccountParams struct {
	OrgID int64
	ID    int64
}

type GetBodyServiceAccountRow struct {
	PublicID string
	Name     string
}

// GetBodyServiceAccount reads a Service account as the body of an event names it.
func (q *Queries) GetBodyServiceAccount(ctx context.Context, arg GetBodyServiceAccountParams) (GetBodyServiceAccountRow, error) {
	row := q.db.QueryRow(ctx, getBodyServiceAccount, arg.OrgID, arg.ID)
	var i GetBodyServiceAccountRow
	err := row.Scan(&i.PublicID, &i.Name)
	return i, err
}

const getBodyUser = `-- name: GetBodyUser :one
SELECT public_id, name, login
FROM users
WHERE org_id = $1 AND id = $2
`

type GetBodyUserParams struct {
	OrgID int64
	ID    int64
}

type GetBodyUserRow struct {
	PublicID string
	Name     string
	Login    string
}

// GetBodyUser reads a User as the body of an event names them.
func (q *Queries) GetBodyUser(ctx context.Context, arg GetBodyUserParams) (GetBodyUserRow, error) {
	row := q.db.QueryRow(ctx, getBodyUser, arg.OrgID, arg.ID)
	var i GetBodyUserRow
	err := row.Scan(&i.PublicID, &i.Name, &i.Login)
	return i, err
}

const getTarget = `-- name: GetTarget :one
SELECT id, public_id, webhook_mode, webhook_events_config, webhook_template_config, proxy, proxy_password_ciphertext,
       proxy_password_key_id,
       signing_secret_ciphertext, signing_secret_key_id, previous_signing_secret_ciphertext,
       previous_signing_secret_key_id
FROM destinations
WHERE org_id = $1 AND id = $2 AND type = 'webhook'
`

type GetTargetParams struct {
	OrgID int64
	ID    int64
}

type GetTargetRow struct {
	ID                              int64
	PublicID                        string
	WebhookMode                     pgtype.Text
	WebhookEventsConfig             []byte
	WebhookTemplateConfig           []byte
	Proxy                           []byte
	ProxyPasswordCiphertext         []byte
	ProxyPasswordKeyID              pgtype.Text
	SigningSecretCiphertext         []byte
	SigningSecretKeyID              pgtype.Text
	PreviousSigningSecretCiphertext []byte
	PreviousSigningSecretKeyID      pgtype.Text
}

// GetTarget reads what a request of an outgoing webhook needs, in either mode, deleted or not: a call in flight when it
// was deleted still signs with its secrets, which delivery wipes once no call of it holds a lease.
func (q *Queries) GetTarget(ctx context.Context, arg GetTargetParams) (GetTargetRow, error) {
	row := q.db.QueryRow(ctx, getTarget, arg.OrgID, arg.ID)
	var i GetTargetRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WebhookMode,
		&i.WebhookEventsConfig,
		&i.WebhookTemplateConfig,
		&i.Proxy,
		&i.ProxyPasswordCiphertext,
		&i.ProxyPasswordKeyID,
		&i.SigningSecretCiphertext,
		&i.SigningSecretKeyID,
		&i.PreviousSigningSecretCiphertext,
		&i.PreviousSigningSecretKeyID,
	)
	return i, err
}

const getTemplateConfig = `-- name: GetTemplateConfig :one
SELECT webhook_template_config
FROM destinations
WHERE org_id = $1 AND id = $2 AND type = 'webhook'
`

type GetTemplateConfigParams struct {
	OrgID int64
	ID    int64
}

// GetTemplateConfig reads the request templates of an outgoing webhook, deleted or not, through the transaction of a
// change, to render the Desired state of its template mode; null in the events mode.
func (q *Queries) GetTemplateConfig(ctx context.Context, arg GetTemplateConfigParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTemplateConfig, arg.OrgID, arg.ID)
	var webhook_template_config []byte
	err := row.Scan(&webhook_template_config)
	return webhook_template_config, err
}

const getWebhookDestination = `-- name: GetWebhookDestination :one


SELECT id, public_id, name, type, version, (signing_secret_ciphertext IS NOT NULL)::boolean AS signing_secret_set,
       signing_secret_updated_at, previous_signing_secret_since
FROM destinations
WHERE org_id = $1 AND public_id = $2 AND deleted_at IS NULL
`

type GetWebhookDestinationParams struct {
	OrgID    int64
	PublicID string
}

type GetWebhookDestinationRow struct {
	ID                         int64
	PublicID                   string
	Name                       string
	Type                       string
	Version                    int64
	SigningSecretSet           bool
	SigningSecretUpdatedAt     pgtype.Timestamptz
	PreviousSigningSecretSince pgtype.Timestamptz
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// Outgoing webhooks (C-15): the Signing secrets and the named Secrets of an outgoing webhook Destination, what an
// events-mode request needs of its Destination, and what the version 1 body reads of an Alert Group. Secret values are
// read only to send a request; the API reads their status.
// GetWebhookDestination reads a Destination that is not deleted, of any type, with the status of its Signing secrets.
func (q *Queries) GetWebhookDestination(ctx context.Context, arg GetWebhookDestinationParams) (GetWebhookDestinationRow, error) {
	row := q.db.QueryRow(ctx, getWebhookDestination, arg.OrgID, arg.PublicID)
	var i GetWebhookDestinationRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.SigningSecretSet,
		&i.SigningSecretUpdatedAt,
		&i.PreviousSigningSecretSince,
	)
	return i, err
}

const listBodyAlerts = `-- name: ListBodyAlerts :many
SELECT DISTINCT ON (a.fingerprint) a.fingerprint, a.labels, m.annotations, m.starts_at, m.ended_at, m.resolve_reason,
       a.generator_url, m.state
FROM alert_group_alerts m
JOIN alerts a ON a.org_id = m.org_id AND a.id = m.alert_id
WHERE m.org_id = $1 AND m.alert_group_id = $2 AND m.state IN ('firing', 'resolved')
ORDER BY a.fingerprint, m.id DESC
`

type ListBodyAlertsParams struct {
	OrgID        int64
	AlertGroupID int64
}

type ListBodyAlertsRow struct {
	Fingerprint   string
	Labels        []byte
	Annotations   []byte
	StartsAt      time.Time
	EndedAt       pgtype.Timestamptz
	ResolveReason pgtype.Text
	GeneratorUrl  pgtype.Text
	State         string
}

// ListBodyAlerts lists the Alerts of an Alert Group for the body of an event, one per fingerprint with its latest
// membership, Alerts that moved to another Alert Group left out, by fingerprint.
func (q *Queries) ListBodyAlerts(ctx context.Context, arg ListBodyAlertsParams) ([]ListBodyAlertsRow, error) {
	rows, err := q.db.Query(ctx, listBodyAlerts, arg.OrgID, arg.AlertGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBodyAlertsRow{}
	for rows.Next() {
		var i ListBodyAlertsRow
		if err := rows.Scan(
			&i.Fingerprint,
			&i.Labels,
			&i.Annotations,
			&i.StartsAt,
			&i.EndedAt,
			&i.ResolveReason,
			&i.GeneratorUrl,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretValues = `-- name: ListSecretValues :many
SELECT name, value_ciphertext, value_key_id
FROM destination_secrets
WHERE org_id = $1 AND destination_id = $2
ORDER BY name
`

type ListSecretValuesParams struct {
	OrgID         int64
	DestinationID int64
}

type ListSecretValuesRow struct {
	Name            string
	ValueCiphertext []byte
	ValueKeyID      string
}

// ListSecretValues reads the encrypted values of the Secrets of a Destination, by name.
func (q *Queries) ListSecretValues(ctx context.Context, arg ListSecretValuesParams) ([]ListSecretValuesRow, error) {
	rows, err := q.db.Query(ctx, listSecretValues, arg.OrgID, arg.DestinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretValuesRow{}
	for rows.Next() {
		var i ListSecretValuesRow
		if err := rows.Scan(&i.Name, &i.ValueCiphertext, &i.ValueKeyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT name, value_updated_at
FROM destination_secrets
WHERE org_id = $1 AND destination_id = $2
ORDER BY name
`

type ListSecretsParams struct {
	OrgID         int64
	DestinationID int64
}

type ListSecretsRow struct {
	Name           string
	ValueUpdatedAt time.Time
}

// ListSecrets lists the names of the Secrets of a Destination with the time of their last change, by name.
func (q *Queries) ListSecrets(ctx context.Context, arg ListSecretsParams) ([]ListSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSecrets, arg.OrgID, arg.DestinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsRow{}
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(&i.Name, &i.ValueUpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWebhookDestination = `-- name: LockWebhookDestination :one
SELECT id, public_id, name, type, version, signing_secret_ciphertext, signing_secret_key_id, signing_secret_updated_at,
       previous_signing_secret_since
FROM destinations
WHERE org_id = $1 AND public_id = $2 AND deleted_at IS NULL
FOR NO KEY UPDATE
`

type LockWebhookDestinationParams struct {
	OrgID    int64
	PublicID string
}

type LockWebhookDestinationRow struct {
	ID                         int64
	PublicID                   string
	Name                       string
	Type                       string
	Version                    int64
	SigningSecretCiphertext    []byte
	SigningSecretKeyID         pgtype.Text
	SigningSecretUpdatedAt     pgtype.Timestamptz
	PreviousSigningSecretSince pgtype.Timestamptz
}

// LockWebhookDestination locks a Destination that is not deleted, of any type, for a change of its secrets, with its
// Signing secrets.
func (q *Queries) LockWebhookDestination(ctx context.Context, arg LockWebhookDestinationParams) (LockWebhookDestinationRow, error) {
	row := q.db.QueryRow(ctx, lockWebhookDestination, arg.OrgID, arg.PublicID)
	var i LockWebhookDestinationRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.SigningSecretCiphertext,
		&i.SigningSecretKeyID,
		&i.SigningSecretUpdatedAt,
		&i.PreviousSigningSecretSince,
	)
	return i, err
}

const retirePreviousSigningSecret = `-- name: RetirePreviousSigningSecret :one
UPDATE destinations
SET previous_signing_secret_ciphertext = NULL, previous_signing_secret_key_id = NULL,
    previous_signing_secret_since = NULL, updated_at = $1::timestamptz, version = version + 1
WHERE org_id = $2 AND id = $3 AND previous_signing_secret_ciphertext IS NOT NULL
RETURNING version
`

type RetirePreviousSigningSecretParams struct {
	Now   time.Time
	OrgID int64
	ID    int64
}

// RetirePreviousSigningSecret wipes the previous Signing secret, which signs no more. No row when there is none.
func (q *Queries) RetirePreviousSigningSecret(ctx context.Context, arg RetirePreviousSigningSecretParams) (int64, error) {
	row := q.db.QueryRow(ctx, retirePreviousSigningSecret, arg.Now, arg.OrgID, arg.ID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const rotateSigningSecret = `-- name: RotateSigningSecret :one
UPDATE destinations
SET previous_signing_secret_ciphertext = $1::bytea,
    previous_signing_secret_key_id = $2::text,
    previous_signing_secret_since = CASE WHEN $1::bytea IS NULL THEN NULL
                                         ELSE $3::timestamptz END,
    signing_secret_ciphertext = $4,
    signing_secret_key_id = $5, signing_secret_updated_at = $3::timestamptz, updated_at = $3::timestamptz,
    version = version + 1
WHERE org_id = $6 AND id = $7
RETURNING version
`

type RotateSigningSecretParams struct {
	PreviousCiphertext []byte
	PreviousKeyID      pgtype.Text
	Now                time.Time
	Ciphertext         []byte
	KeyID              pgtype.Text
	OrgID              int64
	ID                 int64
}

// RotateSigningSecret makes the current Signing secret the previous one, which still signs since @now — none when it
// had none — and stores the new one, and gives the Destination its next version.
func (q *Queries) RotateSigningSecret(ctx context.Context, arg RotateSigningSecretParams) (int64, error) {
	row := q.db.QueryRow(ctx, rotateSigningSecret,
		arg.PreviousCiphertext,
		arg.PreviousKeyID,
		arg.Now,
		arg.Ciphertext,
		arg.KeyID,
		arg.OrgID,
		arg.ID,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const upsertSecret = `-- name: UpsertSecret :exec
INSERT INTO destination_secrets (destination_id, org_id, name, value_ciphertext, value_key_id, value_updated_at)
VALUES ($1, $2, $3, $4, $5, $6::timestamptz)
ON CONFLICT (destination_id, name)
DO UPDATE SET value_ciphertext = excluded.value_ciphertext, value_key_id = excluded.value_key_id,
              value_updated_at = excluded.value_updated_at
`

type UpsertSecretParams struct {
	DestinationID   int64
	OrgID           int64
	Name            string
	ValueCiphertext []byte
	ValueKeyID      string
	Now             time.Time
}

// UpsertSecret creates or replaces a Secret of a Destination.
func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) error {
	_, err := q.db.Exec(ctx, upsertSecret,
		arg.DestinationID,
		arg.OrgID,
		arg.Name,
		arg.ValueCiphertext,
		arg.ValueKeyID,
		arg.Now,
	)
	return err
}
