// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueTimers = `-- name: ClaimDueTimers :many


UPDATE timers t
SET lease_owner = $1::text, lease_until = $2::timestamptz, attempts = t.attempts + 1
FROM (SELECT d.id
      FROM timers d
      WHERE d.org_id = $3 AND d.deadline <= $4 AND d.kind = ANY($5::text[])
        AND (d.lease_until IS NULL OR d.lease_until <= $6::timestamptz)
      ORDER BY d.deadline, d.id
      LIMIT $7
      FOR UPDATE SKIP LOCKED) AS due
WHERE t.org_id = $3 AND t.id = due.id
RETURNING t.id, t.alert_group_id, t.storm_id, t.kind, t.deadline, t.attempts
`

type ClaimDueTimersParams struct {
	Owner      string
	LeaseUntil time.Time
	OrgID      int64
	Due        time.Time
	Kinds      []string
	Now        time.Time
	Lim        int32
}

type ClaimDueTimersRow struct {
	ID           int64
	AlertGroupID pgtype.Int8
	StormID      pgtype.Int8
	Kind         string
	Deadline     time.Time
	Attempts     int64
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// The claim of the timer rows (schema.md §5): due on the business clock, leased on the real clock.
// ClaimDueTimers leases the due timers of the kinds this replica fires whose lease is free or ran out, earliest
// first; another claimer skips the rows this one locked.
func (q *Queries) ClaimDueTimers(ctx context.Context, arg ClaimDueTimersParams) ([]ClaimDueTimersRow, error) {
	rows, err := q.db.Query(ctx, claimDueTimers,
		arg.Owner,
		arg.LeaseUntil,
		arg.OrgID,
		arg.Due,
		arg.Kinds,
		arg.Now,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueTimersRow{}
	for rows.Next() {
		var i ClaimDueTimersRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertGroupID,
			&i.StormID,
			&i.Kind,
			&i.Deadline,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFiredTimer = `-- name: DeleteFiredTimer :exec
DELETE FROM timers
WHERE org_id = $1 AND id = $2 AND lease_owner = $3::text AND deadline = $4
`

type DeleteFiredTimerParams struct {
	OrgID    int64
	ID       int64
	Owner    string
	Deadline time.Time
}

// DeleteFiredTimer removes a timer that fired, unless it was rescheduled since it was claimed.
func (q *Queries) DeleteFiredTimer(ctx context.Context, arg DeleteFiredTimerParams) error {
	_, err := q.db.Exec(ctx, deleteFiredTimer,
		arg.OrgID,
		arg.ID,
		arg.Owner,
		arg.Deadline,
	)
	return err
}

const holdsTimer = `-- name: HoldsTimer :one
SELECT EXISTS (
    SELECT 1
    FROM timers
    WHERE org_id = $1 AND id = $2 AND lease_owner = $3::text AND lease_until > $4::timestamptz
)::boolean AS held
`

type HoldsTimerParams struct {
	OrgID int64
	ID    int64
	Owner string
	Now   time.Time
}

// HoldsTimer reports whether the lease of a claimed timer is still this replica's at now: a timer that was
// rescheduled meanwhile lost its lease.
func (q *Queries) HoldsTimer(ctx context.Context, arg HoldsTimerParams) (bool, error) {
	row := q.db.QueryRow(ctx, holdsTimer,
		arg.OrgID,
		arg.ID,
		arg.Owner,
		arg.Now,
	)
	var held bool
	err := row.Scan(&held)
	return held, err
}

const nextTimerDeadline = `-- name: NextTimerDeadline :one
SELECT coalesce(min(deadline) FILTER (WHERE lease_until IS NULL OR lease_until <= $1::timestamptz),
                '0001-01-01 00:00:00+00')::timestamptz AS free_deadline,
       coalesce(min(lease_until) FILTER (WHERE lease_until > $1::timestamptz),
                '0001-01-01 00:00:00+00')::timestamptz AS lease_end
FROM timers
WHERE org_id = $2 AND kind = ANY($3::text[])
`

type NextTimerDeadlineParams struct {
	Now   time.Time
	OrgID int64
	Kinds []string
}

type NextTimerDeadlineRow struct {
	FreeDeadline time.Time
	LeaseEnd     time.Time
}

// NextTimerDeadline is when the next timer of the kinds this replica fires can be claimed: the earliest deadline of a
// row whose lease is free at the real time now (business clock), and the earliest end of a lease still held (real
// clock); each the zero time 0001-01-01 when there is none.
func (q *Queries) NextTimerDeadline(ctx context.Context, arg NextTimerDeadlineParams) (NextTimerDeadlineRow, error) {
	row := q.db.QueryRow(ctx, nextTimerDeadline, arg.Now, arg.OrgID, arg.Kinds)
	var i NextTimerDeadlineRow
	err := row.Scan(&i.FreeDeadline, &i.LeaseEnd)
	return i, err
}
