// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors

// Command refgen writes the reference pages of the log event registry, the metric registry and the Internal alert
// registry (C-02.FR-18, C-02.FR-19, C-06.FR-14) into a directory, docs/reference by default. make generate runs it,
// and make generate-check fails when a checked-in page differs from what it writes. It fails when a registry is
// invalid.
package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/muster-io/muster/internal/internalalerts"
	"github.com/muster-io/muster/internal/logging"
	"github.com/muster-io/muster/internal/metrics"
)

const (
	logEventsPage      = "log-events.md"
	metricsPage        = "metrics.md"
	internalAlertsPage = "internal-alerts.md"

	header = "<!-- Code generated by internal/tools/refgen from %s. DO NOT EDIT. -->\n\n"
)

const logEventsIntro = "# Log events\n\n" +
	"Muster writes one JSON object per line on stdout, and every line is one of the events below. A line has `time`\n" +
	"(RFC 3339, UTC), `level`, `event` and the fields of its event; a secret is written as `[redacted]`. ERROR means\n" +
	"someone must look within the hour, WARN that the line is needed for an investigation, INFO that an investigation\n" +
	"is impossible without it; `MUSTER_LOG_LEVEL` sets the lowest level written. The capability is the one that logs\n" +
	"the event.\n\n" +
	"| Event | Level | Fields | Capability | Description |\n" +
	"|---|---|---|---|---|\n"

const metricsIntro = "# Metrics\n\n" +
	"Muster serves these metrics in the Prometheus text format at `/metrics` on the internal listener and never pushes\n" +
	"them; the endpoint also serves the process (`process_*`) and Go runtime (`go_*`) metrics. Configuration entities\n" +
	"appear only by their `public_id` (`integration`, `route`, `destination`); the labels of an `*_info` metric carry\n" +
	"what it describes, such as a name or the version; every other label takes its values from the closed set listed\n" +
	"below. Histograms are Prometheus histograms with `le` buckets. A Leader-only metric is exported only by the\n" +
	"replica that is the Leader. The capability is the one that exports the metric.\n\n" +
	"| Metric | Type | Labels | Capability | Leader only | Description |\n" +
	"|---|---|---|---|---|---|\n"

const internalAlertsIntro = "# Internal alerts\n\n" +
	"Muster reports problems it can still report through its own pipeline as Internal alerts: Alerts of the built-in\n" +
	"\"Muster\" Integration, which every Organization has from the first start. Each raise and each resolve is a\n" +
	"synthetic Stored Snapshot of that Integration, listed with its other Stored Snapshots and processed in order with\n" +
	"them. Muster raises and resolves them explicitly when their condition changes; they are never resolved as Gone or\n" +
	"Stale. Besides `alertname` and `severity`, a configuration entity appears by its immutable id (`integration`,\n" +
	"`route`, `destination`) with its current name in a `*_name` label; the fingerprint is computed from `alertname` and\n" +
	"the id label only, so renaming the entity updates the open Internal alert instead of raising a new one. Every\n" +
	"Internal alert carries the annotations `summary`, `description` and `runbook_url`, the runbook page under\n" +
	"`MUSTER_RUNBOOK_BASE_URL`. The capability is the one that raises it.\n\n" +
	"| Internal alert | Severity | Labels | Capability | Runbook | Raised while |\n" +
	"|---|---|---|---|---|---|\n"

var cellEscaper = strings.NewReplacer("|", `\|`, "\n", " ")

func main() {
	os.Exit(run(os.Args[1:], os.Stderr))
}

func run(args []string, stderr io.Writer) int {
	flags := flag.NewFlagSet("refgen", flag.ContinueOnError)
	flags.SetOutput(stderr)
	out := flags.String("out", "docs/reference", "the directory of the reference pages")
	if err := flags.Parse(args); err != nil {
		return 2
	}
	events, eventsErr := logging.Events()
	defs, metricsErr := metrics.Catalogue()
	alerts, alertsErr := internalalerts.Definitions()
	if err := errors.Join(eventsErr, metricsErr, alertsErr); err != nil {
		fmt.Fprintf(stderr, "refgen: invalid registry:\n%v\n", err)
		return 1
	}
	pages := map[string]string{
		logEventsPage:      logEventsMarkdown(events),
		metricsPage:        metricsMarkdown(defs),
		internalAlertsPage: internalAlertsMarkdown(alerts),
	}
	if err := os.MkdirAll(*out, 0o750); err != nil {
		fmt.Fprintf(stderr, "refgen: %v\n", err)
		return 1
	}
	for name, content := range pages {
		if err := os.WriteFile(filepath.Join(*out, name), []byte(content), 0o600); err != nil {
			fmt.Fprintf(stderr, "refgen: %v\n", err)
			return 1
		}
	}
	return 0
}

func logEventsMarkdown(events []logging.EventInfo) string {
	var b strings.Builder
	fmt.Fprintf(&b, header, "internal/logging/events.go")
	b.WriteString(logEventsIntro)
	for _, e := range events {
		fields := strings.Join(e.Fields, ", ")
		if fields == "" {
			fields = "—"
		}
		levels := make([]string, 0, len(e.Levels))
		for _, l := range e.Levels {
			levels = append(levels, l.String())
		}
		if len(levels) == 0 {
			levels = append(levels, e.Level.String())
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n", e.Name, strings.Join(levels, " or "), fields, e.Capability,
			cell(e.Description))
	}
	return b.String()
}

func metricsMarkdown(defs []metrics.Definition) string {
	var b strings.Builder
	fmt.Fprintf(&b, header, "internal/metrics/catalogue.go")
	b.WriteString(metricsIntro)
	for _, d := range defs {
		names := make([]string, 0, len(d.Labels))
		for _, l := range d.Labels {
			names = append(names, l.Name)
		}
		labels := strings.Join(names, ", ")
		if labels == "" {
			labels = "—"
		}
		leader := "no"
		if d.LeaderOnly {
			leader = "yes"
		}
		description := d.Help
		if len(d.Buckets) > 0 {
			bounds := make([]string, 0, len(d.Buckets))
			for _, v := range d.Buckets {
				bounds = append(bounds, strconv.FormatFloat(v, 'g', -1, 64))
			}
			description += " Buckets (le): " + strings.Join(bounds, ", ") + "."
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s |\n", d.Name, d.Kind, labels, d.Capability, leader, cell(description))
	}
	b.WriteString(`
## Label values

| Metric | Label | Values |
|---|---|---|
`)
	for _, d := range defs {
		for _, l := range d.Labels {
			fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", d.Name, l.Name, cell(labelValues(l)))
		}
	}
	return b.String()
}

func internalAlertsMarkdown(defs []*internalalerts.Definition) string {
	var b strings.Builder
	fmt.Fprintf(&b, header, "internal/internalalerts/registry.go")
	b.WriteString(internalAlertsIntro)
	for _, d := range defs {
		labels := make([]string, 0, len(d.Labels()))
		for _, l := range d.Labels() {
			labels = append(labels, "`"+l+"`")
		}
		list := strings.Join(labels, ", ")
		if list == "" {
			list = "—"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | `%s` | %s |\n", d.Name, d.Severity, list, d.Capability, d.Runbook(),
			cell(d.Condition))
	}
	return b.String()
}

func labelValues(l metrics.Label) string {
	switch l.Kind {
	case metrics.LabelClosed:
		values := make([]string, 0, len(l.Values))
		for _, v := range l.Values {
			values = append(values, "`"+v+"`")
		}
		return strings.Join(values, ", ") + " — " + l.Description
	case metrics.LabelEntity:
		return "entity: " + l.Description
	case metrics.LabelInfo:
		return "info: " + l.Description
	}
	return l.Description
}

func cell(s string) string {
	return cellEscaper.Replace(s)
}
