// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLeaderStart = `-- name: GetLeaderStart :one
SELECT r.leader_since,
       coalesce((SELECT max(d.ended_at) FROM downtime_periods d) >= r.leader_since, false)::boolean AS after_downtime
FROM runtime_state r
`

type GetLeaderStartRow struct {
	LeaderSince   pgtype.Timestamptz
	AfterDowntime bool
}

// GetLeaderStart reads when the current Leader started leading and whether it recorded a downtime on taking over:
// the takeover that records a downtime ends it at the moment it starts leading. Both are installation-wide.
func (q *Queries) GetLeaderStart(ctx context.Context) (GetLeaderStartRow, error) {
	row := q.db.QueryRow(ctx, getLeaderStart)
	var i GetLeaderStartRow
	err := row.Scan(&i.LeaderSince, &i.AfterDowntime)
	return i, err
}

const listHeartbeats = `-- name: ListHeartbeats :many
SELECT public_id, heartbeat_state
FROM integrations
WHERE org_id = $1 AND deleted_at IS NULL AND heartbeat_enabled
ORDER BY id
`

type ListHeartbeatsRow struct {
	PublicID       string
	HeartbeatState string
}

// ListHeartbeats lists the Integrations that are not deleted and have their Heartbeat on, with its state, for
// muster_heartbeat_lost.
func (q *Queries) ListHeartbeats(ctx context.Context, orgID int64) ([]ListHeartbeatsRow, error) {
	rows, err := q.db.Query(ctx, listHeartbeats, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeartbeatsRow{}
	for rows.Next() {
		var i ListHeartbeatsRow
		if err := rows.Scan(&i.PublicID, &i.HeartbeatState); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdue = `-- name: ListOverdue :many
SELECT id
FROM integrations
WHERE org_id = $1 AND deleted_at IS NULL AND heartbeat_state = 'live'
  AND greatest(heartbeat_last_signal_at, $2::timestamptz)
      + make_interval(secs => heartbeat_timeout_seconds) < $3::timestamptz
ORDER BY id
`

type ListOverdueParams struct {
	OrgID        int64
	MeasuredFrom pgtype.Timestamptz
	Now          time.Time
}

// ListOverdue lists the Integrations whose Heartbeat is live and whose last signal, or @measured_from when it is later,
// is older than their timeout at @now.
func (q *Queries) ListOverdue(ctx context.Context, arg ListOverdueParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOverdue, arg.OrgID, arg.MeasuredFrom, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockHeartbeat = `-- name: LockHeartbeat :one

SELECT id, public_id, name, static_labels, builtin, heartbeat_enabled, heartbeat_timeout_seconds, heartbeat_state,
       heartbeat_last_signal_at, heartbeat_lost_since
FROM integrations
WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
FOR NO KEY UPDATE
`

type LockHeartbeatParams struct {
	OrgID int64
	ID    int64
}

type LockHeartbeatRow struct {
	ID                      int64
	PublicID                string
	Name                    string
	StaticLabels            []byte
	Builtin                 bool
	HeartbeatEnabled        bool
	HeartbeatTimeoutSeconds int64
	HeartbeatState          string
	HeartbeatLastSignalAt   pgtype.Timestamptz
	HeartbeatLostSince      pgtype.Timestamptz
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// LockHeartbeat locks an Integration that is not deleted for a Heartbeat signal or check and reads its Heartbeat. The
// lock is a non-key update lock, so that processing, which reads the name with FOR KEY SHARE, never waits for it.
func (q *Queries) LockHeartbeat(ctx context.Context, arg LockHeartbeatParams) (LockHeartbeatRow, error) {
	row := q.db.QueryRow(ctx, lockHeartbeat, arg.OrgID, arg.ID)
	var i LockHeartbeatRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.StaticLabels,
		&i.Builtin,
		&i.HeartbeatEnabled,
		&i.HeartbeatTimeoutSeconds,
		&i.HeartbeatState,
		&i.HeartbeatLastSignalAt,
		&i.HeartbeatLostSince,
	)
	return i, err
}

const markLost = `-- name: MarkLost :exec
UPDATE integrations
SET heartbeat_state = 'lost', heartbeat_lost_since = $1::timestamptz
WHERE org_id = $2 AND id = $3 AND heartbeat_state = 'live'
`

type MarkLostParams struct {
	LostSince time.Time
	OrgID     int64
	ID        int64
}

// MarkLost makes a live Heartbeat lost since @lost_since, the time of its last signal.
func (q *Queries) MarkLost(ctx context.Context, arg MarkLostParams) error {
	_, err := q.db.Exec(ctx, markLost, arg.LostSince, arg.OrgID, arg.ID)
	return err
}

const recordSignal = `-- name: RecordSignal :exec
UPDATE integrations
SET heartbeat_state = 'live', heartbeat_last_signal_at = $1::timestamptz, heartbeat_lost_since = NULL,
    liveness_clock_ms = liveness_clock_ms + $2::bigint
WHERE org_id = $3 AND id = $4
`

type RecordSignalParams struct {
	SignalAt  time.Time
	AdvanceMs int64
	OrgID     int64
	ID        int64
}

// RecordSignal records a Heartbeat signal: the Heartbeat is live, the time of the last signal is @signal_at and the
// liveness clock advances by @advance_ms. It never touches version: the Heartbeat state is runtime state.
func (q *Queries) RecordSignal(ctx context.Context, arg RecordSignalParams) error {
	_, err := q.db.Exec(ctx, recordSignal,
		arg.SignalAt,
		arg.AdvanceMs,
		arg.OrgID,
		arg.ID,
	)
	return err
}
