{{- /*
SPDX-License-Identifier: AGPL-3.0-only
Copyright The Muster Authors
*/ -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "muster.fullname" . }}-app
  labels:
    {{- include "muster.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  {{- with .Values.service.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: app
      protocol: TCP
      name: app
  selector:
    {{- include "muster.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "muster.fullname" . }}-ingest
  labels:
    {{- include "muster.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
  {{- with .Values.service.ingest.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.ingest.type }}
  ports:
    - port: {{ .Values.service.ingest.port }}
      targetPort: ingest
      protocol: TCP
      name: ingest
  selector:
    {{- include "muster.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "muster.fullname" . }}-internal
  labels:
    {{- include "muster.labels" . | nindent 4 }}
    app.kubernetes.io/component: internal
  {{- with .Values.service.internal.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.internal.type }}
  ports:
    - port: {{ .Values.service.internal.port }}
      targetPort: internal
      protocol: TCP
      name: internal
  selector:
    {{- include "muster.selectorLabels" . | nindent 4 }}
