// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpRouteOrder = `-- name: BumpRouteOrder :one
UPDATE organizations
SET route_order_version = route_order_version + 1
WHERE id = $1
  AND ($2::bigint IS NULL OR route_order_version = $2::bigint)
RETURNING route_order_version
`

type BumpRouteOrderParams struct {
	OrgID    int64
	Expected pgtype.Int8
}

// BumpRouteOrder bumps the version of the Route list, the list ETag, and returns the new one; with @expected it
// returns no row unless the version is still that one. The row lock serializes the changes of the list.
func (q *Queries) BumpRouteOrder(ctx context.Context, arg BumpRouteOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpRouteOrder, arg.OrgID, arg.Expected)
	var route_order_version int64
	err := row.Scan(&route_order_version)
	return route_order_version, err
}

const bumpRoutesOfDestination = `-- name: BumpRoutesOfDestination :many
UPDATE routes r
SET version = r.version + 1, updated_at = $1
FROM (SELECT x.id
      FROM routes x
      WHERE x.org_id = $2 AND x.deleted_at IS NULL
        AND x.id IN (SELECT rd.route_id
                     FROM route_destinations rd
                     WHERE rd.org_id = $2 AND rd.destination_id = $3)
      ORDER BY x.id
      FOR NO KEY UPDATE OF x) AS locked
WHERE r.org_id = $2 AND r.id = locked.id
RETURNING r.id, r.public_id
`

type BumpRoutesOfDestinationParams struct {
	Now           time.Time
	OrgID         int64
	DestinationID int64
}

type BumpRoutesOfDestinationRow struct {
	ID       int64
	PublicID string
}

// BumpRoutesOfDestination gives each Route that is not deleted of a Destination about to leave them a new version,
// locking them in id order, and returns them in that order.
func (q *Queries) BumpRoutesOfDestination(ctx context.Context, arg BumpRoutesOfDestinationParams) ([]BumpRoutesOfDestinationRow, error) {
	rows, err := q.db.Query(ctx, bumpRoutesOfDestination, arg.Now, arg.OrgID, arg.DestinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BumpRoutesOfDestinationRow{}
	for rows.Next() {
		var i BumpRoutesOfDestinationRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenAlertGroups = `-- name: CountOpenAlertGroups :one
SELECT count(*)::bigint
FROM alert_groups
WHERE org_id = $1 AND route_id = $2 AND status <> 'resolved' AND moved_from_route_id IS NULL
`

type CountOpenAlertGroupsParams struct {
	OrgID   int64
	RouteID int64
}

// CountOpenAlertGroups counts the open Alert Groups of a Route, read-only (only groups writes alert_groups); a
// deletion counts them after LockRoute, so that a Snapshot grouping on the Route either committed before or waits.
func (q *Queries) CountOpenAlertGroups(ctx context.Context, arg CountOpenAlertGroupsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenAlertGroups, arg.OrgID, arg.RouteID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteRoute = `-- name: DeleteRoute :exec
UPDATE routes
SET deleted_at = $1, updated_at = $1, version = version + 1
WHERE org_id = $2 AND id = $3 AND NOT is_default
`

type DeleteRouteParams struct {
	Now   pgtype.Timestamptz
	OrgID int64
	ID    int64
}

// DeleteRoute soft-deletes a Route: it leaves every list and the evaluation order at once.
func (q *Queries) DeleteRoute(ctx context.Context, arg DeleteRouteParams) error {
	_, err := q.db.Exec(ctx, deleteRoute, arg.Now, arg.OrgID, arg.ID)
	return err
}

const deleteRouteDestinations = `-- name: DeleteRouteDestinations :exec
DELETE FROM route_destinations
WHERE org_id = $1 AND route_id = $2 AND destination_id = ANY($3::bigint[])
`

type DeleteRouteDestinationsParams struct {
	OrgID          int64
	RouteID        int64
	DestinationIds []int64
}

// DeleteRouteDestinations removes Destinations from a Route.
func (q *Queries) DeleteRouteDestinations(ctx context.Context, arg DeleteRouteDestinationsParams) error {
	_, err := q.db.Exec(ctx, deleteRouteDestinations, arg.OrgID, arg.RouteID, arg.DestinationIds)
	return err
}

const deleteRouteMatchers = `-- name: DeleteRouteMatchers :exec
DELETE FROM route_matchers
WHERE org_id = $1 AND route_id = $2
`

type DeleteRouteMatchersParams struct {
	OrgID   int64
	RouteID int64
}

// DeleteRouteMatchers removes the Matchers of a Route before they are written again.
func (q *Queries) DeleteRouteMatchers(ctx context.Context, arg DeleteRouteMatchersParams) error {
	_, err := q.db.Exec(ctx, deleteRouteMatchers, arg.OrgID, arg.RouteID)
	return err
}

const dismissRouteSuggestion = `-- name: DismissRouteSuggestion :exec
INSERT INTO route_suggestion_dismissals (user_id, suggestion, org_id, dismissed_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, suggestion) DO NOTHING
`

type DismissRouteSuggestionParams struct {
	UserID      int64
	Suggestion  string
	OrgID       int64
	DismissedAt time.Time
}

// DismissRouteSuggestion records that a User dismissed a Route suggestion; a second dismissal changes nothing.
func (q *Queries) DismissRouteSuggestion(ctx context.Context, arg DismissRouteSuggestionParams) error {
	_, err := q.db.Exec(ctx, dismissRouteSuggestion,
		arg.UserID,
		arg.Suggestion,
		arg.OrgID,
		arg.DismissedAt,
	)
	return err
}

const ensureDefaultRoute = `-- name: EnsureDefaultRoute :one
INSERT INTO routes (
    org_id, public_id, name, description, position, is_default, urgent, group_key, reopen_window_seconds,
    grace_period_seconds, urgent_rise_removes_ack, snooze_durations_seconds, thread_batching_window_seconds,
    storm_threshold, language, ack_timeout_enabled, ack_timeout_first_interval_seconds, reminders_enabled,
    reminders_first_interval_seconds, reminders_cap_seconds, auto_unacknowledge, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, 0, true, $5, $6::text[], $7,
    $8, $9, $10::bigint[],
    $11, $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $20
)
ON CONFLICT (org_id) WHERE is_default DO NOTHING
RETURNING public_id
`

type EnsureDefaultRouteParams struct {
	OrgID                          int64
	PublicID                       string
	Name                           string
	Description                    string
	Urgent                         bool
	GroupKey                       []string
	ReopenWindowSeconds            int64
	GracePeriodSeconds             int64
	UrgentRiseRemovesAck           bool
	SnoozeDurationsSeconds         []int64
	ThreadBatchingWindowSeconds    int64
	StormThreshold                 int64
	Language                       string
	AckTimeoutEnabled              bool
	AckTimeoutFirstIntervalSeconds int64
	RemindersEnabled               bool
	RemindersFirstIntervalSeconds  int64
	RemindersCapSeconds            int64
	AutoUnacknowledge              bool
	Now                            time.Time
}

// EnsureDefaultRoute creates the Default route of the Organization when it has none, and returns its public_id only
// when it created it.
func (q *Queries) EnsureDefaultRoute(ctx context.Context, arg EnsureDefaultRouteParams) (string, error) {
	row := q.db.QueryRow(ctx, ensureDefaultRoute,
		arg.OrgID,
		arg.PublicID,
		arg.Name,
		arg.Description,
		arg.Urgent,
		arg.GroupKey,
		arg.ReopenWindowSeconds,
		arg.GracePeriodSeconds,
		arg.UrgentRiseRemovesAck,
		arg.SnoozeDurationsSeconds,
		arg.ThreadBatchingWindowSeconds,
		arg.StormThreshold,
		arg.Language,
		arg.AckTimeoutEnabled,
		arg.AckTimeoutFirstIntervalSeconds,
		arg.RemindersEnabled,
		arg.RemindersFirstIntervalSeconds,
		arg.RemindersCapSeconds,
		arg.AutoUnacknowledge,
		arg.Now,
	)
	var public_id string
	err := row.Scan(&public_id)
	return public_id, err
}

const getRoute = `-- name: GetRoute :one
SELECT r.id, r.public_id, r.name, r.description, r.position, r.is_default, r.urgent, r.group_key,
       r.reopen_window_seconds, r.grace_period_seconds, r.urgent_rise_removes_ack, r.snooze_durations_seconds,
       r.thread_batching_window_seconds, r.storm_threshold, r.language, r.template_root_message, r.template_line,
       r.template_ack_timeout_notice, r.ack_timeout_enabled, r.ack_timeout_first_interval_seconds,
       r.reminders_enabled, r.reminders_first_interval_seconds, r.reminders_cap_seconds, r.auto_unacknowledge,
       r.created_at, r.version,
       (SELECT count(*)
        FROM routes o
        WHERE o.org_id = $1 AND o.deleted_at IS NULL
          AND (o.is_default, o.position, o.id) < (r.is_default, r.position, r.id))::bigint AS place,
       s.started_at AS storm_since, s.alert_group_count AS storm_alert_group_count
FROM routes r
LEFT JOIN storms s ON s.org_id = r.org_id AND s.route_id = r.id AND s.ended_at IS NULL
WHERE r.org_id = $1 AND r.public_id = $2 AND r.deleted_at IS NULL
`

type GetRouteParams struct {
	OrgID    int64
	PublicID string
}

type GetRouteRow struct {
	ID                             int64
	PublicID                       string
	Name                           string
	Description                    string
	Position                       int64
	IsDefault                      bool
	Urgent                         bool
	GroupKey                       []string
	ReopenWindowSeconds            int64
	GracePeriodSeconds             int64
	UrgentRiseRemovesAck           bool
	SnoozeDurationsSeconds         []int64
	ThreadBatchingWindowSeconds    int64
	StormThreshold                 int64
	Language                       string
	TemplateRootMessage            pgtype.Text
	TemplateLine                   pgtype.Text
	TemplateAckTimeoutNotice       pgtype.Text
	AckTimeoutEnabled              bool
	AckTimeoutFirstIntervalSeconds int64
	RemindersEnabled               bool
	RemindersFirstIntervalSeconds  int64
	RemindersCapSeconds            int64
	AutoUnacknowledge              bool
	CreatedAt                      time.Time
	Version                        int64
	Place                          int64
	StormSince                     pgtype.Timestamptz
	StormAlertGroupCount           pgtype.Int8
}

// GetRoute reads a Route that is not deleted with its place in evaluation order, zero-based, and its active Storm.
func (q *Queries) GetRoute(ctx context.Context, arg GetRouteParams) (GetRouteRow, error) {
	row := q.db.QueryRow(ctx, getRoute, arg.OrgID, arg.PublicID)
	var i GetRouteRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Description,
		&i.Position,
		&i.IsDefault,
		&i.Urgent,
		&i.GroupKey,
		&i.ReopenWindowSeconds,
		&i.GracePeriodSeconds,
		&i.UrgentRiseRemovesAck,
		&i.SnoozeDurationsSeconds,
		&i.ThreadBatchingWindowSeconds,
		&i.StormThreshold,
		&i.Language,
		&i.TemplateRootMessage,
		&i.TemplateLine,
		&i.TemplateAckTimeoutNotice,
		&i.AckTimeoutEnabled,
		&i.AckTimeoutFirstIntervalSeconds,
		&i.RemindersEnabled,
		&i.RemindersFirstIntervalSeconds,
		&i.RemindersCapSeconds,
		&i.AutoUnacknowledge,
		&i.CreatedAt,
		&i.Version,
		&i.Place,
		&i.StormSince,
		&i.StormAlertGroupCount,
	)
	return i, err
}

const getRouteOrderVersion = `-- name: GetRouteOrderVersion :one
SELECT route_order_version
FROM organizations
WHERE id = $1
`

// GetRouteOrderVersion reads the version of the Route list.
func (q *Queries) GetRouteOrderVersion(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getRouteOrderVersion, orgID)
	var route_order_version int64
	err := row.Scan(&route_order_version)
	return route_order_version, err
}

const getRoutingStamp = `-- name: GetRoutingStamp :one
SELECT o.route_order_version,
       (SELECT coalesce(sum(r.version), 0)
        FROM routes r
        WHERE r.org_id = $1 AND r.deleted_at IS NULL)::bigint AS route_versions,
       o.severity_label, o.severity_mapping
FROM organizations o
WHERE o.id = $1
`

type GetRoutingStampRow struct {
	RouteOrderVersion int64
	RouteVersions     int64
	SeverityLabel     string
	SeverityMapping   []byte
}

// GetRoutingStamp reads what decides whether the cached evaluation order is current — the version of the Route list,
// which creation, deletion and reordering bump, with the sum of the versions of the Routes, which every edit bumps —
// and the Severity level settings of the Organization.
func (q *Queries) GetRoutingStamp(ctx context.Context, orgID int64) (GetRoutingStampRow, error) {
	row := q.db.QueryRow(ctx, getRoutingStamp, orgID)
	var i GetRoutingStampRow
	err := row.Scan(
		&i.RouteOrderVersion,
		&i.RouteVersions,
		&i.SeverityLabel,
		&i.SeverityMapping,
	)
	return i, err
}

const insertRoute = `-- name: InsertRoute :one
INSERT INTO routes (
    org_id, public_id, name, description, position, is_default, urgent, group_key, reopen_window_seconds,
    grace_period_seconds, urgent_rise_removes_ack, snooze_durations_seconds, thread_batching_window_seconds,
    storm_threshold, language, template_root_message, template_line, template_ack_timeout_notice,
    ack_timeout_enabled, ack_timeout_first_interval_seconds, reminders_enabled, reminders_first_interval_seconds,
    reminders_cap_seconds, auto_unacknowledge, created_at, updated_at
)
SELECT $1, $2, $3, $4,
       coalesce((SELECT CASE WHEN $5::boolean THEN min(p.position) - 1 ELSE max(p.position) + 1 END
                 FROM routes p
                 WHERE p.org_id = $1 AND NOT p.is_default AND p.deleted_at IS NULL), 0),
       false, $6, $7::text[], $8, $9, $10,
       $11::bigint[], $12, $13, $14,
       $15, $16, $17,
       $18, $19, $20,
       $21, $22, $23, $24, $24
RETURNING id
`

type InsertRouteParams struct {
	OrgID                          int64
	PublicID                       string
	Name                           string
	Description                    string
	First                          bool
	Urgent                         bool
	GroupKey                       []string
	ReopenWindowSeconds            int64
	GracePeriodSeconds             int64
	UrgentRiseRemovesAck           bool
	SnoozeDurationsSeconds         []int64
	ThreadBatchingWindowSeconds    int64
	StormThreshold                 int64
	Language                       string
	TemplateRootMessage            pgtype.Text
	TemplateLine                   pgtype.Text
	TemplateAckTimeoutNotice       pgtype.Text
	AckTimeoutEnabled              bool
	AckTimeoutFirstIntervalSeconds int64
	RemindersEnabled               bool
	RemindersFirstIntervalSeconds  int64
	RemindersCapSeconds            int64
	AutoUnacknowledge              bool
	Now                            time.Time
}

// InsertRoute creates a Route at the last position before the Default route, or with @first at the top of the list.
func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRoute,
		arg.OrgID,
		arg.PublicID,
		arg.Name,
		arg.Description,
		arg.First,
		arg.Urgent,
		arg.GroupKey,
		arg.ReopenWindowSeconds,
		arg.GracePeriodSeconds,
		arg.UrgentRiseRemovesAck,
		arg.SnoozeDurationsSeconds,
		arg.ThreadBatchingWindowSeconds,
		arg.StormThreshold,
		arg.Language,
		arg.TemplateRootMessage,
		arg.TemplateLine,
		arg.TemplateAckTimeoutNotice,
		arg.AckTimeoutEnabled,
		arg.AckTimeoutFirstIntervalSeconds,
		arg.RemindersEnabled,
		arg.RemindersFirstIntervalSeconds,
		arg.RemindersCapSeconds,
		arg.AutoUnacknowledge,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRouteDestinations = `-- name: InsertRouteDestinations :exec
INSERT INTO route_destinations (route_id, destination_id, org_id, added_at)
SELECT $1, unnest($2::bigint[]), $3, $4
`

type InsertRouteDestinationsParams struct {
	RouteID        int64
	DestinationIds []int64
	OrgID          int64
	Now            time.Time
}

// InsertRouteDestinations adds Destinations to a Route, added now.
func (q *Queries) InsertRouteDestinations(ctx context.Context, arg InsertRouteDestinationsParams) error {
	_, err := q.db.Exec(ctx, insertRouteDestinations,
		arg.RouteID,
		arg.DestinationIds,
		arg.OrgID,
		arg.Now,
	)
	return err
}

const insertRouteMatcher = `-- name: InsertRouteMatcher :exec
INSERT INTO route_matchers (route_id, org_id, position, label, op, value)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRouteMatcherParams struct {
	RouteID  int64
	OrgID    int64
	Position int64
	Label    string
	Op       string
	Value    string
}

// InsertRouteMatcher writes one Matcher of a Route at its position.
func (q *Queries) InsertRouteMatcher(ctx context.Context, arg InsertRouteMatcherParams) error {
	_, err := q.db.Exec(ctx, insertRouteMatcher,
		arg.RouteID,
		arg.OrgID,
		arg.Position,
		arg.Label,
		arg.Op,
		arg.Value,
	)
	return err
}

const listAlertLabels = `-- name: ListAlertLabels :many
SELECT id, labels
FROM alerts
WHERE org_id = $1
  AND (id = ANY($2::bigint[])
       OR (id = ANY($3::bigint[]) AND status = 'firing' AND route_id IS NULL))
`

type ListAlertLabelsParams struct {
	OrgID     int64
	Ids       []int64
	ListedIds []int64
}

type ListAlertLabelsRow struct {
	ID     int64
	Labels []byte
}

// ListAlertLabels reads the labels of Alerts, with their Static labels applied: the Alerts ids, and the Alerts
// listed_ids that fire without a Route.
func (q *Queries) ListAlertLabels(ctx context.Context, arg ListAlertLabelsParams) ([]ListAlertLabelsRow, error) {
	rows, err := q.db.Query(ctx, listAlertLabels, arg.OrgID, arg.Ids, arg.ListedIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertLabelsRow{}
	for rows.Next() {
		var i ListAlertLabelsRow
		if err := rows.Scan(&i.ID, &i.Labels); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeatIntegrations = `-- name: ListHeartbeatIntegrations :many
SELECT public_id, name, static_labels
FROM integrations
WHERE org_id = $1 AND deleted_at IS NULL AND heartbeat_enabled
ORDER BY id
`

type ListHeartbeatIntegrationsRow struct {
	PublicID     string
	Name         string
	StaticLabels []byte
}

// ListHeartbeatIntegrations lists the Integrations that are not deleted and have their Heartbeat on, with what
// MusterHeartbeatLost carries of them: the public_id, the name and the Static labels.
func (q *Queries) ListHeartbeatIntegrations(ctx context.Context, orgID int64) ([]ListHeartbeatIntegrationsRow, error) {
	rows, err := q.db.Query(ctx, listHeartbeatIntegrations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHeartbeatIntegrationsRow{}
	for rows.Next() {
		var i ListHeartbeatIntegrationsRow
		if err := rows.Scan(&i.PublicID, &i.Name, &i.StaticLabels); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAlertGroupCounts = `-- name: ListOpenAlertGroupCounts :many
SELECT route_id, count(*)::bigint AS count
FROM alert_groups
WHERE org_id = $1 AND status <> 'resolved' AND moved_from_route_id IS NULL
GROUP BY route_id
`

type ListOpenAlertGroupCountsRow struct {
	RouteID int64
	Count   int64
}

// ListOpenAlertGroupCounts counts the open Alert Groups of each Route that has any (Route.open_alert_group_count).
func (q *Queries) ListOpenAlertGroupCounts(ctx context.Context, orgID int64) ([]ListOpenAlertGroupCountsRow, error) {
	rows, err := q.db.Query(ctx, listOpenAlertGroupCounts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenAlertGroupCountsRow{}
	for rows.Next() {
		var i ListOpenAlertGroupCountsRow
		if err := rows.Scan(&i.RouteID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteDestinationIDs = `-- name: ListRouteDestinationIDs :many
SELECT rd.route_id, rd.destination_id, d.public_id
FROM route_destinations rd
JOIN destinations d ON d.org_id = rd.org_id AND d.id = rd.destination_id
WHERE rd.org_id = $1 AND rd.route_id = ANY($2::bigint[]) AND d.deleted_at IS NULL
ORDER BY rd.route_id, d.public_id
`

type ListRouteDestinationIDsParams struct {
	OrgID    int64
	RouteIds []int64
}

type ListRouteDestinationIDsRow struct {
	RouteID       int64
	DestinationID int64
	PublicID      string
}

// ListRouteDestinationIDs lists the Destinations that are not deleted of the Routes, by public_id.
func (q *Queries) ListRouteDestinationIDs(ctx context.Context, arg ListRouteDestinationIDsParams) ([]ListRouteDestinationIDsRow, error) {
	rows, err := q.db.Query(ctx, listRouteDestinationIDs, arg.OrgID, arg.RouteIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRouteDestinationIDsRow{}
	for rows.Next() {
		var i ListRouteDestinationIDsRow
		if err := rows.Scan(&i.RouteID, &i.DestinationID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteInfo = `-- name: ListRouteInfo :many
SELECT public_id, name
FROM routes
WHERE org_id = $1 AND deleted_at IS NULL
`

type ListRouteInfoRow struct {
	PublicID string
	Name     string
}

// ListRouteInfo lists the Routes that are not deleted for muster_route_info.
func (q *Queries) ListRouteInfo(ctx context.Context, orgID int64) ([]ListRouteInfoRow, error) {
	rows, err := q.db.Query(ctx, listRouteInfo, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRouteInfoRow{}
	for rows.Next() {
		var i ListRouteInfoRow
		if err := rows.Scan(&i.PublicID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteMatchers = `-- name: ListRouteMatchers :many
SELECT route_id, label, op, value
FROM route_matchers
WHERE org_id = $1 AND route_id = ANY($2::bigint[])
ORDER BY route_id, position
`

type ListRouteMatchersParams struct {
	OrgID    int64
	RouteIds []int64
}

type ListRouteMatchersRow struct {
	RouteID int64
	Label   string
	Op      string
	Value   string
}

// ListRouteMatchers lists the Matchers of the Routes, in their order.
func (q *Queries) ListRouteMatchers(ctx context.Context, arg ListRouteMatchersParams) ([]ListRouteMatchersRow, error) {
	rows, err := q.db.Query(ctx, listRouteMatchers, arg.OrgID, arg.RouteIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRouteMatchersRow{}
	for rows.Next() {
		var i ListRouteMatchersRow
		if err := rows.Scan(
			&i.RouteID,
			&i.Label,
			&i.Op,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteSuggestionDismissals = `-- name: ListRouteSuggestionDismissals :many
SELECT suggestion
FROM route_suggestion_dismissals
WHERE org_id = $1 AND user_id = $2
`

type ListRouteSuggestionDismissalsParams struct {
	OrgID  int64
	UserID int64
}

// ListRouteSuggestionDismissals lists the Route suggestions a User dismissed.
func (q *Queries) ListRouteSuggestionDismissals(ctx context.Context, arg ListRouteSuggestionDismissalsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRouteSuggestionDismissals, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var suggestion string
		if err := rows.Scan(&suggestion); err != nil {
			return nil, err
		}
		items = append(items, suggestion)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many

SELECT r.id, r.public_id, r.name, r.description, r.position, r.is_default, r.urgent, r.group_key,
       r.reopen_window_seconds, r.grace_period_seconds, r.urgent_rise_removes_ack, r.snooze_durations_seconds,
       r.thread_batching_window_seconds, r.storm_threshold, r.language, r.template_root_message, r.template_line,
       r.template_ack_timeout_notice, r.ack_timeout_enabled, r.ack_timeout_first_interval_seconds,
       r.reminders_enabled, r.reminders_first_interval_seconds, r.reminders_cap_seconds, r.auto_unacknowledge,
       r.created_at, r.version, s.started_at AS storm_since, s.alert_group_count AS storm_alert_group_count
FROM routes r
LEFT JOIN storms s ON s.org_id = r.org_id AND s.route_id = r.id AND s.ended_at IS NULL
WHERE r.org_id = $1 AND r.deleted_at IS NULL
ORDER BY r.is_default, r.position, r.id
`

type ListRoutesRow struct {
	ID                             int64
	PublicID                       string
	Name                           string
	Description                    string
	Position                       int64
	IsDefault                      bool
	Urgent                         bool
	GroupKey                       []string
	ReopenWindowSeconds            int64
	GracePeriodSeconds             int64
	UrgentRiseRemovesAck           bool
	SnoozeDurationsSeconds         []int64
	ThreadBatchingWindowSeconds    int64
	StormThreshold                 int64
	Language                       string
	TemplateRootMessage            pgtype.Text
	TemplateLine                   pgtype.Text
	TemplateAckTimeoutNotice       pgtype.Text
	AckTimeoutEnabled              bool
	AckTimeoutFirstIntervalSeconds int64
	RemindersEnabled               bool
	RemindersFirstIntervalSeconds  int64
	RemindersCapSeconds            int64
	AutoUnacknowledge              bool
	CreatedAt                      time.Time
	Version                        int64
	StormSince                     pgtype.Timestamptz
	StormAlertGroupCount           pgtype.Int8
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// ListRoutes lists the Routes that are not deleted in evaluation order, the Default route last, with their active
// Storm.
func (q *Queries) ListRoutes(ctx context.Context, orgID int64) ([]ListRoutesRow, error) {
	rows, err := q.db.Query(ctx, listRoutes, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoutesRow{}
	for rows.Next() {
		var i ListRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Description,
			&i.Position,
			&i.IsDefault,
			&i.Urgent,
			&i.GroupKey,
			&i.ReopenWindowSeconds,
			&i.GracePeriodSeconds,
			&i.UrgentRiseRemovesAck,
			&i.SnoozeDurationsSeconds,
			&i.ThreadBatchingWindowSeconds,
			&i.StormThreshold,
			&i.Language,
			&i.TemplateRootMessage,
			&i.TemplateLine,
			&i.TemplateAckTimeoutNotice,
			&i.AckTimeoutEnabled,
			&i.AckTimeoutFirstIntervalSeconds,
			&i.RemindersEnabled,
			&i.RemindersFirstIntervalSeconds,
			&i.RemindersCapSeconds,
			&i.AutoUnacknowledge,
			&i.CreatedAt,
			&i.Version,
			&i.StormSince,
			&i.StormAlertGroupCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoute = `-- name: LockRoute :one
SELECT id
FROM routes
WHERE org_id = $1 AND public_id = $2 AND deleted_at IS NULL
FOR NO KEY UPDATE
`

type LockRouteParams struct {
	OrgID    int64
	PublicID string
}

// LockRoute locks a Route that is not deleted for a change; the lock leaves the key alone, so that routing, whose
// foreign key check on alerts.route_id takes a key share lock, never waits for it.
func (q *Queries) LockRoute(ctx context.Context, arg LockRouteParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockRoute, arg.OrgID, arg.PublicID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockRouteMembership = `-- name: LockRouteMembership :exec
SELECT pg_advisory_xact_lock($1::int, hashint8($2::bigint))
`

type LockRouteMembershipParams struct {
	LockClass int32
	RouteID   int64
}

// LockRouteMembership takes, until the transaction ends, the membership lock of a Route exclusively before its
// Destinations change: delivery's Enqueue takes it shared (ShareRouteMembership, class db.RouteMembershipLockClass),
// so that a change of the Destinations and an Enqueue on the Route serialize.
func (q *Queries) LockRouteMembership(ctx context.Context, arg LockRouteMembershipParams) error {
	_, err := q.db.Exec(ctx, lockRouteMembership, arg.LockClass, arg.RouteID)
	return err
}

const resolveDestinations = `-- name: ResolveDestinations :many
SELECT id, public_id
FROM destinations
WHERE org_id = $1 AND public_id = ANY($2::text[]) AND deleted_at IS NULL
`

type ResolveDestinationsParams struct {
	OrgID     int64
	PublicIds []string
}

type ResolveDestinationsRow struct {
	ID       int64
	PublicID string
}

// ResolveDestinations reads the Destinations that are not deleted among the public_ids, for the Destinations of a
// Route.
func (q *Queries) ResolveDestinations(ctx context.Context, arg ResolveDestinationsParams) ([]ResolveDestinationsRow, error) {
	rows, err := q.db.Query(ctx, resolveDestinations, arg.OrgID, arg.PublicIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveDestinationsRow{}
	for rows.Next() {
		var i ResolveDestinationsRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restampAlertRoutes = `-- name: RestampAlertRoutes :exec
UPDATE alerts
SET route_id = $1
WHERE org_id = $2 AND id = ANY($3::bigint[])
`

type RestampAlertRoutesParams struct {
	RouteID pgtype.Int8
	OrgID   int64
	Ids     []int64
}

// RestampAlertRoutes records another Route for the current firing of Alerts: the Default route, for Alerts whose Route
// was deleted while their Snapshot waited for it.
func (q *Queries) RestampAlertRoutes(ctx context.Context, arg RestampAlertRoutesParams) error {
	_, err := q.db.Exec(ctx, restampAlertRoutes, arg.RouteID, arg.OrgID, arg.Ids)
	return err
}

const setAlertRoutes = `-- name: SetAlertRoutes :exec
UPDATE alerts a
SET route_id = nullif(r.route_id, 0), severity_level = r.severity_level, severity_raw = nullif(r.severity_raw, '')
FROM (SELECT unnest($2::bigint[]) AS id, unnest($3::bigint[]) AS route_id,
             unnest($4::text[]) AS severity_level, unnest($5::text[]) AS severity_raw) AS r
WHERE a.org_id = $1 AND a.id = r.id
`

type SetAlertRoutesParams struct {
	OrgID          int64
	Ids            []int64
	RouteIds       []int64
	SeverityLevels []string
	SeverityRaws   []string
}

// SetAlertRoutes records the Route and the Severity level of the current firing of each Alert; a route id of 0 and
// an empty raw value are null.
func (q *Queries) SetAlertRoutes(ctx context.Context, arg SetAlertRoutesParams) error {
	_, err := q.db.Exec(ctx, setAlertRoutes,
		arg.OrgID,
		arg.Ids,
		arg.RouteIds,
		arg.SeverityLevels,
		arg.SeverityRaws,
	)
	return err
}

const setRoutePositions = `-- name: SetRoutePositions :exec
UPDATE routes r
SET position = p.position
FROM (SELECT unnest($2::bigint[]) AS id, unnest($3::bigint[]) AS position) AS p
WHERE r.org_id = $1 AND r.id = p.id
`

type SetRoutePositionsParams struct {
	OrgID     int64
	Ids       []int64
	Positions []int64
}

// SetRoutePositions rewrites the positions of the Routes.
func (q *Queries) SetRoutePositions(ctx context.Context, arg SetRoutePositionsParams) error {
	_, err := q.db.Exec(ctx, setRoutePositions, arg.OrgID, arg.Ids, arg.Positions)
	return err
}

const updateRoute = `-- name: UpdateRoute :exec
UPDATE routes
SET name = $1, description = $2, urgent = $3, group_key = $4::text[],
    reopen_window_seconds = $5, grace_period_seconds = $6,
    urgent_rise_removes_ack = $7, snooze_durations_seconds = $8::bigint[],
    thread_batching_window_seconds = $9, storm_threshold = $10,
    language = $11, template_root_message = $12,
    template_line = $13, template_ack_timeout_notice = $14,
    ack_timeout_enabled = $15, ack_timeout_first_interval_seconds = $16,
    reminders_enabled = $17, reminders_first_interval_seconds = $18,
    reminders_cap_seconds = $19, auto_unacknowledge = $20, updated_at = $21,
    version = version + 1
WHERE org_id = $22 AND id = $23
`

type UpdateRouteParams struct {
	Name                           string
	Description                    string
	Urgent                         bool
	GroupKey                       []string
	ReopenWindowSeconds            int64
	GracePeriodSeconds             int64
	UrgentRiseRemovesAck           bool
	SnoozeDurationsSeconds         []int64
	ThreadBatchingWindowSeconds    int64
	StormThreshold                 int64
	Language                       string
	TemplateRootMessage            pgtype.Text
	TemplateLine                   pgtype.Text
	TemplateAckTimeoutNotice       pgtype.Text
	AckTimeoutEnabled              bool
	AckTimeoutFirstIntervalSeconds int64
	RemindersEnabled               bool
	RemindersFirstIntervalSeconds  int64
	RemindersCapSeconds            int64
	AutoUnacknowledge              bool
	Now                            time.Time
	OrgID                          int64
	ID                             int64
}

// UpdateRoute replaces the configured fields of a Route and bumps its version.
func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) error {
	_, err := q.db.Exec(ctx, updateRoute,
		arg.Name,
		arg.Description,
		arg.Urgent,
		arg.GroupKey,
		arg.ReopenWindowSeconds,
		arg.GracePeriodSeconds,
		arg.UrgentRiseRemovesAck,
		arg.SnoozeDurationsSeconds,
		arg.ThreadBatchingWindowSeconds,
		arg.StormThreshold,
		arg.Language,
		arg.TemplateRootMessage,
		arg.TemplateLine,
		arg.TemplateAckTimeoutNotice,
		arg.AckTimeoutEnabled,
		arg.AckTimeoutFirstIntervalSeconds,
		arg.RemindersEnabled,
		arg.RemindersFirstIntervalSeconds,
		arg.RemindersCapSeconds,
		arg.AutoUnacknowledge,
		arg.Now,
		arg.OrgID,
		arg.ID,
	)
	return err
}
