// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors

package main

import (
	"maps"
	"slices"
	"strings"
	"testing"
	"testing/fstest"
)

const goodHeader = "// SPDX-License-Identifier: AGPL-3.0-only\n// Copyright The Muster Authors\n\n"

func TestCheck(t *testing.T) {
	fsys := fstest.MapFS{
		"cmd/muster/main.go":                           {Data: []byte(goodHeader + "package main\n")},
		"internal/cli/nospdx.go":                       {Data: []byte("// Copyright The Muster Authors\n\npackage cli\n")},
		"internal/cli/nocopyright.go":                  {Data: []byte("// SPDX-License-Identifier: AGPL-3.0-only\n\npackage cli\n")},
		"internal/cli/none.go":                         {Data: []byte("package cli\n")},
		"internal/cli/late.go":                         {Data: []byte("package cli\n\n\n\n\n" + goodHeader)},
		"scripts/run.sh":                               {Data: []byte("#!/bin/sh\n# SPDX-License-Identifier: AGPL-3.0-only\n# Copyright The Muster Authors\n")},
		"scripts/noheader.sh":                          {Data: []byte("#!/bin/sh\necho hi\n")},
		"Makefile":                                     {Data: []byte("# SPDX-License-Identifier: AGPL-3.0-only\r\n# Copyright The Muster Authors\r\n")},
		"deploy/dev/Dockerfile":                        {Data: []byte("FROM scratch\n")},
		"db/0001.up.sql":                               {Data: []byte("-- SPDX-License-Identifier: AGPL-3.0-only\n-- Copyright The Muster Authors\n")},
		"internal/x/dbgen/models.go":                   {Data: []byte("// Code generated by sqlc. DO NOT EDIT.\n\npackage dbgen\n")},
		"internal/x/gen.sql":                           {Data: []byte("-- Code generated by hand-rolled tool. DO NOT EDIT.\nSELECT 1;\n")},
		"internal/archlint/testdata/a.go":              {Data: []byte("package a\n")},
		"web/src/components/ui/button.tsx":             {Data: []byte("// SPDX-License-Identifier: MIT\n")},
		"web/src/main.tsx":                             {Data: []byte("export {}\n")},
		"deploy/helm/muster/templates/deployment.yaml": {Data: []byte("kind: Deployment\n")},
		".github/workflows/ci.yml":                     {Data: []byte("name: ci\n")},
		".github/ISSUE_TEMPLATE/bug.yml":               {Data: []byte("name: Bug\n")},
		"README.md":                                    {Data: []byte("# Muster\n")},
		"api/openapi.yaml":                             {Data: []byte("openapi: 3.1.0\n")},
	}
	files := append(slices.Collect(maps.Keys(fsys)), "internal/deleted.go")

	got, err := check(fsys, files, []string{"web/src/components/ui/**"})
	if err != nil {
		t.Fatalf("check: %v", err)
	}
	want := []string{
		`.github/workflows/ci.yml: missing "SPDX-License-Identifier: AGPL-3.0-only"`,
		`.github/workflows/ci.yml: missing "Copyright The Muster Authors"`,
		`deploy/dev/Dockerfile: missing "SPDX-License-Identifier: AGPL-3.0-only"`,
		`deploy/dev/Dockerfile: missing "Copyright The Muster Authors"`,
		`deploy/helm/muster/templates/deployment.yaml: missing "SPDX-License-Identifier: AGPL-3.0-only"`,
		`deploy/helm/muster/templates/deployment.yaml: missing "Copyright The Muster Authors"`,
		`internal/cli/late.go: missing "SPDX-License-Identifier: AGPL-3.0-only"`,
		`internal/cli/late.go: missing "Copyright The Muster Authors"`,
		`internal/cli/nocopyright.go: missing "Copyright The Muster Authors"`,
		`internal/cli/none.go: missing "SPDX-License-Identifier: AGPL-3.0-only"`,
		`internal/cli/none.go: missing "Copyright The Muster Authors"`,
		`internal/cli/nospdx.go: missing "SPDX-License-Identifier: AGPL-3.0-only"`,
		`scripts/noheader.sh: missing "SPDX-License-Identifier: AGPL-3.0-only"`,
		`scripts/noheader.sh: missing "Copyright The Muster Authors"`,
		`web/src/main.tsx: missing "SPDX-License-Identifier: AGPL-3.0-only"`,
		`web/src/main.tsx: missing "Copyright The Muster Authors"`,
	}
	if !slices.Equal(got, want) {
		t.Errorf("problems:\n%s\nwant:\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
}

func TestParseExclusions(t *testing.T) {
	tests := []struct {
		name    string
		notice  string
		want    []string
		wantErr string
	}{
		{
			name:   "none",
			notice: "Muster\n\n" + noticeHeading + "\n  (none)\n\nThe list above is read by make lint.\n- not/an/entry/**\n",
			want:   []string{},
		},
		{
			name: "entries with descriptions",
			notice: noticeHeading + "\r\n  - web/src/components/ui/**  shadcn/ui, MIT\r\n" +
				"  - internal/x/port.go   KeepHQ, MIT\r\n",
			want: []string{"web/src/components/ui/**", "internal/x/port.go"},
		},
		{name: "missing heading", notice: "Muster\n", wantErr: "not found"},
		{name: "bad entry", notice: noticeHeading + "\n  web/**\n", wantErr: `line 2: want "- <glob>"`},
		{name: "inner double star", notice: noticeHeading + "\n  - web/**/ui/**\n", wantErr: `only as a trailing "/**"`},
		{name: "bad pattern", notice: noticeHeading + "\n  - web/[ui\n", wantErr: "syntax error in pattern"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parseExclusions(tt.notice)
			if tt.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("err = %v, want it to contain %q", err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("parseExclusions: %v", err)
			}
			if !slices.Equal(got, tt.want) {
				t.Errorf("globs = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestMatchGlob(t *testing.T) {
	tests := []struct {
		glob, name string
		want       bool
	}{
		{"web/src/components/ui/**", "web/src/components/ui/button.tsx", true},
		{"web/src/components/ui/**", "web/src/components/ui/forms/input.tsx", true},
		{"web/src/components/ui/**", "web/src/components/ui", false},
		{"web/src/components/ui/**", "web/src/components/uix/button.tsx", false},
		{"deploy/helm/*/templates/**", "deploy/helm/muster/templates/_helpers.tpl", true},
		{"deploy/helm/*/templates/**", "deploy/helm/muster/values.yaml", false},
		{"internal/*/vendored.go", "internal/x/vendored.go", true},
		{"internal/*/vendored.go", "internal/x/y/vendored.go", false},
		{".github/workflows/*.yml", ".github/workflows/ci.yml", true},
	}
	for _, tt := range tests {
		if got := matchGlob(tt.glob, tt.name); got != tt.want {
			t.Errorf("matchGlob(%q, %q) = %v, want %v", tt.glob, tt.name, got, tt.want)
		}
	}
}
