// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureRuntimeState = `-- name: EnsureRuntimeState :exec


INSERT INTO runtime_state (updated_at)
VALUES ($1)
ON CONFLICT (singleton) DO NOTHING
`

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// The installation-level platform state of the Leader: runtime_state, downtime_periods and the replica records have
// no org_id. Times are business times, except the replica records, which are on the real clock.
// EnsureRuntimeState writes the singleton row on a new database; it changes nothing when the row exists.
func (q *Queries) EnsureRuntimeState(ctx context.Context, updatedAt time.Time) error {
	_, err := q.db.Exec(ctx, ensureRuntimeState, updatedAt)
	return err
}

const getRuntimeState = `-- name: GetRuntimeState :one
SELECT leader_replica_id, leader_since, alive_at, recovery_until
FROM runtime_state
`

type GetRuntimeStateRow struct {
	LeaderReplicaID pgtype.Text
	LeaderSince     pgtype.Timestamptz
	AliveAt         pgtype.Timestamptz
	RecoveryUntil   pgtype.Timestamptz
}

func (q *Queries) GetRuntimeState(ctx context.Context) (GetRuntimeStateRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeState)
	var i GetRuntimeStateRow
	err := row.Scan(
		&i.LeaderReplicaID,
		&i.LeaderSince,
		&i.AliveAt,
		&i.RecoveryUntil,
	)
	return i, err
}

const latestDowntimeEnd = `-- name: LatestDowntimeEnd :one
SELECT ended_at
FROM downtime_periods
ORDER BY ended_at DESC
LIMIT 1
`

func (q *Queries) LatestDowntimeEnd(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestDowntimeEnd)
	var ended_at time.Time
	err := row.Scan(&ended_at)
	return ended_at, err
}

const latestOtherReplicaRefresh = `-- name: LatestOtherReplicaRefresh :one
SELECT refreshed_at
FROM replicas
WHERE replica_id <> $1
  AND started_at <= $2
ORDER BY refreshed_at DESC
LIMIT 1
`

type LatestOtherReplicaRefreshParams struct {
	ReplicaID     string
	StartedBefore time.Time
}

// LatestOtherReplicaRefresh is the newest key-record refresh of any replica but the given one that started before
// started_before, on the real clock: a replica that started later did not run across the gap.
func (q *Queries) LatestOtherReplicaRefresh(ctx context.Context, arg LatestOtherReplicaRefreshParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestOtherReplicaRefresh, arg.ReplicaID, arg.StartedBefore)
	var refreshed_at time.Time
	err := row.Scan(&refreshed_at)
	return refreshed_at, err
}

const listOrganizationIDs = `-- name: ListOrganizationIDs :many
SELECT id
FROM organizations
ORDER BY id
`

func (q *Queries) ListOrganizationIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOrganizationIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRuntimeState = `-- name: LockRuntimeState :one
SELECT leader_replica_id, leader_since, alive_at, recovery_until
FROM runtime_state
FOR UPDATE
`

type LockRuntimeStateRow struct {
	LeaderReplicaID pgtype.Text
	LeaderSince     pgtype.Timestamptz
	AliveAt         pgtype.Timestamptz
	RecoveryUntil   pgtype.Timestamptz
}

// LockRuntimeState reads the row and locks it until the transaction ends, so that two Leaders taking over at once
// record one downtime.
func (q *Queries) LockRuntimeState(ctx context.Context) (LockRuntimeStateRow, error) {
	row := q.db.QueryRow(ctx, lockRuntimeState)
	var i LockRuntimeStateRow
	err := row.Scan(
		&i.LeaderReplicaID,
		&i.LeaderSince,
		&i.AliveAt,
		&i.RecoveryUntil,
	)
	return i, err
}

const longestLearnedRepeatInterval = `-- name: LongestLearnedRepeatInterval :one
SELECT COALESCE(max(learned_repeat_interval_ms), 0)::bigint AS longest_ms
FROM alertmanager_routes
WHERE org_id = $1
`

// LongestLearnedRepeatInterval is the longest repeat interval learned from the Organization's Alertmanager routes,
// in milliseconds; 0 when none is learned.
func (q *Queries) LongestLearnedRepeatInterval(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, longestLearnedRepeatInterval, orgID)
	var longest_ms int64
	err := row.Scan(&longest_ms)
	return longest_ms, err
}

const markAlive = `-- name: MarkAlive :execrows
UPDATE runtime_state
SET leader_since      = CASE WHEN leader_replica_id IS DISTINCT FROM $1::text THEN $2 ELSE leader_since END,
    leader_replica_id = $1::text,
    alive_at          = GREATEST(alive_at, $2),
    updated_at        = $2
`

type MarkAliveParams struct {
	LeaderReplicaID string
	Now             time.Time
}

// MarkAlive refreshes the alive mark; a Leader that finds another replica's id in the row writes its own.
func (q *Queries) MarkAlive(ctx context.Context, arg MarkAliveParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAlive, arg.LeaderReplicaID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDowntime = `-- name: RecordDowntime :exec
INSERT INTO downtime_periods (started_at, ended_at, recorded_at)
VALUES ($1, $2, $3)
`

type RecordDowntimeParams struct {
	StartedAt  time.Time
	EndedAt    time.Time
	RecordedAt time.Time
}

func (q *Queries) RecordDowntime(ctx context.Context, arg RecordDowntimeParams) error {
	_, err := q.db.Exec(ctx, recordDowntime, arg.StartedAt, arg.EndedAt, arg.RecordedAt)
	return err
}

const takeOver = `-- name: TakeOver :exec
UPDATE runtime_state
SET leader_replica_id = $1::text,
    leader_since      = $2::timestamptz,
    alive_at          = GREATEST(alive_at, $2::timestamptz),
    recovery_until    = COALESCE($3::timestamptz, recovery_until),
    updated_at        = $2::timestamptz
`

type TakeOverParams struct {
	LeaderReplicaID string
	Now             time.Time
	RecoveryUntil   pgtype.Timestamptz
}

// TakeOver records a new Leader; a null recovery_until keeps the recovery window that is open, if any.
func (q *Queries) TakeOver(ctx context.Context, arg TakeOverParams) error {
	_, err := q.db.Exec(ctx, takeOver, arg.LeaderReplicaID, arg.Now, arg.RecoveryUntil)
	return err
}
