// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateSeed = `-- name: ActivateSeed :execrows
UPDATE user_totp
SET seed_ciphertext = $1, seed_key_id = $2::text, seed_updated_at = $3::timestamptz,
    enrolled_at = $3::timestamptz,
    pending_seed_ciphertext = NULL, pending_seed_key_id = NULL, pending_seed_updated_at = NULL,
    last_used_step = $4::bigint
WHERE org_id = $5 AND user_id = $6 AND seed_ciphertext IS NULL
  AND pending_seed_ciphertext = $7
`

type ActivateSeedParams struct {
	Ciphertext        []byte
	KeyID             string
	Now               time.Time
	Step              int64
	OrgID             int64
	UserID            int64
	PendingCiphertext []byte
}

// ActivateSeed confirms an enrolment: the pending seed that was checked, written again as the seed, becomes the
// user's TOTP, and the step of the confirming code is used. No row changes when the pending seed was replaced or
// TOTP is enrolled meanwhile.
func (q *Queries) ActivateSeed(ctx context.Context, arg ActivateSeedParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateSeed,
		arg.Ciphertext,
		arg.KeyID,
		arg.Now,
		arg.Step,
		arg.OrgID,
		arg.UserID,
		arg.PendingCiphertext,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const activateSession = `-- name: ActivateSession :execrows
UPDATE sessions
SET state = 'active'
WHERE org_id = $1 AND id = $2 AND state = 'totp_enrolment_required' AND ended_at IS NULL
`

type ActivateSessionParams struct {
	OrgID int64
	ID    int64
}

// ActivateSession makes a session that waited for the enrolment active, once the enrolment is confirmed.
func (q *Queries) ActivateSession(ctx context.Context, arg ActivateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateSession, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT count(*)
FROM user_recovery_codes
WHERE org_id = $1 AND user_id = $2 AND used_at IS NULL
`

type CountUnusedRecoveryCodesParams struct {
	OrgID  int64
	UserID int64
}

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, arg CountUnusedRecoveryCodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedRecoveryCodes, arg.OrgID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :execrows
DELETE FROM user_recovery_codes
WHERE org_id = $1 AND user_id = $2
`

type DeleteRecoveryCodesParams struct {
	OrgID  int64
	UserID int64
}

// DeleteRecoveryCodes removes every code of a user, with the TOTP they belong to.
func (q *Queries) DeleteRecoveryCodes(ctx context.Context, arg DeleteRecoveryCodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecoveryCodes, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTOTP = `-- name: DeleteTOTP :execrows
DELETE FROM user_totp
WHERE org_id = $1 AND user_id = $2
`

type DeleteTOTPParams struct {
	OrgID  int64
	UserID int64
}

func (q *Queries) DeleteTOTP(ctx context.Context, arg DeleteTOTPParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTOTP, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUnusedRecoveryCodes = `-- name: DeleteUnusedRecoveryCodes :execrows
DELETE FROM user_recovery_codes
WHERE org_id = $1 AND user_id = $2 AND used_at IS NULL
`

type DeleteUnusedRecoveryCodesParams struct {
	OrgID  int64
	UserID int64
}

// DeleteUnusedRecoveryCodes removes the codes not used yet, before new ones are issued.
func (q *Queries) DeleteUnusedRecoveryCodes(ctx context.Context, arg DeleteUnusedRecoveryCodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnusedRecoveryCodes, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endSessionsOfUser = `-- name: EndSessionsOfUser :execrows
UPDATE sessions
SET ended_at = $1::timestamptz, end_reason = 'totp_reset'
WHERE org_id = $2 AND user_id = $3 AND ended_at IS NULL
`

type EndSessionsOfUserParams struct {
	Now    time.Time
	OrgID  int64
	UserID int64
}

// EndSessionsOfUser ends every session of a user whose TOTP an Admin reset.
func (q *Queries) EndSessionsOfUser(ctx context.Context, arg EndSessionsOfUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, endSessionsOfUser, arg.Now, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTOTP = `-- name: GetTOTP :one
SELECT seed_ciphertext, seed_key_id, pending_seed_ciphertext, pending_seed_key_id, enrolled_at, last_used_step
FROM user_totp
WHERE org_id = $1 AND user_id = $2
`

type GetTOTPParams struct {
	OrgID  int64
	UserID int64
}

type GetTOTPRow struct {
	SeedCiphertext        []byte
	SeedKeyID             pgtype.Text
	PendingSeedCiphertext []byte
	PendingSeedKeyID      pgtype.Text
	EnrolledAt            pgtype.Timestamptz
	LastUsedStep          pgtype.Int8
}

func (q *Queries) GetTOTP(ctx context.Context, arg GetTOTPParams) (GetTOTPRow, error) {
	row := q.db.QueryRow(ctx, getTOTP, arg.OrgID, arg.UserID)
	var i GetTOTPRow
	err := row.Scan(
		&i.SeedCiphertext,
		&i.SeedKeyID,
		&i.PendingSeedCiphertext,
		&i.PendingSeedKeyID,
		&i.EnrolledAt,
		&i.LastUsedStep,
	)
	return i, err
}

const getTOTPUser = `-- name: GetTOTPUser :one

SELECT id, public_id, login, name, status
FROM users
WHERE org_id = $1 AND id = $2
`

type GetTOTPUserParams struct {
	OrgID int64
	ID    int64
}

type GetTOTPUserRow struct {
	ID       int64
	PublicID string
	Login    string
	Name     string
	Status   string
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// GetTOTPUser reads what TOTP needs of a user: the login names the account in the authenticator app.
func (q *Queries) GetTOTPUser(ctx context.Context, arg GetTOTPUserParams) (GetTOTPUserRow, error) {
	row := q.db.QueryRow(ctx, getTOTPUser, arg.OrgID, arg.ID)
	var i GetTOTPUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Login,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getTOTPUserByLogin = `-- name: GetTOTPUserByLogin :one
SELECT id, public_id, login, name, status
FROM users
WHERE org_id = $1 AND lower(login) = lower($2)
`

type GetTOTPUserByLoginParams struct {
	OrgID int64
	Login string
}

type GetTOTPUserByLoginRow struct {
	ID       int64
	PublicID string
	Login    string
	Name     string
	Status   string
}

// GetTOTPUserByLogin finds an account by its login, compared lowercased.
func (q *Queries) GetTOTPUserByLogin(ctx context.Context, arg GetTOTPUserByLoginParams) (GetTOTPUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getTOTPUserByLogin, arg.OrgID, arg.Login)
	var i GetTOTPUserByLoginRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Login,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getTOTPUserByPublicID = `-- name: GetTOTPUserByPublicID :one
SELECT id, public_id, login, name, status
FROM users
WHERE org_id = $1 AND public_id = $2
`

type GetTOTPUserByPublicIDParams struct {
	OrgID    int64
	PublicID string
}

type GetTOTPUserByPublicIDRow struct {
	ID       int64
	PublicID string
	Login    string
	Name     string
	Status   string
}

func (q *Queries) GetTOTPUserByPublicID(ctx context.Context, arg GetTOTPUserByPublicIDParams) (GetTOTPUserByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getTOTPUserByPublicID, arg.OrgID, arg.PublicID)
	var i GetTOTPUserByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Login,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO user_recovery_codes (org_id, user_id, code_hash, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertRecoveryCodeParams struct {
	OrgID    int64
	UserID   int64
	CodeHash string
	Now      time.Time
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode,
		arg.OrgID,
		arg.UserID,
		arg.CodeHash,
		arg.Now,
	)
	return err
}

const listUnusedRecoveryCodes = `-- name: ListUnusedRecoveryCodes :many
SELECT id, code_hash
FROM user_recovery_codes
WHERE org_id = $1 AND user_id = $2 AND used_at IS NULL
ORDER BY id
`

type ListUnusedRecoveryCodesParams struct {
	OrgID  int64
	UserID int64
}

type ListUnusedRecoveryCodesRow struct {
	ID       int64
	CodeHash string
}

func (q *Queries) ListUnusedRecoveryCodes(ctx context.Context, arg ListUnusedRecoveryCodesParams) ([]ListUnusedRecoveryCodesRow, error) {
	rows, err := q.db.Query(ctx, listUnusedRecoveryCodes, arg.OrgID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnusedRecoveryCodesRow{}
	for rows.Next() {
		var i ListUnusedRecoveryCodesRow
		if err := rows.Scan(&i.ID, &i.CodeHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPendingSeed = `-- name: SetPendingSeed :execrows
INSERT INTO user_totp (user_id, org_id, pending_seed_ciphertext, pending_seed_key_id, pending_seed_updated_at)
VALUES ($1, $2, $3, $4::text, $5::timestamptz)
ON CONFLICT (user_id) DO UPDATE
SET pending_seed_ciphertext = EXCLUDED.pending_seed_ciphertext, pending_seed_key_id = EXCLUDED.pending_seed_key_id,
    pending_seed_updated_at = EXCLUDED.pending_seed_updated_at
WHERE user_totp.org_id = $2 AND user_totp.seed_ciphertext IS NULL
`

type SetPendingSeedParams struct {
	UserID     int64
	OrgID      int64
	Ciphertext []byte
	KeyID      string
	Now        time.Time
}

// SetPendingSeed stores the seed of a begun enrolment, replacing a pending one; it changes nothing and returns no row
// while TOTP is enrolled.
func (q *Queries) SetPendingSeed(ctx context.Context, arg SetPendingSeedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPendingSeed,
		arg.UserID,
		arg.OrgID,
		arg.Ciphertext,
		arg.KeyID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
UPDATE user_recovery_codes
SET used_at = $1::timestamptz
WHERE org_id = $2 AND id = $3 AND used_at IS NULL
`

type UseRecoveryCodeParams struct {
	Now   time.Time
	OrgID int64
	ID    int64
}

// UseRecoveryCode marks a code used; no row changes when another request used it first.
func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCode, arg.Now, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const useStep = `-- name: UseStep :execrows
UPDATE user_totp
SET last_used_step = $1::bigint
WHERE org_id = $2 AND user_id = $3 AND seed_ciphertext IS NOT NULL
  AND (last_used_step IS NULL OR last_used_step < $1::bigint)
`

type UseStepParams struct {
	Step   int64
	OrgID  int64
	UserID int64
}

// UseStep records the time step of an accepted code; no row changes for a step already used or an older one, which
// refuses a replayed code.
func (q *Queries) UseStep(ctx context.Context, arg UseStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, useStep, arg.Step, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
