// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOpenGroupsByRoute = `-- name: CountOpenGroupsByRoute :many
SELECT r.public_id, g.status, count(*)::bigint AS count
FROM alert_groups g
JOIN routes r ON r.org_id = g.org_id AND r.id = g.route_id
WHERE g.org_id = $1 AND g.status <> 'resolved'
GROUP BY r.public_id, g.status
`

type CountOpenGroupsByRouteRow struct {
	PublicID string
	Status   string
	Count    int64
}

// CountOpenGroupsByRoute counts the open Alert Groups per Route that is not deleted and status, for
// muster_alert_groups.
func (q *Queries) CountOpenGroupsByRoute(ctx context.Context, orgID int64) ([]CountOpenGroupsByRouteRow, error) {
	rows, err := q.db.Query(ctx, countOpenGroupsByRoute, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOpenGroupsByRouteRow{}
	for rows.Next() {
		var i CountOpenGroupsByRouteRow
		if err := rows.Scan(&i.PublicID, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTimer = `-- name: DeleteTimer :exec
DELETE FROM timers
WHERE org_id = $1 AND alert_group_id = $2::bigint AND kind = $3
`

type DeleteTimerParams struct {
	OrgID        int64
	AlertGroupID int64
	Kind         string
}

// DeleteTimer stops an Alert Group's timer of a kind.
func (q *Queries) DeleteTimer(ctx context.Context, arg DeleteTimerParams) error {
	_, err := q.db.Exec(ctx, deleteTimer, arg.OrgID, arg.AlertGroupID, arg.Kind)
	return err
}

const ensureCounter = `-- name: EnsureCounter :exec
INSERT INTO alert_group_counters (org_id)
VALUES ($1)
ON CONFLICT (org_id) DO NOTHING
`

// EnsureCounter creates the Organization's row of alert_group_counters on first use.
func (q *Queries) EnsureCounter(ctx context.Context, orgID int64) error {
	_, err := q.db.Exec(ctx, ensureCounter, orgID)
	return err
}

const findOpenGroup = `-- name: FindOpenGroup :one
SELECT id
FROM alert_groups
WHERE org_id = $1 AND route_id = $2 AND group_key_sha256 = $3
  AND status <> 'resolved' AND moved_from_route_id IS NULL
`

type FindOpenGroupParams struct {
	OrgID          int64
	RouteID        int64
	GroupKeySha256 []byte
}

// FindOpenGroup finds the open Alert Group of a Route and Group key values; Alert Groups moved to the Default route
// are left out, as alert_groups_open_key leaves them out.
func (q *Queries) FindOpenGroup(ctx context.Context, arg FindOpenGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, findOpenGroup, arg.OrgID, arg.RouteID, arg.GroupKeySha256)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findReopenableGroup = `-- name: FindReopenableGroup :one
SELECT id
FROM alert_groups
WHERE org_id = $1 AND route_id = $2 AND group_key_sha256 = $3
  AND reopen_deadline > $4::timestamptz
ORDER BY resolved_at DESC, id DESC
LIMIT 1
`

type FindReopenableGroupParams struct {
	OrgID          int64
	RouteID        int64
	GroupKeySha256 []byte
	Now            time.Time
}

// FindReopenableGroup finds the latest system-resolved Alert Group of a Route and Group key values whose Reopen
// window is still open at now.
func (q *Queries) FindReopenableGroup(ctx context.Context, arg FindReopenableGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, findReopenableGroup,
		arg.OrgID,
		arg.RouteID,
		arg.GroupKeySha256,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDefaultRouteID = `-- name: GetDefaultRouteID :one
SELECT id
FROM routes
WHERE org_id = $1 AND is_default
`

// GetDefaultRouteID reads the id of the Default route.
func (q *Queries) GetDefaultRouteID(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDefaultRouteID, orgID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getGroup = `-- name: GetGroup :one
SELECT g.id, g.public_id, g.number, g.title, g.summary, g.status, g.severity_level, g.urgent, g.group_key_values,
       g.common_labels, g.common_annotations, g.integration_ids, g.reopen_count, g.firing_alert_count,
       g.resolved_alert_count, g.resolved_at, g.resolved_by_kind, g.resolved_by_user_id,
       g.resolved_by_service_account_id, g.resolve_reason, g.resolve_reason_text, g.created_at, g.last_changed_at,
       r.public_id AS route_public_id, r.name AS route_name,
       coalesce((SELECT p.number
                 FROM alert_groups p
                 WHERE p.org_id = g.org_id AND p.id = g.firing_again_after_id), 0)::bigint AS firing_again_after_number,
       coalesce((SELECT e.replaced_label
                 FROM timeline_entries e
                 WHERE e.org_id = g.org_id AND e.alert_group_id = g.id AND e.event = 'alert_replaced'
                 ORDER BY e.at DESC, e.id DESC
                 LIMIT 1), '')::text AS replaced_label,
       (SELECT count(*)
        FROM alert_group_alerts m
        WHERE m.org_id = g.org_id AND m.alert_group_id = g.id AND m.state = 'firing')::bigint AS still_firing
FROM alert_groups g
JOIN routes r ON r.org_id = g.org_id AND r.id = g.route_id
WHERE g.org_id = $1 AND g.public_id = $2
`

type GetGroupParams struct {
	OrgID    int64
	PublicID string
}

type GetGroupRow struct {
	ID                         int64
	PublicID                   string
	Number                     int64
	Title                      string
	Summary                    pgtype.Text
	Status                     string
	SeverityLevel              string
	Urgent                     bool
	GroupKeyValues             []byte
	CommonLabels               []byte
	CommonAnnotations          []byte
	IntegrationIds             []int64
	ReopenCount                int64
	FiringAlertCount           int64
	ResolvedAlertCount         int64
	ResolvedAt                 pgtype.Timestamptz
	ResolvedByKind             pgtype.Text
	ResolvedByUserID           pgtype.Int8
	ResolvedByServiceAccountID pgtype.Int8
	ResolveReason              pgtype.Text
	ResolveReasonText          pgtype.Text
	CreatedAt                  time.Time
	LastChangedAt              time.Time
	RoutePublicID              string
	RouteName                  string
	FiringAgainAfterNumber     int64
	ReplacedLabel              string
	StillFiring                int64
}

// GetGroup reads an Alert Group by public_id with its Route, the #N of the Alert Group it fires again after, the
// label of its latest Replacement and the Alerts still firing in it.
func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (GetGroupRow, error) {
	row := q.db.QueryRow(ctx, getGroup, arg.OrgID, arg.PublicID)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Number,
		&i.Title,
		&i.Summary,
		&i.Status,
		&i.SeverityLevel,
		&i.Urgent,
		&i.GroupKeyValues,
		&i.CommonLabels,
		&i.CommonAnnotations,
		&i.IntegrationIds,
		&i.ReopenCount,
		&i.FiringAlertCount,
		&i.ResolvedAlertCount,
		&i.ResolvedAt,
		&i.ResolvedByKind,
		&i.ResolvedByUserID,
		&i.ResolvedByServiceAccountID,
		&i.ResolveReason,
		&i.ResolveReasonText,
		&i.CreatedAt,
		&i.LastChangedAt,
		&i.RoutePublicID,
		&i.RouteName,
		&i.FiringAgainAfterNumber,
		&i.ReplacedLabel,
		&i.StillFiring,
	)
	return i, err
}

const getGroupID = `-- name: GetGroupID :one
SELECT id
FROM alert_groups
WHERE org_id = $1 AND public_id = $2
`

type GetGroupIDParams struct {
	OrgID    int64
	PublicID string
}

// GetGroupID reads the id of an Alert Group by public_id.
func (q *Queries) GetGroupID(ctx context.Context, arg GetGroupIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getGroupID, arg.OrgID, arg.PublicID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getGroupingSettings = `-- name: GetGroupingSettings :one


SELECT critical_is_urgent, instance_labels
FROM organizations
WHERE id = $1
`

type GetGroupingSettingsRow struct {
	CriticalIsUrgent bool
	InstanceLabels   []string
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// The queries of the Alert Group lifecycle. Only this package writes alert_groups, alert_group_alerts,
// timeline_entries, notes and alert_group_counters (lint 2). Times are business times passed in from Go.
// GetGroupingSettings reads the Organization settings grouping needs: critical is Urgent and the Instance labels.
func (q *Queries) GetGroupingSettings(ctx context.Context, orgID int64) (GetGroupingSettingsRow, error) {
	row := q.db.QueryRow(ctx, getGroupingSettings, orgID)
	var i GetGroupingSettingsRow
	err := row.Scan(&i.CriticalIsUrgent, &i.InstanceLabels)
	return i, err
}

const getRoutePolicy = `-- name: GetRoutePolicy :one
SELECT id, public_id, is_default, urgent, group_key, reopen_window_seconds, grace_period_seconds,
       urgent_rise_removes_ack
FROM routes
WHERE org_id = $1 AND id = $2
`

type GetRoutePolicyParams struct {
	OrgID int64
	ID    int64
}

type GetRoutePolicyRow struct {
	ID                   int64
	PublicID             string
	IsDefault            bool
	Urgent               bool
	GroupKey             []string
	ReopenWindowSeconds  int64
	GracePeriodSeconds   int64
	UrgentRiseRemovesAck bool
}

// GetRoutePolicy reads the policy of a Route, deleted or not, that an existing Alert Group belongs to.
func (q *Queries) GetRoutePolicy(ctx context.Context, arg GetRoutePolicyParams) (GetRoutePolicyRow, error) {
	row := q.db.QueryRow(ctx, getRoutePolicy, arg.OrgID, arg.ID)
	var i GetRoutePolicyRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.IsDefault,
		&i.Urgent,
		&i.GroupKey,
		&i.ReopenWindowSeconds,
		&i.GracePeriodSeconds,
		&i.UrgentRiseRemovesAck,
	)
	return i, err
}

const insertDowntimeEntries = `-- name: InsertDowntimeEntries :exec
INSERT INTO timeline_entries (org_id, public_id, alert_group_id, at, kind, system_event, actor_kind, transport,
                              period_from, period_to)
SELECT $1, unnest($2::text[]), unnest($3::bigint[]), $4, 'system',
       'muster_unavailable', 'system', 'system', $5::timestamptz, $6::timestamptz
`

type InsertDowntimeEntriesParams struct {
	OrgID         int64
	PublicIds     []string
	AlertGroupIds []int64
	At            time.Time
	PeriodFrom    time.Time
	PeriodTo      time.Time
}

// InsertDowntimeEntries records "Muster was unavailable from … to …" on Alert Groups.
func (q *Queries) InsertDowntimeEntries(ctx context.Context, arg InsertDowntimeEntriesParams) error {
	_, err := q.db.Exec(ctx, insertDowntimeEntries,
		arg.OrgID,
		arg.PublicIds,
		arg.AlertGroupIds,
		arg.At,
		arg.PeriodFrom,
		arg.PeriodTo,
	)
	return err
}

const insertGroup = `-- name: InsertGroup :one
INSERT INTO alert_groups (
    org_id, public_id, number, route_id, group_key_labels, group_key_values, group_key_sha256, title,
    title_from_group_key, summary, common_labels, common_annotations, integration_ids, status, severity_level, urgent,
    firing_again_after_id, created_at, last_changed_at
)
VALUES (
    $1, $2, $3, $4, $5::text[], $6, $7, $8,
    $9, $10, $11, $12, $13::bigint[],
    'firing', $14, $15, $16, $17, $17
)
RETURNING id
`

type InsertGroupParams struct {
	OrgID              int64
	PublicID           string
	Number             int64
	RouteID            int64
	GroupKeyLabels     []string
	GroupKeyValues     []byte
	GroupKeySha256     []byte
	Title              string
	TitleFromGroupKey  bool
	Summary            pgtype.Text
	CommonLabels       []byte
	CommonAnnotations  []byte
	IntegrationIds     []int64
	SeverityLevel      string
	Urgent             bool
	FiringAgainAfterID pgtype.Int8
	CreatedAt          time.Time
}

// InsertGroup creates an Alert Group, firing.
func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertGroup,
		arg.OrgID,
		arg.PublicID,
		arg.Number,
		arg.RouteID,
		arg.GroupKeyLabels,
		arg.GroupKeyValues,
		arg.GroupKeySha256,
		arg.Title,
		arg.TitleFromGroupKey,
		arg.Summary,
		arg.CommonLabels,
		arg.CommonAnnotations,
		arg.IntegrationIds,
		arg.SeverityLevel,
		arg.Urgent,
		arg.FiringAgainAfterID,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertMemberships = `-- name: InsertMemberships :exec
INSERT INTO alert_group_alerts (org_id, alert_group_id, alert_id, episode, state, joined_at, starts_at, annotations)
SELECT $1, unnest($2::bigint[]), unnest($3::bigint[]), unnest($4::bigint[]),
       'firing', $5, unnest($6::timestamptz[]), unnest($7::jsonb[])
`

type InsertMembershipsParams struct {
	OrgID         int64
	AlertGroupIds []int64
	AlertIds      []int64
	Episodes      []int64
	JoinedAt      time.Time
	StartsAts     []time.Time
	Annotations   [][]byte
}

// InsertMemberships adds Alerts to Alert Groups, firing.
func (q *Queries) InsertMemberships(ctx context.Context, arg InsertMembershipsParams) error {
	_, err := q.db.Exec(ctx, insertMemberships,
		arg.OrgID,
		arg.AlertGroupIds,
		arg.AlertIds,
		arg.Episodes,
		arg.JoinedAt,
		arg.StartsAts,
		arg.Annotations,
	)
	return err
}

const insertTimelineEntry = `-- name: InsertTimelineEntry :exec
INSERT INTO timeline_entries (
    org_id, public_id, alert_group_id, at, kind, event, event_seq, system_event, loudness, mentions, actor_kind,
    actor_user_id, actor_service_account_id, api_token_id, token_name, transport, reason, from_status, to_status,
    owner_user_id, previous_owner_user_id, snooze_until, fingerprints, replaced_label, label_conflicts, period_from,
    period_to, detail
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10::text[], $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19, $20,
    $21, $22, $23::text[],
    $24, $25::text[], $26,
    $27, $28
)
`

type InsertTimelineEntryParams struct {
	OrgID                 int64
	PublicID              string
	AlertGroupID          int64
	At                    time.Time
	Kind                  string
	Event                 pgtype.Text
	EventSeq              pgtype.Int8
	SystemEvent           pgtype.Text
	Loudness              pgtype.Text
	Mentions              []string
	ActorKind             string
	ActorUserID           pgtype.Int8
	ActorServiceAccountID pgtype.Int8
	ApiTokenID            pgtype.Int8
	TokenName             pgtype.Text
	Transport             string
	Reason                pgtype.Text
	FromStatus            pgtype.Text
	ToStatus              pgtype.Text
	OwnerUserID           pgtype.Int8
	PreviousOwnerUserID   pgtype.Int8
	SnoozeUntil           pgtype.Timestamptz
	Fingerprints          []string
	ReplacedLabel         pgtype.Text
	LabelConflicts        []string
	PeriodFrom            pgtype.Timestamptz
	PeriodTo              pgtype.Timestamptz
	Detail                pgtype.Text
}

// InsertTimelineEntry records one Timeline entry: a lifecycle event or a system entry.
func (q *Queries) InsertTimelineEntry(ctx context.Context, arg InsertTimelineEntryParams) error {
	_, err := q.db.Exec(ctx, insertTimelineEntry,
		arg.OrgID,
		arg.PublicID,
		arg.AlertGroupID,
		arg.At,
		arg.Kind,
		arg.Event,
		arg.EventSeq,
		arg.SystemEvent,
		arg.Loudness,
		arg.Mentions,
		arg.ActorKind,
		arg.ActorUserID,
		arg.ActorServiceAccountID,
		arg.ApiTokenID,
		arg.TokenName,
		arg.Transport,
		arg.Reason,
		arg.FromStatus,
		arg.ToStatus,
		arg.OwnerUserID,
		arg.PreviousOwnerUserID,
		arg.SnoozeUntil,
		arg.Fingerprints,
		arg.ReplacedLabel,
		arg.LabelConflicts,
		arg.PeriodFrom,
		arg.PeriodTo,
		arg.Detail,
	)
	return err
}

const isActiveUser = `-- name: IsActiveUser :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE org_id = $1 AND id = $2 AND status = 'active'
)::boolean AS active
`

type IsActiveUserParams struct {
	OrgID int64
	ID    int64
}

// IsActiveUser reports whether a User can still own an Alert Group: a disabled or deleted Owner has no
// acknowledgements.
func (q *Queries) IsActiveUser(ctx context.Context, arg IsActiveUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveUser, arg.OrgID, arg.ID)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const listAlertGroupKeys = `-- name: ListAlertGroupKeys :many
SELECT p.alert_id, g.group_key
FROM alert_presences p
JOIN alerts a ON a.org_id = p.org_id AND a.id = p.alert_id
JOIN alertmanager_groups g ON g.org_id = p.org_id AND g.id = p.alertmanager_group_id
WHERE p.org_id = $1 AND p.alert_id = ANY($2::bigint[]) AND p.last_seen_at >= a.fired_at
ORDER BY p.alert_id, g.group_key
`

type ListAlertGroupKeysParams struct {
	OrgID    int64
	AlertIds []int64
}

type ListAlertGroupKeysRow struct {
	AlertID  int64
	GroupKey string
}

// ListAlertGroupKeys lists the Alertmanager groupKeys that listed each Alert during its current or last firing.
func (q *Queries) ListAlertGroupKeys(ctx context.Context, arg ListAlertGroupKeysParams) ([]ListAlertGroupKeysRow, error) {
	rows, err := q.db.Query(ctx, listAlertGroupKeys, arg.OrgID, arg.AlertIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertGroupKeysRow{}
	for rows.Next() {
		var i ListAlertGroupKeysRow
		if err := rows.Scan(&i.AlertID, &i.GroupKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangedAlerts = `-- name: ListChangedAlerts :many
SELECT id, integration_id, fingerprint, labels, annotations, static_label_conflicts, status, starts_at, episode,
       route_id, severity_level
FROM alerts
WHERE org_id = $1 AND id = ANY($2::bigint[])
`

type ListChangedAlertsParams struct {
	OrgID int64
	Ids   []int64
}

type ListChangedAlertsRow struct {
	ID                   int64
	IntegrationID        int64
	Fingerprint          string
	Labels               []byte
	Annotations          []byte
	StaticLabelConflicts []string
	Status               string
	StartsAt             time.Time
	Episode              int64
	RouteID              pgtype.Int8
	SeverityLevel        pgtype.Text
}

// ListChangedAlerts reads the Alerts of a Snapshot's changes, with the Route and Severity level routing stamped.
func (q *Queries) ListChangedAlerts(ctx context.Context, arg ListChangedAlertsParams) ([]ListChangedAlertsRow, error) {
	rows, err := q.db.Query(ctx, listChangedAlerts, arg.OrgID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChangedAlertsRow{}
	for rows.Next() {
		var i ListChangedAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Fingerprint,
			&i.Labels,
			&i.Annotations,
			&i.StaticLabelConflicts,
			&i.Status,
			&i.StartsAt,
			&i.Episode,
			&i.RouteID,
			&i.SeverityLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiringMemberships = `-- name: ListFiringMemberships :many
SELECT id, alert_group_id, alert_id, episode, starts_at, annotations
FROM alert_group_alerts
WHERE org_id = $1 AND alert_id = ANY($2::bigint[]) AND state = 'firing'
`

type ListFiringMembershipsParams struct {
	OrgID    int64
	AlertIds []int64
}

type ListFiringMembershipsRow struct {
	ID           int64
	AlertGroupID int64
	AlertID      int64
	Episode      int64
	StartsAt     time.Time
	Annotations  []byte
}

// ListFiringMemberships reads where the Alerts fire: an Alert lives in at most one Alert Group at a time.
func (q *Queries) ListFiringMemberships(ctx context.Context, arg ListFiringMembershipsParams) ([]ListFiringMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listFiringMemberships, arg.OrgID, arg.AlertIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFiringMembershipsRow{}
	for rows.Next() {
		var i ListFiringMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertGroupID,
			&i.AlertID,
			&i.Episode,
			&i.StartsAt,
			&i.Annotations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupAlerts = `-- name: ListGroupAlerts :many
SELECT m.id, (m.state <> 'firing')::boolean AS ended, m.state, m.starts_at, m.annotations, m.ended_at,
       m.resolve_reason, m.resolve_reason_text, a.id AS alert_id, a.fingerprint, a.labels, a.generator_url,
       a.last_seen_at, i.public_id AS integration_public_id, i.name AS integration_name
FROM alert_group_alerts m
JOIN alerts a ON a.org_id = m.org_id AND a.id = m.alert_id
JOIN integrations i ON i.org_id = a.org_id AND i.id = a.integration_id
WHERE m.org_id = $1 AND m.alert_group_id = $2
  AND ($3::boolean OR (m.state = 'firing') = $4::boolean)
  AND ((m.state <> 'firing')::int, m.id) > ($5::int, $6::bigint)
ORDER BY (m.state <> 'firing')::int, m.id
LIMIT $7
`

type ListGroupAlertsParams struct {
	OrgID        int64
	AlertGroupID int64
	AllStates    bool
	Firing       bool
	AfterRank    int32
	AfterID      int64
	Lim          int32
}

type ListGroupAlertsRow struct {
	ID                  int64
	Ended               bool
	State               string
	StartsAt            time.Time
	Annotations         []byte
	EndedAt             pgtype.Timestamptz
	ResolveReason       pgtype.Text
	ResolveReasonText   pgtype.Text
	AlertID             int64
	Fingerprint         string
	Labels              []byte
	GeneratorUrl        pgtype.Text
	LastSeenAt          time.Time
	IntegrationPublicID string
	IntegrationName     string
}

// ListGroupAlerts lists the Alerts of an Alert Group, firing first, then those that ended, after a position; @rank
// is 0 for firing and 1 for ended.
func (q *Queries) ListGroupAlerts(ctx context.Context, arg ListGroupAlertsParams) ([]ListGroupAlertsRow, error) {
	rows, err := q.db.Query(ctx, listGroupAlerts,
		arg.OrgID,
		arg.AlertGroupID,
		arg.AllStates,
		arg.Firing,
		arg.AfterRank,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupAlertsRow{}
	for rows.Next() {
		var i ListGroupAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ended,
			&i.State,
			&i.StartsAt,
			&i.Annotations,
			&i.EndedAt,
			&i.ResolveReason,
			&i.ResolveReasonText,
			&i.AlertID,
			&i.Fingerprint,
			&i.Labels,
			&i.GeneratorUrl,
			&i.LastSeenAt,
			&i.IntegrationPublicID,
			&i.IntegrationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupFiringAlerts = `-- name: ListGroupFiringAlerts :many
SELECT m.id, m.alert_group_id, m.alert_id, m.episode, m.starts_at, m.annotations, a.integration_id, a.fingerprint,
       a.labels, a.static_label_conflicts, a.severity_level, a.status
FROM alert_group_alerts m
JOIN alerts a ON a.org_id = m.org_id AND a.id = m.alert_id
WHERE m.org_id = $1 AND m.alert_group_id = ANY($2::bigint[]) AND m.state = 'firing'
ORDER BY m.alert_group_id, m.id
`

type ListGroupFiringAlertsParams struct {
	OrgID         int64
	AlertGroupIds []int64
}

type ListGroupFiringAlertsRow struct {
	ID                   int64
	AlertGroupID         int64
	AlertID              int64
	Episode              int64
	StartsAt             time.Time
	Annotations          []byte
	IntegrationID        int64
	Fingerprint          string
	Labels               []byte
	StaticLabelConflicts []string
	SeverityLevel        pgtype.Text
	Status               string
}

// ListGroupFiringAlerts lists the Alerts firing in Alert Groups with their labels: the comparison of a Replacement,
// and the tails that a Grace period end groups again.
func (q *Queries) ListGroupFiringAlerts(ctx context.Context, arg ListGroupFiringAlertsParams) ([]ListGroupFiringAlertsRow, error) {
	rows, err := q.db.Query(ctx, listGroupFiringAlerts, arg.OrgID, arg.AlertGroupIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupFiringAlertsRow{}
	for rows.Next() {
		var i ListGroupFiringAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertGroupID,
			&i.AlertID,
			&i.Episode,
			&i.StartsAt,
			&i.Annotations,
			&i.IntegrationID,
			&i.Fingerprint,
			&i.Labels,
			&i.StaticLabelConflicts,
			&i.SeverityLevel,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationRefs = `-- name: ListIntegrationRefs :many
SELECT id, public_id, name
FROM integrations
WHERE org_id = $1 AND id = ANY($2::bigint[])
ORDER BY name, id
`

type ListIntegrationRefsParams struct {
	OrgID int64
	Ids   []int64
}

type ListIntegrationRefsRow struct {
	ID       int64
	PublicID string
	Name     string
}

// ListIntegrationRefs names Integrations, deleted ones included.
func (q *Queries) ListIntegrationRefs(ctx context.Context, arg ListIntegrationRefsParams) ([]ListIntegrationRefsRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationRefs, arg.OrgID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIntegrationRefsRow{}
	for rows.Next() {
		var i ListIntegrationRefsRow
		if err := rows.Scan(&i.ID, &i.PublicID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenGroupIDs = `-- name: ListOpenGroupIDs :many
SELECT id
FROM alert_groups
WHERE org_id = $1 AND status <> 'resolved'
ORDER BY id
`

// ListOpenGroupIDs lists the open Alert Groups of the Organization, for the downtime entries.
func (q *Queries) ListOpenGroupIDs(ctx context.Context, orgID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOpenGroupIDs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenGroupsOfRoute = `-- name: ListOpenGroupsOfRoute :many
SELECT id
FROM alert_groups
WHERE org_id = $1 AND route_id = $2 AND status <> 'resolved' AND moved_from_route_id IS NULL
ORDER BY id
`

type ListOpenGroupsOfRouteParams struct {
	OrgID   int64
	RouteID int64
}

// ListOpenGroupsOfRoute lists the open Alert Groups of a Route.
func (q *Queries) ListOpenGroupsOfRoute(ctx context.Context, arg ListOpenGroupsOfRouteParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOpenGroupsOfRoute, arg.OrgID, arg.RouteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutePublicIDs = `-- name: ListRoutePublicIDs :many
SELECT public_id
FROM routes
WHERE org_id = $1 AND deleted_at IS NULL
`

// ListRoutePublicIDs lists the Routes that are not deleted, for the zero series of muster_alert_groups.
func (q *Queries) ListRoutePublicIDs(ctx context.Context, orgID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoutePublicIDs, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var public_id string
		if err := rows.Scan(&public_id); err != nil {
			return nil, err
		}
		items = append(items, public_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceAccountRefs = `-- name: ListServiceAccountRefs :many
SELECT id, public_id, name, status
FROM service_accounts
WHERE org_id = $1 AND id = ANY($2::bigint[])
`

type ListServiceAccountRefsParams struct {
	OrgID int64
	Ids   []int64
}

type ListServiceAccountRefsRow struct {
	ID       int64
	PublicID string
	Name     string
	Status   string
}

// ListServiceAccountRefs names Service accounts, deleted ones included.
func (q *Queries) ListServiceAccountRefs(ctx context.Context, arg ListServiceAccountRefsParams) ([]ListServiceAccountRefsRow, error) {
	rows, err := q.db.Query(ctx, listServiceAccountRefs, arg.OrgID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceAccountRefsRow{}
	for rows.Next() {
		var i ListServiceAccountRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineAsc = `-- name: ListTimelineAsc :many
SELECT id, public_id, at, kind, event, event_seq, system_event, loudness, mentions, actor_kind, actor_user_id,
       actor_service_account_id, token_name, transport, reason, from_status, to_status, owner_user_id,
       previous_owner_user_id, snooze_until, fingerprints, replaced_label, label_conflicts, notice_number,
       missed_count, period_from, period_to, detail
FROM timeline_entries
WHERE org_id = $1 AND alert_group_id = $2
  AND (cardinality($3::text[]) = 0 OR kind = ANY($3::text[]))
  AND ($4::timestamptz IS NULL
       OR (at, 0, id) > ($4::timestamptz, $5::int, $6::bigint))
ORDER BY at, id
LIMIT $7
`

type ListTimelineAscParams struct {
	OrgID        int64
	AlertGroupID int64
	Kinds        []string
	At           pgtype.Timestamptz
	Source       int32
	ID           int64
	Lim          int32
}

type ListTimelineAscRow struct {
	ID                    int64
	PublicID              string
	At                    time.Time
	Kind                  string
	Event                 pgtype.Text
	EventSeq              pgtype.Int8
	SystemEvent           pgtype.Text
	Loudness              pgtype.Text
	Mentions              []string
	ActorKind             string
	ActorUserID           pgtype.Int8
	ActorServiceAccountID pgtype.Int8
	TokenName             pgtype.Text
	Transport             string
	Reason                pgtype.Text
	FromStatus            pgtype.Text
	ToStatus              pgtype.Text
	OwnerUserID           pgtype.Int8
	PreviousOwnerUserID   pgtype.Int8
	SnoozeUntil           pgtype.Timestamptz
	Fingerprints          []string
	ReplacedLabel         pgtype.Text
	LabelConflicts        []string
	NoticeNumber          pgtype.Int8
	MissedCount           pgtype.Int8
	PeriodFrom            pgtype.Timestamptz
	PeriodTo              pgtype.Timestamptz
	Detail                pgtype.Text
}

// ListTimelineAsc reads the Timeline entries of an Alert Group, oldest first, after a position.
func (q *Queries) ListTimelineAsc(ctx context.Context, arg ListTimelineAscParams) ([]ListTimelineAscRow, error) {
	rows, err := q.db.Query(ctx, listTimelineAsc,
		arg.OrgID,
		arg.AlertGroupID,
		arg.Kinds,
		arg.At,
		arg.Source,
		arg.ID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineAscRow{}
	for rows.Next() {
		var i ListTimelineAscRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.At,
			&i.Kind,
			&i.Event,
			&i.EventSeq,
			&i.SystemEvent,
			&i.Loudness,
			&i.Mentions,
			&i.ActorKind,
			&i.ActorUserID,
			&i.ActorServiceAccountID,
			&i.TokenName,
			&i.Transport,
			&i.Reason,
			&i.FromStatus,
			&i.ToStatus,
			&i.OwnerUserID,
			&i.PreviousOwnerUserID,
			&i.SnoozeUntil,
			&i.Fingerprints,
			&i.ReplacedLabel,
			&i.LabelConflicts,
			&i.NoticeNumber,
			&i.MissedCount,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineDeliveryEvents = `-- name: ListTimelineDeliveryEvents :many
SELECT e.id, e.public_id, e.occurred_at, e.kind, e.loudness, e.mentions, e.error, d.public_id AS destination_public_id,
       d.name AS destination_name
FROM delivery_events e
JOIN destinations d ON d.org_id = e.org_id AND d.id = e.destination_id
WHERE e.org_id = $1 AND e.alert_group_id = $2::bigint
  AND ($3::timestamptz IS NULL
       OR ($4::boolean
           AND (e.occurred_at, 2, e.id) < ($3::timestamptz, $5::int, $6::bigint))
       OR (NOT $4::boolean
           AND (e.occurred_at, 2, e.id) > ($3::timestamptz, $5::int, $6::bigint)))
ORDER BY CASE WHEN $4::boolean THEN e.occurred_at END DESC,
         CASE WHEN $4::boolean THEN e.id END DESC, e.occurred_at, e.id
LIMIT $7
`

type ListTimelineDeliveryEventsParams struct {
	OrgID        int64
	AlertGroupID int64
	At           pgtype.Timestamptz
	Descending   bool
	Source       int32
	ID           int64
	Lim          int32
}

type ListTimelineDeliveryEventsRow struct {
	ID                  int64
	PublicID            string
	OccurredAt          time.Time
	Kind                string
	Loudness            string
	Mentions            []string
	Error               pgtype.Text
	DestinationPublicID string
	DestinationName     string
}

// ListTimelineDeliveryEvents reads the delivery events of an Alert Group for the Timeline, newest first with
// @descending, after a position.
func (q *Queries) ListTimelineDeliveryEvents(ctx context.Context, arg ListTimelineDeliveryEventsParams) ([]ListTimelineDeliveryEventsRow, error) {
	rows, err := q.db.Query(ctx, listTimelineDeliveryEvents,
		arg.OrgID,
		arg.AlertGroupID,
		arg.At,
		arg.Descending,
		arg.Source,
		arg.ID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineDeliveryEventsRow{}
	for rows.Next() {
		var i ListTimelineDeliveryEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OccurredAt,
			&i.Kind,
			&i.Loudness,
			&i.Mentions,
			&i.Error,
			&i.DestinationPublicID,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineDesc = `-- name: ListTimelineDesc :many

SELECT id, public_id, at, kind, event, event_seq, system_event, loudness, mentions, actor_kind, actor_user_id,
       actor_service_account_id, token_name, transport, reason, from_status, to_status, owner_user_id,
       previous_owner_user_id, snooze_until, fingerprints, replaced_label, label_conflicts, notice_number,
       missed_count, period_from, period_to, detail
FROM timeline_entries
WHERE org_id = $1 AND alert_group_id = $2
  AND (cardinality($3::text[]) = 0 OR kind = ANY($3::text[]))
  AND ($4::timestamptz IS NULL
       OR (at, 0, id) < ($4::timestamptz, $5::int, $6::bigint))
ORDER BY at DESC, id DESC
LIMIT $7
`

type ListTimelineDescParams struct {
	OrgID        int64
	AlertGroupID int64
	Kinds        []string
	At           pgtype.Timestamptz
	Source       int32
	ID           int64
	Lim          int32
}

type ListTimelineDescRow struct {
	ID                    int64
	PublicID              string
	At                    time.Time
	Kind                  string
	Event                 pgtype.Text
	EventSeq              pgtype.Int8
	SystemEvent           pgtype.Text
	Loudness              pgtype.Text
	Mentions              []string
	ActorKind             string
	ActorUserID           pgtype.Int8
	ActorServiceAccountID pgtype.Int8
	TokenName             pgtype.Text
	Transport             string
	Reason                pgtype.Text
	FromStatus            pgtype.Text
	ToStatus              pgtype.Text
	OwnerUserID           pgtype.Int8
	PreviousOwnerUserID   pgtype.Int8
	SnoozeUntil           pgtype.Timestamptz
	Fingerprints          []string
	ReplacedLabel         pgtype.Text
	LabelConflicts        []string
	NoticeNumber          pgtype.Int8
	MissedCount           pgtype.Int8
	PeriodFrom            pgtype.Timestamptz
	PeriodTo              pgtype.Timestamptz
	Detail                pgtype.Text
}

// The Timeline merges three sources by (at, source, id): its entries (source 0), Notes (1) and delivery events (2).
// A page reads up to @lim of each after the position of the previous page and keeps the first @lim of the merge.
// ListTimelineDesc reads the Timeline entries of an Alert Group, newest first, before a position.
func (q *Queries) ListTimelineDesc(ctx context.Context, arg ListTimelineDescParams) ([]ListTimelineDescRow, error) {
	rows, err := q.db.Query(ctx, listTimelineDesc,
		arg.OrgID,
		arg.AlertGroupID,
		arg.Kinds,
		arg.At,
		arg.Source,
		arg.ID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineDescRow{}
	for rows.Next() {
		var i ListTimelineDescRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.At,
			&i.Kind,
			&i.Event,
			&i.EventSeq,
			&i.SystemEvent,
			&i.Loudness,
			&i.Mentions,
			&i.ActorKind,
			&i.ActorUserID,
			&i.ActorServiceAccountID,
			&i.TokenName,
			&i.Transport,
			&i.Reason,
			&i.FromStatus,
			&i.ToStatus,
			&i.OwnerUserID,
			&i.PreviousOwnerUserID,
			&i.SnoozeUntil,
			&i.Fingerprints,
			&i.ReplacedLabel,
			&i.LabelConflicts,
			&i.NoticeNumber,
			&i.MissedCount,
			&i.PeriodFrom,
			&i.PeriodTo,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimelineNotes = `-- name: ListTimelineNotes :many
SELECT id, public_id, created_at, body, actor_kind, actor_user_id, actor_service_account_id, token_name, transport
FROM notes
WHERE org_id = $1 AND alert_group_id = $2
  AND ($3::timestamptz IS NULL
       OR ($4::boolean AND (created_at, 1, id) < ($3::timestamptz, $5::int, $6::bigint))
       OR (NOT $4::boolean
           AND (created_at, 1, id) > ($3::timestamptz, $5::int, $6::bigint)))
ORDER BY CASE WHEN $4::boolean THEN created_at END DESC, CASE WHEN $4::boolean THEN id END DESC,
         created_at, id
LIMIT $7
`

type ListTimelineNotesParams struct {
	OrgID        int64
	AlertGroupID int64
	At           pgtype.Timestamptz
	Descending   bool
	Source       int32
	ID           int64
	Lim          int32
}

type ListTimelineNotesRow struct {
	ID                    int64
	PublicID              string
	CreatedAt             time.Time
	Body                  string
	ActorKind             string
	ActorUserID           pgtype.Int8
	ActorServiceAccountID pgtype.Int8
	TokenName             pgtype.Text
	Transport             string
}

// ListTimelineNotes reads the Notes of an Alert Group for the Timeline, newest first with @descending, after a
// position.
func (q *Queries) ListTimelineNotes(ctx context.Context, arg ListTimelineNotesParams) ([]ListTimelineNotesRow, error) {
	rows, err := q.db.Query(ctx, listTimelineNotes,
		arg.OrgID,
		arg.AlertGroupID,
		arg.At,
		arg.Descending,
		arg.Source,
		arg.ID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimelineNotesRow{}
	for rows.Next() {
		var i ListTimelineNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CreatedAt,
			&i.Body,
			&i.ActorKind,
			&i.ActorUserID,
			&i.ActorServiceAccountID,
			&i.TokenName,
			&i.Transport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRefs = `-- name: ListUserRefs :many
SELECT id, public_id, name, login, status
FROM users
WHERE org_id = $1 AND id = ANY($2::bigint[])
`

type ListUserRefsParams struct {
	OrgID int64
	Ids   []int64
}

type ListUserRefsRow struct {
	ID       int64
	PublicID string
	Name     string
	Login    string
	Status   string
}

// ListUserRefs names Users, deleted ones included.
func (q *Queries) ListUserRefs(ctx context.Context, arg ListUserRefsParams) ([]ListUserRefsRow, error) {
	rows, err := q.db.Query(ctx, listUserRefs, arg.OrgID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRefsRow{}
	for rows.Next() {
		var i ListUserRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Login,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCounter = `-- name: LockCounter :one
SELECT last_number
FROM alert_group_counters
WHERE org_id = $1
FOR UPDATE
`

// LockCounter locks the Organization's counter row: every change that makes an Alert Group open — a creation or a
// Reopen — takes it first, so that two of them never race for one Route and Group key.
func (q *Queries) LockCounter(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockCounter, orgID)
	var last_number int64
	err := row.Scan(&last_number)
	return last_number, err
}

const lockDefaultRoute = `-- name: LockDefaultRoute :one
SELECT id, public_id, is_default, urgent, group_key, reopen_window_seconds, grace_period_seconds,
       urgent_rise_removes_ack
FROM routes
WHERE org_id = $1 AND is_default
FOR SHARE
`

type LockDefaultRouteRow struct {
	ID                   int64
	PublicID             string
	IsDefault            bool
	Urgent               bool
	GroupKey             []string
	ReopenWindowSeconds  int64
	GracePeriodSeconds   int64
	UrgentRiseRemovesAck bool
}

// LockDefaultRoute locks the Default route FOR SHARE, for the Alerts whose Route was deleted meanwhile.
func (q *Queries) LockDefaultRoute(ctx context.Context, orgID int64) (LockDefaultRouteRow, error) {
	row := q.db.QueryRow(ctx, lockDefaultRoute, orgID)
	var i LockDefaultRouteRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.IsDefault,
		&i.Urgent,
		&i.GroupKey,
		&i.ReopenWindowSeconds,
		&i.GracePeriodSeconds,
		&i.UrgentRiseRemovesAck,
	)
	return i, err
}

const lockGroups = `-- name: LockGroups :many
SELECT id, public_id, number, route_id, moved_from_route_id, group_key_labels, group_key_values, group_key_sha256,
       title, title_from_group_key, summary, common_labels, common_annotations, integration_ids, status,
       severity_level, urgent, owner_user_id, acknowledged_at, snooze_until, snooze_no_end, snoozed_while_urgent,
       snoozed_by_user_id, snoozed_by_service_account_id, firing_alert_count, resolved_alert_count, reopen_count,
       resolved_at, resolved_by_kind, resolved_by_user_id, resolved_by_service_account_id, resolve_reason,
       resolve_reason_text, reopen_deadline, prior_status, prior_owner_user_id, prior_snooze_until,
       prior_snooze_no_end, prior_snoozed_while_urgent, prior_snoozed_by_user_id,
       prior_snoozed_by_service_account_id, grace_deadline, firing_again_after_id, event_seq, created_at,
       last_changed_at
FROM alert_groups
WHERE org_id = $1 AND id = ANY($2::bigint[])
ORDER BY id
FOR UPDATE
`

type LockGroupsParams struct {
	OrgID int64
	Ids   []int64
}

type LockGroupsRow struct {
	ID                             int64
	PublicID                       string
	Number                         int64
	RouteID                        int64
	MovedFromRouteID               pgtype.Int8
	GroupKeyLabels                 []string
	GroupKeyValues                 []byte
	GroupKeySha256                 []byte
	Title                          string
	TitleFromGroupKey              bool
	Summary                        pgtype.Text
	CommonLabels                   []byte
	CommonAnnotations              []byte
	IntegrationIds                 []int64
	Status                         string
	SeverityLevel                  string
	Urgent                         bool
	OwnerUserID                    pgtype.Int8
	AcknowledgedAt                 pgtype.Timestamptz
	SnoozeUntil                    pgtype.Timestamptz
	SnoozeNoEnd                    bool
	SnoozedWhileUrgent             bool
	SnoozedByUserID                pgtype.Int8
	SnoozedByServiceAccountID      pgtype.Int8
	FiringAlertCount               int64
	ResolvedAlertCount             int64
	ReopenCount                    int64
	ResolvedAt                     pgtype.Timestamptz
	ResolvedByKind                 pgtype.Text
	ResolvedByUserID               pgtype.Int8
	ResolvedByServiceAccountID     pgtype.Int8
	ResolveReason                  pgtype.Text
	ResolveReasonText              pgtype.Text
	ReopenDeadline                 pgtype.Timestamptz
	PriorStatus                    pgtype.Text
	PriorOwnerUserID               pgtype.Int8
	PriorSnoozeUntil               pgtype.Timestamptz
	PriorSnoozeNoEnd               pgtype.Bool
	PriorSnoozedWhileUrgent        pgtype.Bool
	PriorSnoozedByUserID           pgtype.Int8
	PriorSnoozedByServiceAccountID pgtype.Int8
	GraceDeadline                  pgtype.Timestamptz
	FiringAgainAfterID             pgtype.Int8
	EventSeq                       int64
	CreatedAt                      time.Time
	LastChangedAt                  time.Time
}

// LockGroups locks Alert Groups for a change, in id order, so that two transactions never wait for each other.
func (q *Queries) LockGroups(ctx context.Context, arg LockGroupsParams) ([]LockGroupsRow, error) {
	rows, err := q.db.Query(ctx, lockGroups, arg.OrgID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockGroupsRow{}
	for rows.Next() {
		var i LockGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Number,
			&i.RouteID,
			&i.MovedFromRouteID,
			&i.GroupKeyLabels,
			&i.GroupKeyValues,
			&i.GroupKeySha256,
			&i.Title,
			&i.TitleFromGroupKey,
			&i.Summary,
			&i.CommonLabels,
			&i.CommonAnnotations,
			&i.IntegrationIds,
			&i.Status,
			&i.SeverityLevel,
			&i.Urgent,
			&i.OwnerUserID,
			&i.AcknowledgedAt,
			&i.SnoozeUntil,
			&i.SnoozeNoEnd,
			&i.SnoozedWhileUrgent,
			&i.SnoozedByUserID,
			&i.SnoozedByServiceAccountID,
			&i.FiringAlertCount,
			&i.ResolvedAlertCount,
			&i.ReopenCount,
			&i.ResolvedAt,
			&i.ResolvedByKind,
			&i.ResolvedByUserID,
			&i.ResolvedByServiceAccountID,
			&i.ResolveReason,
			&i.ResolveReasonText,
			&i.ReopenDeadline,
			&i.PriorStatus,
			&i.PriorOwnerUserID,
			&i.PriorSnoozeUntil,
			&i.PriorSnoozeNoEnd,
			&i.PriorSnoozedWhileUrgent,
			&i.PriorSnoozedByUserID,
			&i.PriorSnoozedByServiceAccountID,
			&i.GraceDeadline,
			&i.FiringAgainAfterID,
			&i.EventSeq,
			&i.CreatedAt,
			&i.LastChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRouteForMove = `-- name: LockRouteForMove :one
SELECT id, public_id, name, is_default
FROM routes
WHERE org_id = $1 AND public_id = $2 AND deleted_at IS NULL
FOR NO KEY UPDATE
`

type LockRouteForMoveParams struct {
	OrgID    int64
	PublicID string
}

type LockRouteForMoveRow struct {
	ID        int64
	PublicID  string
	Name      string
	IsDefault bool
}

// LockRouteForMove locks a Route that is not deleted against grouping, which takes it FOR SHARE, while its open
// Alert Groups move to the Default route.
func (q *Queries) LockRouteForMove(ctx context.Context, arg LockRouteForMoveParams) (LockRouteForMoveRow, error) {
	row := q.db.QueryRow(ctx, lockRouteForMove, arg.OrgID, arg.PublicID)
	var i LockRouteForMoveRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.IsDefault,
	)
	return i, err
}

const lockRoutes = `-- name: LockRoutes :many
SELECT id, public_id, is_default, urgent, group_key, reopen_window_seconds, grace_period_seconds,
       urgent_rise_removes_ack
FROM routes
WHERE org_id = $1 AND id = ANY($2::bigint[]) AND deleted_at IS NULL
ORDER BY id
FOR SHARE
`

type LockRoutesParams struct {
	OrgID int64
	Ids   []int64
}

type LockRoutesRow struct {
	ID                   int64
	PublicID             string
	IsDefault            bool
	Urgent               bool
	GroupKey             []string
	ReopenWindowSeconds  int64
	GracePeriodSeconds   int64
	UrgentRiseRemovesAck bool
}

// LockRoutes locks the Routes that are not deleted FOR SHARE before grouping creates or joins an Alert Group on
// them, in id order: a deletion, which locks its Route FOR NO KEY UPDATE and then counts the open Alert Groups, waits
// for the Snapshot, or commits first and leaves the Route out of the result.
func (q *Queries) LockRoutes(ctx context.Context, arg LockRoutesParams) ([]LockRoutesRow, error) {
	rows, err := q.db.Query(ctx, lockRoutes, arg.OrgID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockRoutesRow{}
	for rows.Next() {
		var i LockRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.IsDefault,
			&i.Urgent,
			&i.GroupKey,
			&i.ReopenWindowSeconds,
			&i.GracePeriodSeconds,
			&i.UrgentRiseRemovesAck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveMemberships = `-- name: MoveMemberships :exec
UPDATE alert_group_alerts m
SET state = 'moved', ended_at = $1::timestamptz, moved_to_alert_group_id = r.moved_to
FROM (SELECT unnest($3::bigint[]) AS id, unnest($4::bigint[]) AS moved_to) AS r
WHERE m.org_id = $2 AND m.id = r.id AND m.state = 'firing'
`

type MoveMembershipsParams struct {
	EndedAt  time.Time
	OrgID    int64
	Ids      []int64
	MovedTos []int64
}

// MoveMemberships ends firing memberships whose Alerts were grouped again, into the Alert Group that took them.
func (q *Queries) MoveMemberships(ctx context.Context, arg MoveMembershipsParams) error {
	_, err := q.db.Exec(ctx, moveMemberships,
		arg.EndedAt,
		arg.OrgID,
		arg.Ids,
		arg.MovedTos,
	)
	return err
}

const nextNumber = `-- name: NextNumber :one
UPDATE alert_group_counters
SET last_number = last_number + 1
WHERE org_id = $1
RETURNING last_number
`

// NextNumber takes the next #N; a rollback returns it, so no gap appears.
func (q *Queries) NextNumber(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, nextNumber, orgID)
	var last_number int64
	err := row.Scan(&last_number)
	return last_number, err
}

const notifyTimers = `-- name: NotifyTimers :exec
SELECT pg_notify($1::text, '')
`

// NotifyTimers wakes the timer workers of every replica once the transaction commits.
func (q *Queries) NotifyTimers(ctx context.Context, channel string) error {
	_, err := q.db.Exec(ctx, notifyTimers, channel)
	return err
}

const peekGroup = `-- name: PeekGroup :one
SELECT route_id, grace_deadline
FROM alert_groups
WHERE org_id = $1 AND id = $2
`

type PeekGroupParams struct {
	OrgID int64
	ID    int64
}

type PeekGroupRow struct {
	RouteID       int64
	GraceDeadline pgtype.Timestamptz
}

// PeekGroup reads, without a lock, the Route and the Grace period of an Alert Group, so that the end of its Grace
// period finds the Alert Groups it changes before it locks them all in id order.
func (q *Queries) PeekGroup(ctx context.Context, arg PeekGroupParams) (PeekGroupRow, error) {
	row := q.db.QueryRow(ctx, peekGroup, arg.OrgID, arg.ID)
	var i PeekGroupRow
	err := row.Scan(&i.RouteID, &i.GraceDeadline)
	return i, err
}

const resolveMemberships = `-- name: ResolveMemberships :exec
UPDATE alert_group_alerts m
SET state = 'resolved', ended_at = $1::timestamptz, resolve_reason = r.reason, resolve_reason_text = r.reason_text
FROM (SELECT unnest($3::bigint[]) AS id, unnest($4::text[]) AS reason,
             unnest($5::text[]) AS reason_text) AS r
WHERE m.org_id = $2 AND m.id = r.id AND m.state = 'firing'
`

type ResolveMembershipsParams struct {
	EndedAt     time.Time
	OrgID       int64
	Ids         []int64
	Reasons     []string
	ReasonTexts []string
}

// ResolveMemberships ends firing memberships whose Alerts resolved, each with its reason.
func (q *Queries) ResolveMemberships(ctx context.Context, arg ResolveMembershipsParams) error {
	_, err := q.db.Exec(ctx, resolveMemberships,
		arg.EndedAt,
		arg.OrgID,
		arg.Ids,
		arg.Reasons,
		arg.ReasonTexts,
	)
	return err
}

const saveGroup = `-- name: SaveGroup :exec
UPDATE alert_groups
SET route_id = $1, moved_from_route_id = $2, title = $3,
    title_from_group_key = $4, summary = $5, common_labels = $6,
    common_annotations = $7, integration_ids = $8::bigint[], status = $9,
    severity_level = $10, urgent = $11, owner_user_id = $12,
    acknowledged_at = $13, snooze_until = $14,
    snooze_no_end = $15, snoozed_while_urgent = $16,
    snoozed_by_user_id = $17,
    snoozed_by_service_account_id = $18,
    firing_alert_count = $19, resolved_alert_count = $20,
    reopen_count = $21, resolved_at = $22,
    resolved_by_kind = $23, resolved_by_user_id = $24,
    resolved_by_service_account_id = $25,
    resolve_reason = $26, resolve_reason_text = $27,
    reopen_deadline = $28, prior_status = $29,
    prior_owner_user_id = $30, prior_snooze_until = $31,
    prior_snooze_no_end = $32,
    prior_snoozed_while_urgent = $33,
    prior_snoozed_by_user_id = $34,
    prior_snoozed_by_service_account_id = $35,
    grace_deadline = $36, event_seq = $37, last_changed_at = $38
WHERE org_id = $39 AND id = $40
`

type SaveGroupParams struct {
	RouteID                        int64
	MovedFromRouteID               pgtype.Int8
	Title                          string
	TitleFromGroupKey              bool
	Summary                        pgtype.Text
	CommonLabels                   []byte
	CommonAnnotations              []byte
	IntegrationIds                 []int64
	Status                         string
	SeverityLevel                  string
	Urgent                         bool
	OwnerUserID                    pgtype.Int8
	AcknowledgedAt                 pgtype.Timestamptz
	SnoozeUntil                    pgtype.Timestamptz
	SnoozeNoEnd                    bool
	SnoozedWhileUrgent             bool
	SnoozedByUserID                pgtype.Int8
	SnoozedByServiceAccountID      pgtype.Int8
	FiringAlertCount               int64
	ResolvedAlertCount             int64
	ReopenCount                    int64
	ResolvedAt                     pgtype.Timestamptz
	ResolvedByKind                 pgtype.Text
	ResolvedByUserID               pgtype.Int8
	ResolvedByServiceAccountID     pgtype.Int8
	ResolveReason                  pgtype.Text
	ResolveReasonText              pgtype.Text
	ReopenDeadline                 pgtype.Timestamptz
	PriorStatus                    pgtype.Text
	PriorOwnerUserID               pgtype.Int8
	PriorSnoozeUntil               pgtype.Timestamptz
	PriorSnoozeNoEnd               pgtype.Bool
	PriorSnoozedWhileUrgent        pgtype.Bool
	PriorSnoozedByUserID           pgtype.Int8
	PriorSnoozedByServiceAccountID pgtype.Int8
	GraceDeadline                  pgtype.Timestamptz
	EventSeq                       int64
	LastChangedAt                  time.Time
	OrgID                          int64
	ID                             int64
}

// SaveGroup writes the state of an Alert Group after a change.
func (q *Queries) SaveGroup(ctx context.Context, arg SaveGroupParams) error {
	_, err := q.db.Exec(ctx, saveGroup,
		arg.RouteID,
		arg.MovedFromRouteID,
		arg.Title,
		arg.TitleFromGroupKey,
		arg.Summary,
		arg.CommonLabels,
		arg.CommonAnnotations,
		arg.IntegrationIds,
		arg.Status,
		arg.SeverityLevel,
		arg.Urgent,
		arg.OwnerUserID,
		arg.AcknowledgedAt,
		arg.SnoozeUntil,
		arg.SnoozeNoEnd,
		arg.SnoozedWhileUrgent,
		arg.SnoozedByUserID,
		arg.SnoozedByServiceAccountID,
		arg.FiringAlertCount,
		arg.ResolvedAlertCount,
		arg.ReopenCount,
		arg.ResolvedAt,
		arg.ResolvedByKind,
		arg.ResolvedByUserID,
		arg.ResolvedByServiceAccountID,
		arg.ResolveReason,
		arg.ResolveReasonText,
		arg.ReopenDeadline,
		arg.PriorStatus,
		arg.PriorOwnerUserID,
		arg.PriorSnoozeUntil,
		arg.PriorSnoozeNoEnd,
		arg.PriorSnoozedWhileUrgent,
		arg.PriorSnoozedByUserID,
		arg.PriorSnoozedByServiceAccountID,
		arg.GraceDeadline,
		arg.EventSeq,
		arg.LastChangedAt,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const updateMemberships = `-- name: UpdateMemberships :exec
UPDATE alert_group_alerts m
SET starts_at = r.starts_at, annotations = r.annotations
FROM (SELECT unnest($2::bigint[]) AS id, unnest($3::timestamptz[]) AS starts_at,
             unnest($4::jsonb[]) AS annotations) AS r
WHERE m.org_id = $1 AND m.id = r.id
`

type UpdateMembershipsParams struct {
	OrgID       int64
	Ids         []int64
	StartsAts   []time.Time
	Annotations [][]byte
}

// UpdateMemberships records the startsAt of a Continuation and the annotations as last seen.
func (q *Queries) UpdateMemberships(ctx context.Context, arg UpdateMembershipsParams) error {
	_, err := q.db.Exec(ctx, updateMemberships,
		arg.OrgID,
		arg.Ids,
		arg.StartsAts,
		arg.Annotations,
	)
	return err
}

const upsertTimer = `-- name: UpsertTimer :exec
INSERT INTO timers (org_id, alert_group_id, kind, deadline, created_at, updated_at)
VALUES ($1, $2::bigint, $3, $4, $5, $5)
ON CONFLICT (alert_group_id, kind) WHERE alert_group_id IS NOT NULL
DO UPDATE SET deadline = excluded.deadline, lease_owner = NULL, lease_until = NULL, attempts = 0,
              updated_at = excluded.updated_at
`

type UpsertTimerParams struct {
	OrgID        int64
	AlertGroupID int64
	Kind         string
	Deadline     time.Time
	Now          time.Time
}

// UpsertTimer sets the deadline of an Alert Group's timer of a kind, free of any lease.
func (q *Queries) UpsertTimer(ctx context.Context, arg UpsertTimerParams) error {
	_, err := q.db.Exec(ctx, upsertTimer,
		arg.OrgID,
		arg.AlertGroupID,
		arg.Kind,
		arg.Deadline,
		arg.Now,
	)
	return err
}
