// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Replica struct {
	ReplicaID   string
	Hostname    pgtype.Text
	Version     string
	KeyIds      []string
	StartedAt   time.Time
	RefreshedAt time.Time
}
