// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKeyringState = `-- name: CreateKeyringState :execrows
INSERT INTO keyring_state (active_key_id, activated_at, canary_ciphertext, canary_key_id)
VALUES ($1, $2, $3, $1)
ON CONFLICT (singleton) DO NOTHING
`

type CreateKeyringStateParams struct {
	ActiveKeyID      string
	ActivatedAt      time.Time
	CanaryCiphertext []byte
}

// CreateKeyringState writes the first active key and its canary; it changes nothing when a row exists.
func (q *Queries) CreateKeyringState(ctx context.Context, arg CreateKeyringStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, createKeyringState, arg.ActiveKeyID, arg.ActivatedAt, arg.CanaryCiphertext)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReplica = `-- name: DeleteReplica :exec
DELETE FROM replicas
WHERE replica_id = $1
`

func (q *Queries) DeleteReplica(ctx context.Context, replicaID string) error {
	_, err := q.db.Exec(ctx, deleteReplica, replicaID)
	return err
}

const getActiveKeyID = `-- name: GetActiveKeyID :one
SELECT active_key_id
FROM keyring_state
`

func (q *Queries) GetActiveKeyID(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getActiveKeyID)
	var active_key_id string
	err := row.Scan(&active_key_id)
	return active_key_id, err
}

const getKeyringState = `-- name: GetKeyringState :one

SELECT active_key_id, activated_at, canary_ciphertext, canary_key_id
FROM keyring_state
`

type GetKeyringStateRow struct {
	ActiveKeyID      string
	ActivatedAt      time.Time
	CanaryCiphertext []byte
	CanaryKeyID      string
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
func (q *Queries) GetKeyringState(ctx context.Context) (GetKeyringStateRow, error) {
	row := q.db.QueryRow(ctx, getKeyringState)
	var i GetKeyringStateRow
	err := row.Scan(
		&i.ActiveKeyID,
		&i.ActivatedAt,
		&i.CanaryCiphertext,
		&i.CanaryKeyID,
	)
	return i, err
}

const listLiveReplicas = `-- name: ListLiveReplicas :many
SELECT replica_id, hostname, version, key_ids, started_at, refreshed_at
FROM replicas
WHERE refreshed_at > $1
ORDER BY replica_id
`

func (q *Queries) ListLiveReplicas(ctx context.Context, liveSince time.Time) ([]Replica, error) {
	rows, err := q.db.Query(ctx, listLiveReplicas, liveSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Replica{}
	for rows.Next() {
		var i Replica
		if err := rows.Scan(
			&i.ReplicaID,
			&i.Hostname,
			&i.Version,
			&i.KeyIds,
			&i.StartedAt,
			&i.RefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordReplica = `-- name: RecordReplica :exec
INSERT INTO replicas (replica_id, hostname, version, key_ids, started_at, refreshed_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (replica_id) DO UPDATE
SET key_ids = EXCLUDED.key_ids, refreshed_at = EXCLUDED.refreshed_at
`

type RecordReplicaParams struct {
	ReplicaID   string
	Hostname    pgtype.Text
	Version     string
	KeyIds      []string
	StartedAt   time.Time
	RefreshedAt time.Time
}

// RecordReplica writes the replica's record at start and refreshes it; a pruned record comes back.
func (q *Queries) RecordReplica(ctx context.Context, arg RecordReplicaParams) error {
	_, err := q.db.Exec(ctx, recordReplica,
		arg.ReplicaID,
		arg.Hostname,
		arg.Version,
		arg.KeyIds,
		arg.StartedAt,
		arg.RefreshedAt,
	)
	return err
}
