// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const allowNetwork = `-- name: AllowNetwork :execrows
UPDATE outbound_policies
SET allowed = array_append(allowed, $1::text), version = version + 1, updated_at = $2
WHERE org_id = $3 AND NOT ($1::text = ANY (allowed))
`

type AllowNetworkParams struct {
	Network   string
	UpdatedAt time.Time
	OrgID     int64
}

// AllowNetwork adds a network to the Organization's allowed outbound networks when it is not listed; `muster dev`
// allows loopback this way so that Muster may call the fake servers.
func (q *Queries) AllowNetwork(ctx context.Context, arg AllowNetworkParams) (int64, error) {
	result, err := q.db.Exec(ctx, allowNetwork, arg.Network, arg.UpdatedAt, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const capOIDCSessions = `-- name: CapOIDCSessions :execrows
UPDATE sessions
SET expires_at = least(expires_at, $1::timestamptz)
WHERE org_id = $2 AND user_id = $3 AND method = 'oidc' AND ended_at IS NULL
`

type CapOIDCSessionsParams struct {
	ExpiresAt time.Time
	OrgID     int64
	UserID    int64
}

// CapOIDCSessions bounds the open OIDC sessions of a user who no longer holds an offline token to @expires_at, since no
// background re-check can end them any more.
func (q *Queries) CapOIDCSessions(ctx context.Context, arg CapOIDCSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, capOIDCSessions, arg.ExpiresAt, arg.OrgID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const continueAsOIDCSession = `-- name: ContinueAsOIDCSession :execrows
UPDATE sessions
SET method = 'oidc', idp_mfa = $1, expires_at = least(expires_at, $2::timestamptz)
WHERE org_id = $3 AND id = $4 AND ended_at IS NULL
`

type ContinueAsOIDCSessionParams struct {
	IdpMfa    bool
	ExpiresAt time.Time
	OrgID     int64
	ID        int64
}

// ContinueAsOIDCSession turns the web session that linked an identity into an OIDC session; without an offline token
// it ends at @expires_at at the latest.
func (q *Queries) ContinueAsOIDCSession(ctx context.Context, arg ContinueAsOIDCSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, continueAsOIDCSession,
		arg.IdpMfa,
		arg.ExpiresAt,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createIdentityUser = `-- name: CreateIdentityUser :one
INSERT INTO users (
    org_id, public_id, login, name, email, role, source, status, oidc_issuer, oidc_subject, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, 'oidc', 'active', $7, $8, $9,
    $9
)
RETURNING id
`

type CreateIdentityUserParams struct {
	OrgID     int64
	PublicID  string
	Login     string
	Name      string
	Email     pgtype.Text
	Role      string
	Issuer    pgtype.Text
	Subject   pgtype.Text
	CreatedAt time.Time
}

// CreateIdentityUser creates the account of an OIDC identity at its first sign-in.
func (q *Queries) CreateIdentityUser(ctx context.Context, arg CreateIdentityUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createIdentityUser,
		arg.OrgID,
		arg.PublicID,
		arg.Login,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Issuer,
		arg.Subject,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCheck = `-- name: DeleteCheck :exec
DELETE FROM oidc_checks
WHERE org_id = $1 AND user_id = $2
`

type DeleteCheckParams struct {
	OrgID  int64
	UserID int64
}

// DeleteCheck removes the re-check of a user who holds no offline token any more.
func (q *Queries) DeleteCheck(ctx context.Context, arg DeleteCheckParams) error {
	_, err := q.db.Exec(ctx, deleteCheck, arg.OrgID, arg.UserID)
	return err
}

const dropCheck = `-- name: DropCheck :execrows
DELETE FROM oidc_checks
WHERE org_id = $1 AND user_id = $2 AND lease_owner = $3 AND lease_until > $4::timestamptz
`

type DropCheckParams struct {
	OrgID  int64
	UserID int64
	Owner  pgtype.Text
	Now    time.Time
}

// DropCheck removes a re-check that still holds its lease, when the identity provider refused the user; no row means
// the lease was lost.
func (q *Queries) DropCheck(ctx context.Context, arg DropCheckParams) (int64, error) {
	result, err := q.db.Exec(ctx, dropCheck,
		arg.OrgID,
		arg.UserID,
		arg.Owner,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dueChecks = `-- name: DueChecks :many
SELECT user_id
FROM oidc_checks
WHERE org_id = $1 AND deadline <= $2::timestamptz
    AND (lease_until IS NULL OR lease_until <= $3::timestamptz)
ORDER BY deadline, user_id
LIMIT $4
FOR UPDATE SKIP LOCKED
`

type DueChecksParams struct {
	OrgID     int64
	Due       time.Time
	Now       time.Time
	BatchSize int32
}

// DueChecks locks up to batch_size re-checks that are due on the business clock and not leased on the real clock,
// skipping those another replica holds.
func (q *Queries) DueChecks(ctx context.Context, arg DueChecksParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, dueChecks,
		arg.OrgID,
		arg.Due,
		arg.Now,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endOtherUserSessions = `-- name: EndOtherUserSessions :execrows
UPDATE sessions
SET ended_at = $1::timestamptz, end_reason = $2
WHERE org_id = $3 AND user_id = $4 AND id <> $5 AND ended_at IS NULL
`

type EndOtherUserSessionsParams struct {
	Now       time.Time
	EndReason pgtype.Text
	OrgID     int64
	UserID    int64
	KeepID    int64
}

// EndOtherUserSessions ends every session of a user but the one that made the change, with the reason.
func (q *Queries) EndOtherUserSessions(ctx context.Context, arg EndOtherUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, endOtherUserSessions,
		arg.Now,
		arg.EndReason,
		arg.OrgID,
		arg.UserID,
		arg.KeepID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endUserSessions = `-- name: EndUserSessions :execrows
UPDATE sessions
SET ended_at = $1::timestamptz, end_reason = $2
WHERE org_id = $3 AND user_id = $4 AND ended_at IS NULL
`

type EndUserSessionsParams struct {
	Now       time.Time
	EndReason pgtype.Text
	OrgID     int64
	UserID    int64
}

// EndUserSessions ends every session of a user that has not ended, with the reason.
func (q *Queries) EndUserSessions(ctx context.Context, arg EndUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, endUserSessions,
		arg.Now,
		arg.EndReason,
		arg.OrgID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishCheck = `-- name: FinishCheck :execrows
UPDATE oidc_checks
SET deadline = $1::timestamptz, last_outcome = $2, lease_owner = NULL, lease_until = NULL,
    updated_at = $3::timestamptz
WHERE org_id = $4 AND user_id = $5 AND lease_owner = $6 AND lease_until > $7::timestamptz
`

type FinishCheckParams struct {
	Deadline  time.Time
	Outcome   pgtype.Text
	UpdatedAt time.Time
	OrgID     int64
	UserID    int64
	Owner     pgtype.Text
	Now       time.Time
}

// FinishCheck records the outcome of a re-check that still holds its lease, makes it due again at @deadline and
// releases the lease; no row means the lease was lost and the outcome must not be recorded.
func (q *Queries) FinishCheck(ctx context.Context, arg FinishCheckParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishCheck,
		arg.Deadline,
		arg.Outcome,
		arg.UpdatedAt,
		arg.OrgID,
		arg.UserID,
		arg.Owner,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCheckUser = `-- name: GetCheckUser :one
SELECT u.id, u.public_id, u.name, u.role, u.status, u.oidc_subject, u.oidc_offline_token_ciphertext,
       u.oidc_offline_token_key_id, u.oidc_offline_token_updated_at,
       EXISTS (
           SELECT 1 FROM sessions s
           WHERE s.org_id = u.org_id AND s.user_id = u.id AND s.ended_at IS NULL
               AND s.expires_at > $1::timestamptz AND s.idle_expires_at > $1::timestamptz
       ) AS live_session,
       EXISTS (
           SELECT 1 FROM api_tokens t
           WHERE t.org_id = u.org_id AND t.user_id = u.id AND t.kind = 'personal' AND t.revoked_at IS NULL
               AND (t.expires_at IS NULL OR t.expires_at > $1::timestamptz)
       ) AS usable_token
FROM users u
WHERE u.org_id = $2 AND u.id = $3
`

type GetCheckUserParams struct {
	Now   time.Time
	OrgID int64
	ID    int64
}

type GetCheckUserRow struct {
	ID                         int64
	PublicID                   string
	Name                       string
	Role                       string
	Status                     string
	OidcSubject                pgtype.Text
	OidcOfflineTokenCiphertext []byte
	OidcOfflineTokenKeyID      pgtype.Text
	OidcOfflineTokenUpdatedAt  pgtype.Timestamptz
	LiveSession                bool
	UsableToken                bool
}

// GetCheckUser reads the user of a claimed re-check: the offline token and when it was stored, and whether the user
// has a live session or a Personal access token that has not expired, at @now on the business clock.
func (q *Queries) GetCheckUser(ctx context.Context, arg GetCheckUserParams) (GetCheckUserRow, error) {
	row := q.db.QueryRow(ctx, getCheckUser, arg.Now, arg.OrgID, arg.ID)
	var i GetCheckUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.OidcSubject,
		&i.OidcOfflineTokenCiphertext,
		&i.OidcOfflineTokenKeyID,
		&i.OidcOfflineTokenUpdatedAt,
		&i.LiveSession,
		&i.UsableToken,
	)
	return i, err
}

const getIdentityUser = `-- name: GetIdentityUser :one
SELECT u.id, u.public_id, u.login, u.name, u.role, u.status,
       EXISTS (
           SELECT 1 FROM user_totp t
           WHERE t.org_id = u.org_id AND t.user_id = u.id AND t.enrolled_at IS NOT NULL
       ) AS totp_enrolled,
       o.totp_required
FROM users u
JOIN organizations o ON o.id = u.org_id
WHERE u.org_id = $1 AND u.oidc_issuer = $2 AND u.oidc_subject = $3
`

type GetIdentityUserParams struct {
	OrgID   int64
	Issuer  pgtype.Text
	Subject pgtype.Text
}

type GetIdentityUserRow struct {
	ID           int64
	PublicID     string
	Login        string
	Name         string
	Role         string
	Status       string
	TotpEnrolled bool
	TotpRequired string
}

// GetIdentityUser finds the account that holds an OIDC identity, with whether it has TOTP and the Organization's TOTP
// policy.
func (q *Queries) GetIdentityUser(ctx context.Context, arg GetIdentityUserParams) (GetIdentityUserRow, error) {
	row := q.db.QueryRow(ctx, getIdentityUser, arg.OrgID, arg.Issuer, arg.Subject)
	var i GetIdentityUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Login,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.TotpEnrolled,
		&i.TotpRequired,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one

SELECT org_id, enabled, display_name, issuer_url, client_id, client_secret_ciphertext, client_secret_key_id,
       client_secret_updated_at, client_secret_expires_on, scopes, groups_claim, group_mappings, unmatched_role,
       sync_role, skip_totp_with_idp_mfa, proxy, proxy_password_ciphertext, proxy_password_key_id,
       proxy_password_updated_at, groups_claim_missing_since, version, updated_at
FROM oidc_settings
WHERE org_id = $1
`

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// GetSettings reads the OIDC settings of the Organization, with the state of their Secrets.
func (q *Queries) GetSettings(ctx context.Context, orgID int64) (OidcSetting, error) {
	row := q.db.QueryRow(ctx, getSettings, orgID)
	var i OidcSetting
	err := row.Scan(
		&i.OrgID,
		&i.Enabled,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.ClientSecretKeyID,
		&i.ClientSecretUpdatedAt,
		&i.ClientSecretExpiresOn,
		&i.Scopes,
		&i.GroupsClaim,
		&i.GroupMappings,
		&i.UnmatchedRole,
		&i.SyncRole,
		&i.SkipTotpWithIdpMfa,
		&i.Proxy,
		&i.ProxyPasswordCiphertext,
		&i.ProxyPasswordKeyID,
		&i.ProxyPasswordUpdatedAt,
		&i.GroupsClaimMissingSince,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuthRequest = `-- name: InsertAuthRequest :execrows
INSERT INTO oidc_auth_requests (
    state_hash, org_id, purpose, link_user_id, link_session_id, nonce, code_verifier_ciphertext, code_verifier_key_id,
    return_to, created_at, expires_at
)
SELECT $1, $2, $3, $4, $5, $6,
       $7, $8, $9, $10, $11
WHERE (SELECT count(*) FROM oidc_auth_requests p WHERE p.org_id = $2 AND p.expires_at > $10)
      < $12::bigint
`

type InsertAuthRequestParams struct {
	StateHash              []byte
	OrgID                  int64
	Purpose                string
	LinkUserID             pgtype.Int8
	LinkSessionID          pgtype.Int8
	Nonce                  string
	CodeVerifierCiphertext []byte
	CodeVerifierKeyID      string
	ReturnTo               pgtype.Text
	CreatedAt              time.Time
	ExpiresAt              time.Time
	MaxPending             int64
}

// InsertAuthRequest stores an OIDC redirect in flight, keyed by the hash of its state, unless the Organization already
// has max_pending requests that have not expired: starts need no credentials, so their rows are bounded.
func (q *Queries) InsertAuthRequest(ctx context.Context, arg InsertAuthRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAuthRequest,
		arg.StateHash,
		arg.OrgID,
		arg.Purpose,
		arg.LinkUserID,
		arg.LinkSessionID,
		arg.Nonce,
		arg.CodeVerifierCiphertext,
		arg.CodeVerifierKeyID,
		arg.ReturnTo,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.MaxPending,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDemoSettings = `-- name: InsertDemoSettings :execrows
INSERT INTO oidc_settings (
    org_id, enabled, display_name, issuer_url, client_id, client_secret_ciphertext, client_secret_key_id,
    client_secret_updated_at, scopes, groups_claim, group_mappings, unmatched_role, sync_role, skip_totp_with_idp_mfa,
    version, updated_at
)
VALUES (
    $1, true, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, 'none', true, false, 1, $7
)
ON CONFLICT (org_id) DO NOTHING
`

type InsertDemoSettingsParams struct {
	OrgID                  int64
	DisplayName            pgtype.Text
	IssuerUrl              string
	ClientID               string
	ClientSecretCiphertext []byte
	ClientSecretKeyID      pgtype.Text
	UpdatedAt              pgtype.Timestamptz
	Scopes                 []string
	GroupsClaim            string
	GroupMappings          []byte
}

// InsertDemoSettings stores the demo OIDC configuration of `muster dev` when the Organization has none.
func (q *Queries) InsertDemoSettings(ctx context.Context, arg InsertDemoSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDemoSettings,
		arg.OrgID,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretCiphertext,
		arg.ClientSecretKeyID,
		arg.UpdatedAt,
		arg.Scopes,
		arg.GroupsClaim,
		arg.GroupMappings,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSettings = `-- name: InsertSettings :execrows
INSERT INTO oidc_settings (
    org_id, enabled, display_name, issuer_url, client_id, client_secret_ciphertext, client_secret_key_id,
    client_secret_updated_at, client_secret_expires_on, scopes, groups_claim, group_mappings, unmatched_role, sync_role,
    skip_totp_with_idp_mfa, proxy, proxy_password_ciphertext, proxy_password_key_id, proxy_password_updated_at,
    version, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16,
    $17, $18, $19,
    1, $20
)
ON CONFLICT (org_id) DO NOTHING
`

type InsertSettingsParams struct {
	OrgID                   int64
	Enabled                 bool
	DisplayName             pgtype.Text
	IssuerUrl               string
	ClientID                string
	ClientSecretCiphertext  []byte
	ClientSecretKeyID       pgtype.Text
	ClientSecretUpdatedAt   pgtype.Timestamptz
	ClientSecretExpiresOn   pgtype.Date
	Scopes                  []string
	GroupsClaim             string
	GroupMappings           []byte
	UnmatchedRole           string
	SyncRole                bool
	SkipTotpWithIdpMfa      bool
	Proxy                   []byte
	ProxyPasswordCiphertext []byte
	ProxyPasswordKeyID      pgtype.Text
	ProxyPasswordUpdatedAt  pgtype.Timestamptz
	UpdatedAt               time.Time
}

// InsertSettings stores the first OIDC settings of the Organization; it changes nothing when they exist, so that two
// first saves at once leave one row and the second answers a version mismatch.
func (q *Queries) InsertSettings(ctx context.Context, arg InsertSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSettings,
		arg.OrgID,
		arg.Enabled,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretCiphertext,
		arg.ClientSecretKeyID,
		arg.ClientSecretUpdatedAt,
		arg.ClientSecretExpiresOn,
		arg.Scopes,
		arg.GroupsClaim,
		arg.GroupMappings,
		arg.UnmatchedRole,
		arg.SyncRole,
		arg.SkipTotpWithIdpMfa,
		arg.Proxy,
		arg.ProxyPasswordCiphertext,
		arg.ProxyPasswordKeyID,
		arg.ProxyPasswordUpdatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestKeptAdmin = `-- name: LatestKeptAdmin :one
SELECT a.at, (a.details ->> 'mapped_role')::text AS mapped_role, u.public_id, u.name, u.login, u.role, u.status,
       u.oidc_last_contact_at,
       (SELECT count(*) FROM users c WHERE c.org_id = $1 AND c.role = 'admin' AND c.status = 'active')::bigint
           AS active_admins
FROM audit_log a
JOIN users u ON u.org_id = $1 AND u.public_id = a.resource_public_id
WHERE a.org_id = $1 AND a.action = 'user.role_sync_kept_admin'
ORDER BY a.at DESC, a.id DESC
LIMIT 1
`

type LatestKeptAdminRow struct {
	At                time.Time
	MappedRole        string
	PublicID          string
	Name              string
	Login             string
	Role              string
	Status            string
	OidcLastContactAt pgtype.Timestamptz
	ActiveAdmins      int64
}

// LatestKeptAdmin reads the latest entry in which Role sync kept the last active Admin, with the user it names, that
// user's last OIDC contact and how many active Admins there are now.
func (q *Queries) LatestKeptAdmin(ctx context.Context, orgID int64) (LatestKeptAdminRow, error) {
	row := q.db.QueryRow(ctx, latestKeptAdmin, orgID)
	var i LatestKeptAdminRow
	err := row.Scan(
		&i.At,
		&i.MappedRole,
		&i.PublicID,
		&i.Name,
		&i.Login,
		&i.Role,
		&i.Status,
		&i.OidcLastContactAt,
		&i.ActiveAdmins,
	)
	return i, err
}

const leaseChecks = `-- name: LeaseChecks :exec
UPDATE oidc_checks
SET lease_owner = $1, lease_until = $2::timestamptz
WHERE org_id = $3 AND user_id = ANY ($4::bigint[])
`

type LeaseChecksParams struct {
	Owner      pgtype.Text
	LeaseUntil time.Time
	OrgID      int64
	UserIds    []int64
}

// LeaseChecks leases the re-checks DueChecks locked to this replica until @lease_until on the real clock.
func (q *Queries) LeaseChecks(ctx context.Context, arg LeaseChecksParams) error {
	_, err := q.db.Exec(ctx, leaseChecks,
		arg.Owner,
		arg.LeaseUntil,
		arg.OrgID,
		arg.UserIds,
	)
	return err
}

const linkIdentity = `-- name: LinkIdentity :execrows
UPDATE users
SET oidc_issuer = $1, oidc_subject = $2, password_hash = NULL, oidc_last_contact_at = $3::timestamptz,
    oidc_refused_at = NULL, updated_at = $3::timestamptz, version = version + 1
WHERE org_id = $4 AND id = $5 AND status = 'active' AND password_hash IS NOT NULL AND oidc_subject IS NULL
`

type LinkIdentityParams struct {
	Issuer  pgtype.Text
	Subject pgtype.Text
	Now     time.Time
	OrgID   int64
	ID      int64
}

// LinkIdentity adds the OIDC identity to an active account with a password and wipes the password in the same update,
// so that the account never holds both (users_one_credential_check).
func (q *Queries) LinkIdentity(ctx context.Context, arg LinkIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkIdentity,
		arg.Issuer,
		arg.Subject,
		arg.Now,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockActiveAdmins = `-- name: LockActiveAdmins :many
SELECT id
FROM users
WHERE org_id = $1 AND role = 'admin' AND status = 'active'
ORDER BY id
FOR NO KEY UPDATE
`

// LockActiveAdmins locks the rows of the active Admins, as the last_admin check of user administration does, before
// the row of the user whose Role sync may lower an Admin.
func (q *Queries) LockActiveAdmins(ctx context.Context, orgID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockActiveAdmins, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCheckUser = `-- name: LockCheckUser :one
SELECT role, status, oidc_offline_token_updated_at
FROM users
WHERE org_id = $1 AND id = $2
FOR NO KEY UPDATE
`

type LockCheckUserParams struct {
	OrgID int64
	ID    int64
}

type LockCheckUserRow struct {
	Role                      string
	Status                    string
	OidcOfflineTokenUpdatedAt pgtype.Timestamptz
}

// LockCheckUser locks the user whose re-check ends and reads the offline token it holds now.
func (q *Queries) LockCheckUser(ctx context.Context, arg LockCheckUserParams) (LockCheckUserRow, error) {
	row := q.db.QueryRow(ctx, lockCheckUser, arg.OrgID, arg.ID)
	var i LockCheckUserRow
	err := row.Scan(&i.Role, &i.Status, &i.OidcOfflineTokenUpdatedAt)
	return i, err
}

const lockLinkUser = `-- name: LockLinkUser :one
SELECT id, public_id, name, status, (password_hash IS NOT NULL)::boolean AS has_password,
       (oidc_subject IS NOT NULL)::boolean AS has_identity
FROM users
WHERE org_id = $1 AND id = $2
FOR NO KEY UPDATE
`

type LockLinkUserParams struct {
	OrgID int64
	ID    int64
}

type LockLinkUserRow struct {
	ID          int64
	PublicID    string
	Name        string
	Status      string
	HasPassword bool
	HasIdentity bool
}

// LockLinkUser locks the account a link adds the identity to and reads whether it can take one: active, with a
// password and without an identity.
func (q *Queries) LockLinkUser(ctx context.Context, arg LockLinkUserParams) (LockLinkUserRow, error) {
	row := q.db.QueryRow(ctx, lockLinkUser, arg.OrgID, arg.ID)
	var i LockLinkUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Status,
		&i.HasPassword,
		&i.HasIdentity,
	)
	return i, err
}

const lockSettings = `-- name: LockSettings :one
SELECT version
FROM oidc_settings
WHERE org_id = $1
FOR UPDATE
`

// LockSettings locks the settings row until the transaction ends and returns its version.
func (q *Queries) LockSettings(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockSettings, orgID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const lockUser = `-- name: LockUser :one
SELECT role, status
FROM users
WHERE org_id = $1 AND id = $2
FOR NO KEY UPDATE
`

type LockUserParams struct {
	OrgID int64
	ID    int64
}

type LockUserRow struct {
	Role   string
	Status string
}

// LockUser locks the user whose Role sync runs and reads the Role and status it has now.
func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) (LockUserRow, error) {
	row := q.db.QueryRow(ctx, lockUser, arg.OrgID, arg.ID)
	var i LockUserRow
	err := row.Scan(&i.Role, &i.Status)
	return i, err
}

const loginTaken = `-- name: LoginTaken :one
SELECT EXISTS (SELECT 1 FROM users WHERE org_id = $1 AND lower(login) = lower($2))::boolean AS taken
`

type LoginTakenParams struct {
	OrgID int64
	Login string
}

// LoginTaken reports whether an account has the login, compared lowercased.
func (q *Queries) LoginTaken(ctx context.Context, arg LoginTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, loginTaken, arg.OrgID, arg.Login)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const pruneAuthRequests = `-- name: PruneAuthRequests :execrows
DELETE FROM oidc_auth_requests r
WHERE r.org_id = $1 AND r.state_hash IN (
    SELECT o.state_hash FROM oidc_auth_requests o
    WHERE o.org_id = $1 AND o.expires_at < $2::timestamptz
    ORDER BY o.state_hash
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
`

type PruneAuthRequestsParams struct {
	OrgID     int64
	Before    time.Time
	BatchSize int32
}

// PruneAuthRequests deletes up to batch_size requests that expired before @before. A request being taken is skipped
// and goes at the next run.
func (q *Queries) PruneAuthRequests(ctx context.Context, arg PruneAuthRequestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAuthRequests, arg.OrgID, arg.Before, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordContact = `-- name: RecordContact :exec
UPDATE users
SET oidc_last_contact_at = $1::timestamptz, oidc_refused_at = NULL
WHERE org_id = $2 AND id = $3
`

type RecordContactParams struct {
	Now   time.Time
	OrgID int64
	ID    int64
}

// RecordContact records a successful contact with the identity provider and lifts an earlier refusal.
func (q *Queries) RecordContact(ctx context.Context, arg RecordContactParams) error {
	_, err := q.db.Exec(ctx, recordContact, arg.Now, arg.OrgID, arg.ID)
	return err
}

const refuseUser = `-- name: RefuseUser :exec
UPDATE users
SET oidc_refused_at = $1::timestamptz, oidc_offline_token_ciphertext = NULL, oidc_offline_token_key_id = NULL,
    oidc_offline_token_updated_at = NULL
WHERE org_id = $2 AND id = $3
`

type RefuseUserParams struct {
	Now   time.Time
	OrgID int64
	ID    int64
}

// RefuseUser records that the identity provider refused the user at a re-check and wipes the offline token.
func (q *Queries) RefuseUser(ctx context.Context, arg RefuseUserParams) error {
	_, err := q.db.Exec(ctx, refuseUser, arg.Now, arg.OrgID, arg.ID)
	return err
}

const scheduleCheck = `-- name: ScheduleCheck :exec
INSERT INTO oidc_checks (user_id, org_id, deadline, created_at, updated_at)
VALUES ($1, $2, $3::timestamptz, $4::timestamptz, $4::timestamptz)
ON CONFLICT (user_id) DO UPDATE
SET deadline = excluded.deadline, lease_owner = NULL, lease_until = NULL, last_outcome = NULL,
    updated_at = excluded.updated_at
`

type ScheduleCheckParams struct {
	UserID   int64
	OrgID    int64
	Deadline time.Time
	Now      time.Time
}

// ScheduleCheck makes the re-check of a user who holds an offline token due at @deadline; a re-check in flight for
// the token it replaced loses its lease, so that its outcome is not recorded.
func (q *Queries) ScheduleCheck(ctx context.Context, arg ScheduleCheckParams) error {
	_, err := q.db.Exec(ctx, scheduleCheck,
		arg.UserID,
		arg.OrgID,
		arg.Deadline,
		arg.Now,
	)
	return err
}

const setGroupsClaimMissing = `-- name: SetGroupsClaimMissing :exec
UPDATE oidc_settings
SET groups_claim_missing_since = CASE
        WHEN $1::timestamptz IS NULL THEN NULL
        ELSE coalesce(groups_claim_missing_since, $1::timestamptz)
    END
WHERE org_id = $2
`

type SetGroupsClaimMissingParams struct {
	Since pgtype.Timestamptz
	OrgID int64
}

// SetGroupsClaimMissing records since when the groups claim was found missing, or clears it with null; the warning is
// not a configured value, so the version stays.
func (q *Queries) SetGroupsClaimMissing(ctx context.Context, arg SetGroupsClaimMissingParams) error {
	_, err := q.db.Exec(ctx, setGroupsClaimMissing, arg.Since, arg.OrgID)
	return err
}

const setRole = `-- name: SetRole :execrows
UPDATE users
SET role = $1, updated_at = $2::timestamptz, version = version + 1
WHERE org_id = $3 AND id = $4 AND status = 'active'
`

type SetRoleParams struct {
	Role  string
	Now   time.Time
	OrgID int64
	ID    int64
}

// SetRole gives a user the Role the identity provider maps them to.
func (q *Queries) SetRole(ctx context.Context, arg SetRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRole,
		arg.Role,
		arg.Now,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storeOfflineToken = `-- name: StoreOfflineToken :exec
UPDATE users
SET oidc_offline_token_ciphertext = $1, oidc_offline_token_key_id = $2,
    oidc_offline_token_updated_at = $3::timestamptz
WHERE org_id = $4 AND id = $5
`

type StoreOfflineTokenParams struct {
	Ciphertext []byte
	KeyID      pgtype.Text
	Now        time.Time
	OrgID      int64
	ID         int64
}

// StoreOfflineToken keeps the offline token the identity provider granted, encrypted, in place of the previous one.
func (q *Queries) StoreOfflineToken(ctx context.Context, arg StoreOfflineTokenParams) error {
	_, err := q.db.Exec(ctx, storeOfflineToken,
		arg.Ciphertext,
		arg.KeyID,
		arg.Now,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const takeAuthRequest = `-- name: TakeAuthRequest :one
DELETE FROM oidc_auth_requests
WHERE org_id = $1 AND state_hash = $2
RETURNING purpose, link_user_id, link_session_id, nonce, code_verifier_ciphertext, code_verifier_key_id, return_to,
    expires_at
`

type TakeAuthRequestParams struct {
	OrgID     int64
	StateHash []byte
}

type TakeAuthRequestRow struct {
	Purpose                string
	LinkUserID             pgtype.Int8
	LinkSessionID          pgtype.Int8
	Nonce                  string
	CodeVerifierCiphertext []byte
	CodeVerifierKeyID      string
	ReturnTo               pgtype.Text
	ExpiresAt              time.Time
}

// TakeAuthRequest removes and returns the request of a state, so that a callback uses it once.
func (q *Queries) TakeAuthRequest(ctx context.Context, arg TakeAuthRequestParams) (TakeAuthRequestRow, error) {
	row := q.db.QueryRow(ctx, takeAuthRequest, arg.OrgID, arg.StateHash)
	var i TakeAuthRequestRow
	err := row.Scan(
		&i.Purpose,
		&i.LinkUserID,
		&i.LinkSessionID,
		&i.Nonce,
		&i.CodeVerifierCiphertext,
		&i.CodeVerifierKeyID,
		&i.ReturnTo,
		&i.ExpiresAt,
	)
	return i, err
}

const takeLinkRequest = `-- name: TakeLinkRequest :one
DELETE FROM oidc_auth_requests
WHERE org_id = $1 AND state_hash = $2 AND purpose = 'link' AND link_session_id = $3
    AND link_user_id = $4
RETURNING nonce, code_verifier_ciphertext, code_verifier_key_id, expires_at
`

type TakeLinkRequestParams struct {
	OrgID     int64
	StateHash []byte
	SessionID pgtype.Int8
	UserID    pgtype.Int8
}

type TakeLinkRequestRow struct {
	Nonce                  string
	CodeVerifierCiphertext []byte
	CodeVerifierKeyID      string
	ExpiresAt              time.Time
}

// TakeLinkRequest removes and returns the link request of a state only for the web session that started it, so that
// a callback in another session neither uses nor spends it.
func (q *Queries) TakeLinkRequest(ctx context.Context, arg TakeLinkRequestParams) (TakeLinkRequestRow, error) {
	row := q.db.QueryRow(ctx, takeLinkRequest,
		arg.OrgID,
		arg.StateHash,
		arg.SessionID,
		arg.UserID,
	)
	var i TakeLinkRequestRow
	err := row.Scan(
		&i.Nonce,
		&i.CodeVerifierCiphertext,
		&i.CodeVerifierKeyID,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :execrows
UPDATE oidc_settings
SET enabled = $1, display_name = $2, issuer_url = $3, client_id = $4,
    client_secret_ciphertext = $5,
    client_secret_key_id = $6,
    client_secret_updated_at = $7,
    client_secret_expires_on = $8, scopes = $9, groups_claim = $10,
    group_mappings = $11, unmatched_role = $12, sync_role = $13,
    skip_totp_with_idp_mfa = $14, proxy = $15,
    proxy_password_ciphertext = $16,
    proxy_password_key_id = $17,
    proxy_password_updated_at = $18,
    groups_claim_missing_since = CASE
        WHEN groups_claim = $10 AND issuer_url = $3 THEN groups_claim_missing_since
    END,
    version = version + 1, updated_at = $19
WHERE org_id = $20 AND version = $21
`

type UpdateSettingsParams struct {
	Enabled                 bool
	DisplayName             pgtype.Text
	IssuerUrl               string
	ClientID                string
	ClientSecretCiphertext  []byte
	ClientSecretKeyID       pgtype.Text
	ClientSecretUpdatedAt   pgtype.Timestamptz
	ClientSecretExpiresOn   pgtype.Date
	Scopes                  []string
	GroupsClaim             string
	GroupMappings           []byte
	UnmatchedRole           string
	SyncRole                bool
	SkipTotpWithIdpMfa      bool
	Proxy                   []byte
	ProxyPasswordCiphertext []byte
	ProxyPasswordKeyID      pgtype.Text
	ProxyPasswordUpdatedAt  pgtype.Timestamptz
	UpdatedAt               time.Time
	OrgID                   int64
	Version                 int64
}

// UpdateSettings replaces the settings at the version that was read.
func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSettings,
		arg.Enabled,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretCiphertext,
		arg.ClientSecretKeyID,
		arg.ClientSecretUpdatedAt,
		arg.ClientSecretExpiresOn,
		arg.Scopes,
		arg.GroupsClaim,
		arg.GroupMappings,
		arg.UnmatchedRole,
		arg.SyncRole,
		arg.SkipTotpWithIdpMfa,
		arg.Proxy,
		arg.ProxyPasswordCiphertext,
		arg.ProxyPasswordKeyID,
		arg.ProxyPasswordUpdatedAt,
		arg.UpdatedAt,
		arg.OrgID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wipeOfflineToken = `-- name: WipeOfflineToken :exec
UPDATE users
SET oidc_offline_token_ciphertext = NULL, oidc_offline_token_key_id = NULL, oidc_offline_token_updated_at = NULL
WHERE org_id = $1 AND id = $2
`

type WipeOfflineTokenParams struct {
	OrgID int64
	ID    int64
}

// WipeOfflineToken removes the offline token of a user whose sign-in granted none.
func (q *Queries) WipeOfflineToken(ctx context.Context, arg WipeOfflineTokenParams) error {
	_, err := q.db.Exec(ctx, wipeOfflineToken, arg.OrgID, arg.ID)
	return err
}
