// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const allowNetwork = `-- name: AllowNetwork :execrows
UPDATE outbound_policies
SET allowed = array_append(allowed, $1::text), version = version + 1, updated_at = $2
WHERE org_id = $3 AND NOT ($1::text = ANY (allowed))
`

type AllowNetworkParams struct {
	Network   string
	UpdatedAt time.Time
	OrgID     int64
}

// AllowNetwork adds a network to the Organization's allowed outbound networks when it is not listed; `muster dev`
// allows loopback this way so that Muster may call the fake servers.
func (q *Queries) AllowNetwork(ctx context.Context, arg AllowNetworkParams) (int64, error) {
	result, err := q.db.Exec(ctx, allowNetwork, arg.Network, arg.UpdatedAt, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createIdentityUser = `-- name: CreateIdentityUser :one
INSERT INTO users (
    org_id, public_id, login, name, email, role, source, status, oidc_issuer, oidc_subject, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, 'oidc', 'active', $7, $8, $9,
    $9
)
RETURNING id
`

type CreateIdentityUserParams struct {
	OrgID     int64
	PublicID  string
	Login     string
	Name      string
	Email     pgtype.Text
	Role      string
	Issuer    pgtype.Text
	Subject   pgtype.Text
	CreatedAt time.Time
}

// CreateIdentityUser creates the account of an OIDC identity at its first sign-in.
func (q *Queries) CreateIdentityUser(ctx context.Context, arg CreateIdentityUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createIdentityUser,
		arg.OrgID,
		arg.PublicID,
		arg.Login,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Issuer,
		arg.Subject,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const endUserSessions = `-- name: EndUserSessions :execrows
UPDATE sessions
SET ended_at = $1::timestamptz, end_reason = $2
WHERE org_id = $3 AND user_id = $4 AND ended_at IS NULL
`

type EndUserSessionsParams struct {
	Now       time.Time
	EndReason pgtype.Text
	OrgID     int64
	UserID    int64
}

// EndUserSessions ends every session of a user that has not ended, with the reason.
func (q *Queries) EndUserSessions(ctx context.Context, arg EndUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, endUserSessions,
		arg.Now,
		arg.EndReason,
		arg.OrgID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdentityUser = `-- name: GetIdentityUser :one
SELECT u.id, u.public_id, u.login, u.name, u.role, u.status,
       EXISTS (
           SELECT 1 FROM user_totp t
           WHERE t.org_id = u.org_id AND t.user_id = u.id AND t.enrolled_at IS NOT NULL
       ) AS totp_enrolled,
       o.totp_required
FROM users u
JOIN organizations o ON o.id = u.org_id
WHERE u.org_id = $1 AND u.oidc_issuer = $2 AND u.oidc_subject = $3
`

type GetIdentityUserParams struct {
	OrgID   int64
	Issuer  pgtype.Text
	Subject pgtype.Text
}

type GetIdentityUserRow struct {
	ID           int64
	PublicID     string
	Login        string
	Name         string
	Role         string
	Status       string
	TotpEnrolled bool
	TotpRequired string
}

// GetIdentityUser finds the account that holds an OIDC identity, with whether it has TOTP and the Organization's TOTP
// policy.
func (q *Queries) GetIdentityUser(ctx context.Context, arg GetIdentityUserParams) (GetIdentityUserRow, error) {
	row := q.db.QueryRow(ctx, getIdentityUser, arg.OrgID, arg.Issuer, arg.Subject)
	var i GetIdentityUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Login,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.TotpEnrolled,
		&i.TotpRequired,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one

SELECT org_id, enabled, display_name, issuer_url, client_id, client_secret_ciphertext, client_secret_key_id,
       client_secret_updated_at, client_secret_expires_on, scopes, groups_claim, group_mappings, unmatched_role,
       sync_role, skip_totp_with_idp_mfa, proxy, proxy_password_ciphertext, proxy_password_key_id,
       proxy_password_updated_at, groups_claim_missing_since, version, updated_at
FROM oidc_settings
WHERE org_id = $1
`

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// GetSettings reads the OIDC settings of the Organization, with the state of their Secrets.
func (q *Queries) GetSettings(ctx context.Context, orgID int64) (OidcSetting, error) {
	row := q.db.QueryRow(ctx, getSettings, orgID)
	var i OidcSetting
	err := row.Scan(
		&i.OrgID,
		&i.Enabled,
		&i.DisplayName,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.ClientSecretKeyID,
		&i.ClientSecretUpdatedAt,
		&i.ClientSecretExpiresOn,
		&i.Scopes,
		&i.GroupsClaim,
		&i.GroupMappings,
		&i.UnmatchedRole,
		&i.SyncRole,
		&i.SkipTotpWithIdpMfa,
		&i.Proxy,
		&i.ProxyPasswordCiphertext,
		&i.ProxyPasswordKeyID,
		&i.ProxyPasswordUpdatedAt,
		&i.GroupsClaimMissingSince,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuthRequest = `-- name: InsertAuthRequest :execrows
INSERT INTO oidc_auth_requests (
    state_hash, org_id, purpose, link_user_id, link_session_id, nonce, code_verifier_ciphertext, code_verifier_key_id,
    return_to, created_at, expires_at
)
SELECT $1, $2, $3, $4, $5, $6,
       $7, $8, $9, $10, $11
WHERE (SELECT count(*) FROM oidc_auth_requests p WHERE p.org_id = $2 AND p.expires_at > $10)
      < $12::bigint
`

type InsertAuthRequestParams struct {
	StateHash              []byte
	OrgID                  int64
	Purpose                string
	LinkUserID             pgtype.Int8
	LinkSessionID          pgtype.Int8
	Nonce                  string
	CodeVerifierCiphertext []byte
	CodeVerifierKeyID      string
	ReturnTo               pgtype.Text
	CreatedAt              time.Time
	ExpiresAt              time.Time
	MaxPending             int64
}

// InsertAuthRequest stores an OIDC redirect in flight, keyed by the hash of its state, unless the Organization already
// has max_pending requests that have not expired: starts need no credentials, so their rows are bounded.
func (q *Queries) InsertAuthRequest(ctx context.Context, arg InsertAuthRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAuthRequest,
		arg.StateHash,
		arg.OrgID,
		arg.Purpose,
		arg.LinkUserID,
		arg.LinkSessionID,
		arg.Nonce,
		arg.CodeVerifierCiphertext,
		arg.CodeVerifierKeyID,
		arg.ReturnTo,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.MaxPending,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDemoSettings = `-- name: InsertDemoSettings :execrows
INSERT INTO oidc_settings (
    org_id, enabled, display_name, issuer_url, client_id, client_secret_ciphertext, client_secret_key_id,
    client_secret_updated_at, scopes, groups_claim, group_mappings, unmatched_role, sync_role, skip_totp_with_idp_mfa,
    version, updated_at
)
VALUES (
    $1, true, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, 'none', true, false, 1, $7
)
ON CONFLICT (org_id) DO NOTHING
`

type InsertDemoSettingsParams struct {
	OrgID                  int64
	DisplayName            pgtype.Text
	IssuerUrl              string
	ClientID               string
	ClientSecretCiphertext []byte
	ClientSecretKeyID      pgtype.Text
	UpdatedAt              pgtype.Timestamptz
	Scopes                 []string
	GroupsClaim            string
	GroupMappings          []byte
}

// InsertDemoSettings stores the demo OIDC configuration of `muster dev` when the Organization has none.
func (q *Queries) InsertDemoSettings(ctx context.Context, arg InsertDemoSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDemoSettings,
		arg.OrgID,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretCiphertext,
		arg.ClientSecretKeyID,
		arg.UpdatedAt,
		arg.Scopes,
		arg.GroupsClaim,
		arg.GroupMappings,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSettings = `-- name: InsertSettings :execrows
INSERT INTO oidc_settings (
    org_id, enabled, display_name, issuer_url, client_id, client_secret_ciphertext, client_secret_key_id,
    client_secret_updated_at, client_secret_expires_on, scopes, groups_claim, group_mappings, unmatched_role, sync_role,
    skip_totp_with_idp_mfa, proxy, proxy_password_ciphertext, proxy_password_key_id, proxy_password_updated_at,
    version, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16,
    $17, $18, $19,
    1, $20
)
ON CONFLICT (org_id) DO NOTHING
`

type InsertSettingsParams struct {
	OrgID                   int64
	Enabled                 bool
	DisplayName             pgtype.Text
	IssuerUrl               string
	ClientID                string
	ClientSecretCiphertext  []byte
	ClientSecretKeyID       pgtype.Text
	ClientSecretUpdatedAt   pgtype.Timestamptz
	ClientSecretExpiresOn   pgtype.Date
	Scopes                  []string
	GroupsClaim             string
	GroupMappings           []byte
	UnmatchedRole           string
	SyncRole                bool
	SkipTotpWithIdpMfa      bool
	Proxy                   []byte
	ProxyPasswordCiphertext []byte
	ProxyPasswordKeyID      pgtype.Text
	ProxyPasswordUpdatedAt  pgtype.Timestamptz
	UpdatedAt               time.Time
}

// InsertSettings stores the first OIDC settings of the Organization; it changes nothing when they exist, so that two
// first saves at once leave one row and the second answers a version mismatch.
func (q *Queries) InsertSettings(ctx context.Context, arg InsertSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSettings,
		arg.OrgID,
		arg.Enabled,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretCiphertext,
		arg.ClientSecretKeyID,
		arg.ClientSecretUpdatedAt,
		arg.ClientSecretExpiresOn,
		arg.Scopes,
		arg.GroupsClaim,
		arg.GroupMappings,
		arg.UnmatchedRole,
		arg.SyncRole,
		arg.SkipTotpWithIdpMfa,
		arg.Proxy,
		arg.ProxyPasswordCiphertext,
		arg.ProxyPasswordKeyID,
		arg.ProxyPasswordUpdatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestKeptAdmin = `-- name: LatestKeptAdmin :one
SELECT a.at, (a.details ->> 'mapped_role')::text AS mapped_role, u.public_id, u.name, u.login, u.role, u.status,
       u.oidc_last_contact_at,
       (SELECT count(*) FROM users c WHERE c.org_id = $1 AND c.role = 'admin' AND c.status = 'active')::bigint
           AS active_admins
FROM audit_log a
JOIN users u ON u.org_id = $1 AND u.public_id = a.resource_public_id
WHERE a.org_id = $1 AND a.action = 'user.role_sync_kept_admin'
ORDER BY a.at DESC, a.id DESC
LIMIT 1
`

type LatestKeptAdminRow struct {
	At                time.Time
	MappedRole        string
	PublicID          string
	Name              string
	Login             string
	Role              string
	Status            string
	OidcLastContactAt pgtype.Timestamptz
	ActiveAdmins      int64
}

// LatestKeptAdmin reads the latest entry in which Role sync kept the last active Admin, with the user it names, that
// user's last OIDC contact and how many active Admins there are now.
func (q *Queries) LatestKeptAdmin(ctx context.Context, orgID int64) (LatestKeptAdminRow, error) {
	row := q.db.QueryRow(ctx, latestKeptAdmin, orgID)
	var i LatestKeptAdminRow
	err := row.Scan(
		&i.At,
		&i.MappedRole,
		&i.PublicID,
		&i.Name,
		&i.Login,
		&i.Role,
		&i.Status,
		&i.OidcLastContactAt,
		&i.ActiveAdmins,
	)
	return i, err
}

const lockActiveAdmins = `-- name: LockActiveAdmins :many
SELECT id
FROM users
WHERE org_id = $1 AND role = 'admin' AND status = 'active'
ORDER BY id
FOR NO KEY UPDATE
`

// LockActiveAdmins locks the rows of the active Admins, as the last_admin check of user administration does, before
// the row of the user whose Role sync may lower an Admin.
func (q *Queries) LockActiveAdmins(ctx context.Context, orgID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockActiveAdmins, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSettings = `-- name: LockSettings :one
SELECT version
FROM oidc_settings
WHERE org_id = $1
FOR UPDATE
`

// LockSettings locks the settings row until the transaction ends and returns its version.
func (q *Queries) LockSettings(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockSettings, orgID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const lockUser = `-- name: LockUser :one
SELECT role, status
FROM users
WHERE org_id = $1 AND id = $2
FOR NO KEY UPDATE
`

type LockUserParams struct {
	OrgID int64
	ID    int64
}

type LockUserRow struct {
	Role   string
	Status string
}

// LockUser locks the user whose Role sync runs and reads the Role and status it has now.
func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) (LockUserRow, error) {
	row := q.db.QueryRow(ctx, lockUser, arg.OrgID, arg.ID)
	var i LockUserRow
	err := row.Scan(&i.Role, &i.Status)
	return i, err
}

const loginTaken = `-- name: LoginTaken :one
SELECT EXISTS (SELECT 1 FROM users WHERE org_id = $1 AND lower(login) = lower($2))::boolean AS taken
`

type LoginTakenParams struct {
	OrgID int64
	Login string
}

// LoginTaken reports whether an account has the login, compared lowercased.
func (q *Queries) LoginTaken(ctx context.Context, arg LoginTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, loginTaken, arg.OrgID, arg.Login)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const pruneAuthRequests = `-- name: PruneAuthRequests :execrows
DELETE FROM oidc_auth_requests r
WHERE r.org_id = $1 AND r.state_hash IN (
    SELECT o.state_hash FROM oidc_auth_requests o
    WHERE o.org_id = $1 AND o.expires_at < $2::timestamptz
    ORDER BY o.state_hash
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
`

type PruneAuthRequestsParams struct {
	OrgID     int64
	Before    time.Time
	BatchSize int32
}

// PruneAuthRequests deletes up to batch_size requests that expired before @before. A request being taken is skipped
// and goes at the next run.
func (q *Queries) PruneAuthRequests(ctx context.Context, arg PruneAuthRequestsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAuthRequests, arg.OrgID, arg.Before, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordContact = `-- name: RecordContact :exec
UPDATE users
SET oidc_last_contact_at = $1::timestamptz, oidc_refused_at = NULL
WHERE org_id = $2 AND id = $3
`

type RecordContactParams struct {
	Now   time.Time
	OrgID int64
	ID    int64
}

// RecordContact records a successful contact with the identity provider and lifts an earlier refusal.
func (q *Queries) RecordContact(ctx context.Context, arg RecordContactParams) error {
	_, err := q.db.Exec(ctx, recordContact, arg.Now, arg.OrgID, arg.ID)
	return err
}

const setGroupsClaimMissing = `-- name: SetGroupsClaimMissing :exec
UPDATE oidc_settings
SET groups_claim_missing_since = CASE
        WHEN $1::timestamptz IS NULL THEN NULL
        ELSE coalesce(groups_claim_missing_since, $1::timestamptz)
    END
WHERE org_id = $2
`

type SetGroupsClaimMissingParams struct {
	Since pgtype.Timestamptz
	OrgID int64
}

// SetGroupsClaimMissing records since when the groups claim was found missing, or clears it with null; the warning is
// not a configured value, so the version stays.
func (q *Queries) SetGroupsClaimMissing(ctx context.Context, arg SetGroupsClaimMissingParams) error {
	_, err := q.db.Exec(ctx, setGroupsClaimMissing, arg.Since, arg.OrgID)
	return err
}

const setRole = `-- name: SetRole :execrows
UPDATE users
SET role = $1, updated_at = $2::timestamptz, version = version + 1
WHERE org_id = $3 AND id = $4 AND status = 'active'
`

type SetRoleParams struct {
	Role  string
	Now   time.Time
	OrgID int64
	ID    int64
}

// SetRole gives a user the Role the identity provider maps them to.
func (q *Queries) SetRole(ctx context.Context, arg SetRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRole,
		arg.Role,
		arg.Now,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeAuthRequest = `-- name: TakeAuthRequest :one
DELETE FROM oidc_auth_requests
WHERE org_id = $1 AND state_hash = $2
RETURNING purpose, link_user_id, link_session_id, nonce, code_verifier_ciphertext, code_verifier_key_id, return_to,
    expires_at
`

type TakeAuthRequestParams struct {
	OrgID     int64
	StateHash []byte
}

type TakeAuthRequestRow struct {
	Purpose                string
	LinkUserID             pgtype.Int8
	LinkSessionID          pgtype.Int8
	Nonce                  string
	CodeVerifierCiphertext []byte
	CodeVerifierKeyID      string
	ReturnTo               pgtype.Text
	ExpiresAt              time.Time
}

// TakeAuthRequest removes and returns the request of a state, so that a callback uses it once.
func (q *Queries) TakeAuthRequest(ctx context.Context, arg TakeAuthRequestParams) (TakeAuthRequestRow, error) {
	row := q.db.QueryRow(ctx, takeAuthRequest, arg.OrgID, arg.StateHash)
	var i TakeAuthRequestRow
	err := row.Scan(
		&i.Purpose,
		&i.LinkUserID,
		&i.LinkSessionID,
		&i.Nonce,
		&i.CodeVerifierCiphertext,
		&i.CodeVerifierKeyID,
		&i.ReturnTo,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :execrows
UPDATE oidc_settings
SET enabled = $1, display_name = $2, issuer_url = $3, client_id = $4,
    client_secret_ciphertext = $5,
    client_secret_key_id = $6,
    client_secret_updated_at = $7,
    client_secret_expires_on = $8, scopes = $9, groups_claim = $10,
    group_mappings = $11, unmatched_role = $12, sync_role = $13,
    skip_totp_with_idp_mfa = $14, proxy = $15,
    proxy_password_ciphertext = $16,
    proxy_password_key_id = $17,
    proxy_password_updated_at = $18,
    groups_claim_missing_since = CASE
        WHEN groups_claim = $10 AND issuer_url = $3 THEN groups_claim_missing_since
    END,
    version = version + 1, updated_at = $19
WHERE org_id = $20 AND version = $21
`

type UpdateSettingsParams struct {
	Enabled                 bool
	DisplayName             pgtype.Text
	IssuerUrl               string
	ClientID                string
	ClientSecretCiphertext  []byte
	ClientSecretKeyID       pgtype.Text
	ClientSecretUpdatedAt   pgtype.Timestamptz
	ClientSecretExpiresOn   pgtype.Date
	Scopes                  []string
	GroupsClaim             string
	GroupMappings           []byte
	UnmatchedRole           string
	SyncRole                bool
	SkipTotpWithIdpMfa      bool
	Proxy                   []byte
	ProxyPasswordCiphertext []byte
	ProxyPasswordKeyID      pgtype.Text
	ProxyPasswordUpdatedAt  pgtype.Timestamptz
	UpdatedAt               time.Time
	OrgID                   int64
	Version                 int64
}

// UpdateSettings replaces the settings at the version that was read.
func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSettings,
		arg.Enabled,
		arg.DisplayName,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretCiphertext,
		arg.ClientSecretKeyID,
		arg.ClientSecretUpdatedAt,
		arg.ClientSecretExpiresOn,
		arg.Scopes,
		arg.GroupsClaim,
		arg.GroupMappings,
		arg.UnmatchedRole,
		arg.SyncRole,
		arg.SkipTotpWithIdpMfa,
		arg.Proxy,
		arg.ProxyPasswordCiphertext,
		arg.ProxyPasswordKeyID,
		arg.ProxyPasswordUpdatedAt,
		arg.UpdatedAt,
		arg.OrgID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
