// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockSignIn = `-- name: BlockSignIn :exec
UPDATE sign_in_throttles
SET blocked_until = $1
WHERE org_id = $2 AND subject_kind = $3 AND subject = $4
`

type BlockSignInParams struct {
	BlockedUntil pgtype.Timestamptz
	OrgID        int64
	SubjectKind  string
	Subject      string
}

func (q *Queries) BlockSignIn(ctx context.Context, arg BlockSignInParams) error {
	_, err := q.db.Exec(ctx, blockSignIn,
		arg.BlockedUntil,
		arg.OrgID,
		arg.SubjectKind,
		arg.Subject,
	)
	return err
}

const completeSecondFactor = `-- name: CompleteSecondFactor :execrows
UPDATE sessions
SET state = 'active'
WHERE org_id = $1 AND id = $2 AND state = 'totp_required' AND ended_at IS NULL
`

type CompleteSecondFactorParams struct {
	OrgID int64
	ID    int64
}

// CompleteSecondFactor makes a session that waited for the TOTP code active.
func (q *Queries) CompleteSecondFactor(ctx context.Context, arg CompleteSecondFactorParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeSecondFactor, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    org_id, public_id, user_id, token_hash, state, method, idp_mfa, address, user_agent, created_at, last_used_at,
    idle_expires_at, expires_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $10, $11, $12
)
RETURNING id
`

type CreateSessionParams struct {
	OrgID         int64
	PublicID      string
	UserID        int64
	TokenHash     []byte
	State         string
	Method        string
	IdpMfa        bool
	Address       *netip.Addr
	UserAgent     pgtype.Text
	CreatedAt     time.Time
	IdleExpiresAt time.Time
	ExpiresAt     time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.OrgID,
		arg.PublicID,
		arg.UserID,
		arg.TokenHash,
		arg.State,
		arg.Method,
		arg.IdpMfa,
		arg.Address,
		arg.UserAgent,
		arg.CreatedAt,
		arg.IdleExpiresAt,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const endOtherUserSessions = `-- name: EndOtherUserSessions :execrows
UPDATE sessions
SET ended_at = $1::timestamptz, end_reason = $2
WHERE org_id = $3 AND user_id = $4 AND id <> $5 AND ended_at IS NULL
`

type EndOtherUserSessionsParams struct {
	Now       time.Time
	EndReason pgtype.Text
	OrgID     int64
	UserID    int64
	KeepID    int64
}

func (q *Queries) EndOtherUserSessions(ctx context.Context, arg EndOtherUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, endOtherUserSessions,
		arg.Now,
		arg.EndReason,
		arg.OrgID,
		arg.UserID,
		arg.KeepID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endSession = `-- name: EndSession :execrows
UPDATE sessions
SET ended_at = $1::timestamptz, end_reason = $2
WHERE org_id = $3 AND id = $4 AND ended_at IS NULL
`

type EndSessionParams struct {
	Now       time.Time
	EndReason pgtype.Text
	OrgID     int64
	ID        int64
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, endSession,
		arg.Now,
		arg.EndReason,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endUserSessions = `-- name: EndUserSessions :execrows
UPDATE sessions
SET ended_at = $1::timestamptz, end_reason = $2
WHERE org_id = $3 AND user_id = $4 AND ended_at IS NULL
`

type EndUserSessionsParams struct {
	Now       time.Time
	EndReason pgtype.Text
	OrgID     int64
	UserID    int64
}

func (q *Queries) EndUserSessions(ctx context.Context, arg EndUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, endUserSessions,
		arg.Now,
		arg.EndReason,
		arg.OrgID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT s.id, s.public_id, s.user_id, s.state, s.method, s.address, s.user_agent, s.created_at, s.last_used_at,
       s.idle_expires_at, s.expires_at, s.ended_at, s.end_reason, u.public_id AS user_public_id, u.name AS user_name,
       u.role AS user_role, u.status AS user_status
FROM sessions s
JOIN users u ON u.org_id = s.org_id AND u.id = s.user_id
WHERE s.org_id = $1 AND u.org_id = $1 AND s.token_hash = $2
`

type GetSessionByTokenParams struct {
	OrgID     int64
	TokenHash []byte
}

type GetSessionByTokenRow struct {
	ID            int64
	PublicID      string
	UserID        int64
	State         string
	Method        string
	Address       *netip.Addr
	UserAgent     pgtype.Text
	CreatedAt     time.Time
	LastUsedAt    time.Time
	IdleExpiresAt time.Time
	ExpiresAt     time.Time
	EndedAt       pgtype.Timestamptz
	EndReason     pgtype.Text
	UserPublicID  string
	UserName      string
	UserRole      string
	UserStatus    string
}

// GetSessionByToken finds a session by the hash of its cookie value, with its user.
func (q *Queries) GetSessionByToken(ctx context.Context, arg GetSessionByTokenParams) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, arg.OrgID, arg.TokenHash)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.State,
		&i.Method,
		&i.Address,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.IdleExpiresAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndReason,
		&i.UserPublicID,
		&i.UserName,
		&i.UserRole,
		&i.UserStatus,
	)
	return i, err
}

const getSignInUser = `-- name: GetSignInUser :one
SELECT u.id, u.public_id, u.name, u.role, u.status, u.password_hash,
       EXISTS (
           SELECT 1 FROM user_totp t
           WHERE t.org_id = u.org_id AND t.user_id = u.id AND t.enrolled_at IS NOT NULL
       ) AS totp_enrolled,
       o.totp_required
FROM users u
JOIN organizations o ON o.id = u.org_id
WHERE u.org_id = $1 AND lower(u.login) = lower($2)
`

type GetSignInUserParams struct {
	OrgID int64
	Login string
}

type GetSignInUserRow struct {
	ID           int64
	PublicID     string
	Name         string
	Role         string
	Status       string
	PasswordHash pgtype.Text
	TotpEnrolled bool
	TotpRequired string
}

// GetSignInUser finds the account of a login, compared lowercased, with whether it has TOTP and the Organization's
// TOTP policy.
func (q *Queries) GetSignInUser(ctx context.Context, arg GetSignInUserParams) (GetSignInUserRow, error) {
	row := q.db.QueryRow(ctx, getSignInUser, arg.OrgID, arg.Login)
	var i GetSignInUserRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.PasswordHash,
		&i.TotpEnrolled,
		&i.TotpRequired,
	)
	return i, err
}

const getThrottles = `-- name: GetThrottles :many
SELECT subject_kind, consecutive_failures, blocked_until
FROM sign_in_throttles
WHERE org_id = $1
  AND ((subject_kind = 'account' AND subject = $2) OR (subject_kind = 'address' AND subject = $3))
`

type GetThrottlesParams struct {
	OrgID   int64
	Account string
	Address string
}

type GetThrottlesRow struct {
	SubjectKind         string
	ConsecutiveFailures int64
	BlockedUntil        pgtype.Timestamptz
}

func (q *Queries) GetThrottles(ctx context.Context, arg GetThrottlesParams) ([]GetThrottlesRow, error) {
	rows, err := q.db.Query(ctx, getThrottles, arg.OrgID, arg.Account, arg.Address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetThrottlesRow{}
	for rows.Next() {
		var i GetThrottlesRow
		if err := rows.Scan(&i.SubjectKind, &i.ConsecutiveFailures, &i.BlockedUntil); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPassword = `-- name: GetUserPassword :one
SELECT login, password_hash, (oidc_subject IS NOT NULL)::boolean AS has_oidc_identity
FROM users
WHERE org_id = $1 AND id = $2
`

type GetUserPasswordParams struct {
	OrgID int64
	ID    int64
}

type GetUserPasswordRow struct {
	Login           string
	PasswordHash    pgtype.Text
	HasOidcIdentity bool
}

func (q *Queries) GetUserPassword(ctx context.Context, arg GetUserPasswordParams) (GetUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, getUserPassword, arg.OrgID, arg.ID)
	var i GetUserPasswordRow
	err := row.Scan(&i.Login, &i.PasswordHash, &i.HasOidcIdentity)
	return i, err
}

const listRolePermissions = `-- name: ListRolePermissions :many

SELECT role, permission
FROM role_permissions
ORDER BY role, permission
`

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// ListRolePermissions reads the allocation of Permissions to Roles, reference data without org_id.
func (q *Queries) ListRolePermissions(ctx context.Context) ([]RolePermission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePermission{}
	for rows.Next() {
		var i RolePermission
		if err := rows.Scan(&i.Role, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, public_id, method, address, user_agent, created_at, last_used_at
FROM sessions
WHERE org_id = $1 AND user_id = $2 AND ended_at IS NULL AND idle_expires_at > $3 AND expires_at > $3
ORDER BY last_used_at DESC, id DESC
`

type ListUserSessionsParams struct {
	OrgID  int64
	UserID int64
	Now    time.Time
}

type ListUserSessionsRow struct {
	ID         int64
	PublicID   string
	Method     string
	Address    *netip.Addr
	UserAgent  pgtype.Text
	CreatedAt  time.Time
	LastUsedAt time.Time
}

// ListUserSessions lists the sessions of a user that have neither ended nor expired, the latest used first.
func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.OrgID, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSessionsRow{}
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Method,
			&i.Address,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveSessions = `-- name: LiveSessions :many
SELECT s.id
FROM sessions s
JOIN users u ON u.org_id = s.org_id AND u.id = s.user_id
WHERE s.org_id = $1 AND u.org_id = $1 AND s.id = ANY($2::bigint[]) AND s.state = 'active'
  AND s.ended_at IS NULL AND s.idle_expires_at > $3 AND s.expires_at > $3 AND u.status = 'active'
`

type LiveSessionsParams struct {
	OrgID int64
	Ids   []int64
	Now   time.Time
}

// LiveSessions returns which of the sessions are still usable at @now: active, neither ended nor expired, of an active
// user. Reading them does not count as a use.
func (q *Queries) LiveSessions(ctx context.Context, arg LiveSessionsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, liveSessions, arg.OrgID, arg.Ids, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSignedIn = `-- name: MarkSignedIn :exec
UPDATE users
SET last_sign_in_at = $1::timestamptz
WHERE org_id = $2 AND id = $3
`

type MarkSignedInParams struct {
	Now   time.Time
	OrgID int64
	ID    int64
}

func (q *Queries) MarkSignedIn(ctx context.Context, arg MarkSignedInParams) error {
	_, err := q.db.Exec(ctx, markSignedIn, arg.Now, arg.OrgID, arg.ID)
	return err
}

const pruneSessions = `-- name: PruneSessions :execrows
DELETE FROM sessions s
WHERE s.org_id = $1 AND s.id IN (
    SELECT e.id FROM sessions e
    WHERE e.org_id = $1 AND LEAST(e.ended_at, e.idle_expires_at, e.expires_at) < $2::timestamptz
    ORDER BY e.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
`

type PruneSessionsParams struct {
	OrgID     int64
	Before    time.Time
	BatchSize int32
}

// PruneSessions deletes up to batch_size sessions that could no longer be used before @before: ended, past their idle
// timeout or past their lifetime. A session row being used is skipped and taken at the next run.
func (q *Queries) PruneSessions(ctx context.Context, arg PruneSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneSessions, arg.OrgID, arg.Before, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pruneSignInThrottles = `-- name: PruneSignInThrottles :execrows
DELETE FROM sign_in_throttles t
WHERE t.org_id = $1 AND (t.subject_kind, t.subject) IN (
    SELECT o.subject_kind, o.subject FROM sign_in_throttles o
    WHERE o.org_id = $1 AND o.last_failure_at < $2::timestamptz
      AND (o.blocked_until IS NULL OR o.blocked_until < $2::timestamptz)
    ORDER BY o.subject_kind, o.subject
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
`

type PruneSignInThrottlesParams struct {
	OrgID     int64
	Before    time.Time
	BatchSize int32
}

// PruneSignInThrottles deletes up to batch_size throttle rows whose last failure, and whose block, are older than
// @before. A row being counted is skipped and taken at the next run.
func (q *Queries) PruneSignInThrottles(ctx context.Context, arg PruneSignInThrottlesParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneSignInThrottles, arg.OrgID, arg.Before, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordSignInFailure = `-- name: RecordSignInFailure :one
INSERT INTO sign_in_throttles (org_id, subject_kind, subject, consecutive_failures, last_failure_at)
VALUES ($1, $2, $3, 1, $4)
ON CONFLICT (org_id, subject_kind, subject) DO UPDATE
SET consecutive_failures = sign_in_throttles.consecutive_failures + 1, last_failure_at = EXCLUDED.last_failure_at
RETURNING consecutive_failures
`

type RecordSignInFailureParams struct {
	OrgID       int64
	SubjectKind string
	Subject     string
	Now         time.Time
}

// RecordSignInFailure counts one more consecutive failure of a subject and returns the count.
func (q *Queries) RecordSignInFailure(ctx context.Context, arg RecordSignInFailureParams) (int64, error) {
	row := q.db.QueryRow(ctx, recordSignInFailure,
		arg.OrgID,
		arg.SubjectKind,
		arg.Subject,
		arg.Now,
	)
	var consecutive_failures int64
	err := row.Scan(&consecutive_failures)
	return consecutive_failures, err
}

const resetSignInThrottles = `-- name: ResetSignInThrottles :exec
DELETE FROM sign_in_throttles
WHERE org_id = $1
  AND ((subject_kind = 'account' AND subject = $2) OR (subject_kind = 'address' AND subject = $3))
`

type ResetSignInThrottlesParams struct {
	OrgID   int64
	Account string
	Address string
}

// ResetSignInThrottles forgets the failures of an account and of a source address after a successful sign-in.
func (q *Queries) ResetSignInThrottles(ctx context.Context, arg ResetSignInThrottlesParams) error {
	_, err := q.db.Exec(ctx, resetSignInThrottles, arg.OrgID, arg.Account, arg.Address)
	return err
}

const setPassword = `-- name: SetPassword :execrows
UPDATE users
SET password_hash = $1, password_changed_at = $2::timestamptz, updated_at = $2::timestamptz, version = version + 1
WHERE org_id = $3 AND id = $4 AND oidc_subject IS NULL
`

type SetPasswordParams struct {
	PasswordHash pgtype.Text
	Now          time.Time
	OrgID        int64
	ID           int64
}

// SetPassword replaces the password of a local account.
func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPassword,
		arg.PasswordHash,
		arg.Now,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_used_at = $1, idle_expires_at = $2
WHERE org_id = $3 AND id = $4 AND ended_at IS NULL
`

type TouchSessionParams struct {
	Now           time.Time
	IdleExpiresAt time.Time
	OrgID         int64
	ID            int64
}

// TouchSession records the use of a session, at most once a minute, and moves its idle expiry.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession,
		arg.Now,
		arg.IdleExpiresAt,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const tryLockSignInSubject = `-- name: TryLockSignInSubject :one
SELECT pg_try_advisory_xact_lock($1::int, hashtext($2::text))::boolean AS locked
`

type TryLockSignInSubjectParams struct {
	LockClass int32
	Subject   string
}

// TryLockSignInSubject takes the attempt lock of an account until the transaction ends, without waiting; false means
// that another attempt of the account is being evaluated. The two-key advisory locks do not overlap the one-key locks
// of the migrations and the Leader.
func (q *Queries) TryLockSignInSubject(ctx context.Context, arg TryLockSignInSubjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, tryLockSignInSubject, arg.LockClass, arg.Subject)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}
