/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PasswordSetupRouteImport } from './routes/password-setup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as TotpEnrolmentRouteImport } from './routes/totp-enrolment'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminOidcRouteImport } from './routes/admin.oidc'
import { Route as AlertGroupsIndexRouteImport } from './routes/alert-groups.index'
import { Route as AlertGroupsAlertGroupIdRouteImport } from './routes/alert-groups.$alertGroupId'
import { Route as ConnectionsIndexRouteImport } from './routes/connections.index'
import { Route as ConnectionsConnectionIdRouteImport } from './routes/connections.$connectionId'
import { Route as ConnectionsNewRouteImport } from './routes/connections.new'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as IntegrationsNewRouteImport } from './routes/integrations.new'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as RoutesRouteIdRouteImport } from './routes/routes.$routeId'
import { Route as RoutesNewRouteImport } from './routes/routes.new'
import { Route as SignInTotpRouteImport } from './routes/sign-in.totp'
import { Route as AdminOrganizationSecurityRouteImport } from './routes/admin.organization.security'
import { Route as AdminServiceAccountsIndexRouteImport } from './routes/admin.service-accounts.index'
import { Route as AdminServiceAccountsServiceAccountIdRouteImport } from './routes/admin.service-accounts.$serviceAccountId'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as IntegrationsIntegrationIdIndexRouteImport } from './routes/integrations.$integrationId.index'
import { Route as IntegrationsIntegrationIdEditRouteImport } from './routes/integrations.$integrationId.edit'
import { Route as AdminOrganizationLinkRulesIndexRouteImport } from './routes/admin.organization.link-rules.index'
import { Route as AdminOrganizationLinkRulesLinkRuleIdRouteImport } from './routes/admin.organization.link-rules.$linkRuleId'
import { Route as AdminOrganizationLinkRulesNewRouteImport } from './routes/admin.organization.link-rules.new'
import { Route as AdminOrganizationLookupTablesIndexRouteImport } from './routes/admin.organization.lookup-tables.index'
import { Route as AdminOrganizationLookupTablesLookupTableIdRouteImport } from './routes/admin.organization.lookup-tables.$lookupTableId'
import { Route as AdminOrganizationLookupTablesNewRouteImport } from './routes/admin.organization.lookup-tables.new'
import { Route as IntegrationsIntegrationIdSnapshotsStoredSnapshotIdRouteImport } from './routes/integrations.$integrationId.snapshots.$storedSnapshotId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordSetupRoute = PasswordSetupRouteImport.update({
  id: '/password-setup',
  path: '/password-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TotpEnrolmentRoute = TotpEnrolmentRouteImport.update({
  id: '/totp-enrolment',
  path: '/totp-enrolment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOidcRoute = AdminOidcRouteImport.update({
  id: '/admin/oidc',
  path: '/admin/oidc',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertGroupsIndexRoute = AlertGroupsIndexRouteImport.update({
  id: '/alert-groups/',
  path: '/alert-groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertGroupsAlertGroupIdRoute = AlertGroupsAlertGroupIdRouteImport.update({
  id: '/alert-groups/$alertGroupId',
  path: '/alert-groups/$alertGroupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsIndexRoute = ConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsConnectionIdRoute = ConnectionsConnectionIdRouteImport.update({
  id: '/connections/$connectionId',
  path: '/connections/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsNewRoute = ConnectionsNewRouteImport.update({
  id: '/connections/new',
  path: '/connections/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsNewRoute = IntegrationsNewRouteImport.update({
  id: '/integrations/new',
  path: '/integrations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesNewRoute = RoutesNewRouteImport.update({
  id: '/routes/new',
  path: '/routes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInTotpRoute = SignInTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => SignInRoute,
} as any)
const AdminOrganizationSecurityRoute =
  AdminOrganizationSecurityRouteImport.update({
    id: '/admin/organization/security',
    path: '/admin/organization/security',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminServiceAccountsIndexRoute =
  AdminServiceAccountsIndexRouteImport.update({
    id: '/admin/service-accounts/',
    path: '/admin/service-accounts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminServiceAccountsServiceAccountIdRoute =
  AdminServiceAccountsServiceAccountIdRouteImport.update({
    id: '/admin/service-accounts/$serviceAccountId',
    path: '/admin/service-accounts/$serviceAccountId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIntegrationIdIndexRoute =
  IntegrationsIntegrationIdIndexRouteImport.update({
    id: '/integrations/$integrationId/',
    path: '/integrations/$integrationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationsIntegrationIdEditRoute =
  IntegrationsIntegrationIdEditRouteImport.update({
    id: '/integrations/$integrationId/edit',
    path: '/integrations/$integrationId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrganizationLinkRulesIndexRoute =
  AdminOrganizationLinkRulesIndexRouteImport.update({
    id: '/admin/organization/link-rules/',
    path: '/admin/organization/link-rules/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrganizationLinkRulesLinkRuleIdRoute =
  AdminOrganizationLinkRulesLinkRuleIdRouteImport.update({
    id: '/admin/organization/link-rules/$linkRuleId',
    path: '/admin/organization/link-rules/$linkRuleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrganizationLinkRulesNewRoute =
  AdminOrganizationLinkRulesNewRouteImport.update({
    id: '/admin/organization/link-rules/new',
    path: '/admin/organization/link-rules/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrganizationLookupTablesIndexRoute =
  AdminOrganizationLookupTablesIndexRouteImport.update({
    id: '/admin/organization/lookup-tables/',
    path: '/admin/organization/lookup-tables/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrganizationLookupTablesLookupTableIdRoute =
  AdminOrganizationLookupTablesLookupTableIdRouteImport.update({
    id: '/admin/organization/lookup-tables/$lookupTableId',
    path: '/admin/organization/lookup-tables/$lookupTableId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrganizationLookupTablesNewRoute =
  AdminOrganizationLookupTablesNewRouteImport.update({
    id: '/admin/organization/lookup-tables/new',
    path: '/admin/organization/lookup-tables/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntegrationsIntegrationIdSnapshotsStoredSnapshotIdRoute =
  IntegrationsIntegrationIdSnapshotsStoredSnapshotIdRouteImport.update({
    id: '/integrations/$integrationId/snapshots/$storedSnapshotId',
    path: '/integrations/$integrationId/snapshots/$storedSnapshotId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/password-setup': typeof PasswordSetupRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/totp-enrolment': typeof TotpEnrolmentRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/oidc': typeof AdminOidcRoute
  '/alert-groups/$alertGroupId': typeof AlertGroupsAlertGroupIdRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRoute
  '/connections/new': typeof ConnectionsNewRoute
  '/integrations/new': typeof IntegrationsNewRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/sign-in/totp': typeof SignInTotpRoute
  '/alert-groups/': typeof AlertGroupsIndexRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/admin/organization/security': typeof AdminOrganizationSecurityRoute
  '/admin/service-accounts/$serviceAccountId': typeof AdminServiceAccountsServiceAccountIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/integrations/$integrationId/edit': typeof IntegrationsIntegrationIdEditRoute
  '/admin/service-accounts/': typeof AdminServiceAccountsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/integrations/$integrationId/': typeof IntegrationsIntegrationIdIndexRoute
  '/admin/organization/link-rules/$linkRuleId': typeof AdminOrganizationLinkRulesLinkRuleIdRoute
  '/admin/organization/link-rules/new': typeof AdminOrganizationLinkRulesNewRoute
  '/admin/organization/lookup-tables/$lookupTableId': typeof AdminOrganizationLookupTablesLookupTableIdRoute
  '/admin/organization/lookup-tables/new': typeof AdminOrganizationLookupTablesNewRoute
  '/integrations/$integrationId/snapshots/$storedSnapshotId': typeof IntegrationsIntegrationIdSnapshotsStoredSnapshotIdRoute
  '/admin/organization/link-rules/': typeof AdminOrganizationLinkRulesIndexRoute
  '/admin/organization/lookup-tables/': typeof AdminOrganizationLookupTablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/password-setup': typeof PasswordSetupRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/totp-enrolment': typeof TotpEnrolmentRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/oidc': typeof AdminOidcRoute
  '/alert-groups/$alertGroupId': typeof AlertGroupsAlertGroupIdRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRoute
  '/connections/new': typeof ConnectionsNewRoute
  '/integrations/new': typeof IntegrationsNewRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/sign-in/totp': typeof SignInTotpRoute
  '/alert-groups': typeof AlertGroupsIndexRoute
  '/connections': typeof ConnectionsIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
  '/routes': typeof RoutesIndexRoute
  '/admin/organization/security': typeof AdminOrganizationSecurityRoute
  '/admin/service-accounts/$serviceAccountId': typeof AdminServiceAccountsServiceAccountIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/integrations/$integrationId/edit': typeof IntegrationsIntegrationIdEditRoute
  '/admin/service-accounts': typeof AdminServiceAccountsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/integrations/$integrationId': typeof IntegrationsIntegrationIdIndexRoute
  '/admin/organization/link-rules/$linkRuleId': typeof AdminOrganizationLinkRulesLinkRuleIdRoute
  '/admin/organization/link-rules/new': typeof AdminOrganizationLinkRulesNewRoute
  '/admin/organization/lookup-tables/$lookupTableId': typeof AdminOrganizationLookupTablesLookupTableIdRoute
  '/admin/organization/lookup-tables/new': typeof AdminOrganizationLookupTablesNewRoute
  '/integrations/$integrationId/snapshots/$storedSnapshotId': typeof IntegrationsIntegrationIdSnapshotsStoredSnapshotIdRoute
  '/admin/organization/link-rules': typeof AdminOrganizationLinkRulesIndexRoute
  '/admin/organization/lookup-tables': typeof AdminOrganizationLookupTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/password-setup': typeof PasswordSetupRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/totp-enrolment': typeof TotpEnrolmentRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/oidc': typeof AdminOidcRoute
  '/alert-groups/$alertGroupId': typeof AlertGroupsAlertGroupIdRoute
  '/connections/$connectionId': typeof ConnectionsConnectionIdRoute
  '/connections/new': typeof ConnectionsNewRoute
  '/integrations/new': typeof IntegrationsNewRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/sign-in/totp': typeof SignInTotpRoute
  '/alert-groups/': typeof AlertGroupsIndexRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/admin/organization/security': typeof AdminOrganizationSecurityRoute
  '/admin/service-accounts/$serviceAccountId': typeof AdminServiceAccountsServiceAccountIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/integrations/$integrationId/edit': typeof IntegrationsIntegrationIdEditRoute
  '/admin/service-accounts/': typeof AdminServiceAccountsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/integrations/$integrationId/': typeof IntegrationsIntegrationIdIndexRoute
  '/admin/organization/link-rules/$linkRuleId': typeof AdminOrganizationLinkRulesLinkRuleIdRoute
  '/admin/organization/link-rules/new': typeof AdminOrganizationLinkRulesNewRoute
  '/admin/organization/lookup-tables/$lookupTableId': typeof AdminOrganizationLookupTablesLookupTableIdRoute
  '/admin/organization/lookup-tables/new': typeof AdminOrganizationLookupTablesNewRoute
  '/integrations/$integrationId/snapshots/$storedSnapshotId': typeof IntegrationsIntegrationIdSnapshotsStoredSnapshotIdRoute
  '/admin/organization/link-rules/': typeof AdminOrganizationLinkRulesIndexRoute
  '/admin/organization/lookup-tables/': typeof AdminOrganizationLookupTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/password-setup'
    | '/profile'
    | '/sign-in'
    | '/statistics'
    | '/totp-enrolment'
    | '/admin/audit-log'
    | '/admin/oidc'
    | '/alert-groups/$alertGroupId'
    | '/connections/$connectionId'
    | '/connections/new'
    | '/integrations/new'
    | '/routes/$routeId'
    | '/routes/new'
    | '/sign-in/totp'
    | '/alert-groups/'
    | '/connections/'
    | '/integrations/'
    | '/routes/'
    | '/admin/organization/security'
    | '/admin/service-accounts/$serviceAccountId'
    | '/admin/users/$userId'
    | '/integrations/$integrationId/edit'
    | '/admin/service-accounts/'
    | '/admin/users/'
    | '/integrations/$integrationId/'
    | '/admin/organization/link-rules/$linkRuleId'
    | '/admin/organization/link-rules/new'
    | '/admin/organization/lookup-tables/$lookupTableId'
    | '/admin/organization/lookup-tables/new'
    | '/integrations/$integrationId/snapshots/$storedSnapshotId'
    | '/admin/organization/link-rules/'
    | '/admin/organization/lookup-tables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/password-setup'
    | '/profile'
    | '/sign-in'
    | '/statistics'
    | '/totp-enrolment'
    | '/admin/audit-log'
    | '/admin/oidc'
    | '/alert-groups/$alertGroupId'
    | '/connections/$connectionId'
    | '/connections/new'
    | '/integrations/new'
    | '/routes/$routeId'
    | '/routes/new'
    | '/sign-in/totp'
    | '/alert-groups'
    | '/connections'
    | '/integrations'
    | '/routes'
    | '/admin/organization/security'
    | '/admin/service-accounts/$serviceAccountId'
    | '/admin/users/$userId'
    | '/integrations/$integrationId/edit'
    | '/admin/service-accounts'
    | '/admin/users'
    | '/integrations/$integrationId'
    | '/admin/organization/link-rules/$linkRuleId'
    | '/admin/organization/link-rules/new'
    | '/admin/organization/lookup-tables/$lookupTableId'
    | '/admin/organization/lookup-tables/new'
    | '/integrations/$integrationId/snapshots/$storedSnapshotId'
    | '/admin/organization/link-rules'
    | '/admin/organization/lookup-tables'
  id:
    | '__root__'
    | '/'
    | '/password-setup'
    | '/profile'
    | '/sign-in'
    | '/statistics'
    | '/totp-enrolment'
    | '/admin/audit-log'
    | '/admin/oidc'
    | '/alert-groups/$alertGroupId'
    | '/connections/$connectionId'
    | '/connections/new'
    | '/integrations/new'
    | '/routes/$routeId'
    | '/routes/new'
    | '/sign-in/totp'
    | '/alert-groups/'
    | '/connections/'
    | '/integrations/'
    | '/routes/'
    | '/admin/organization/security'
    | '/admin/service-accounts/$serviceAccountId'
    | '/admin/users/$userId'
    | '/integrations/$integrationId/edit'
    | '/admin/service-accounts/'
    | '/admin/users/'
    | '/integrations/$integrationId/'
    | '/admin/organization/link-rules/$linkRuleId'
    | '/admin/organization/link-rules/new'
    | '/admin/organization/lookup-tables/$lookupTableId'
    | '/admin/organization/lookup-tables/new'
    | '/integrations/$integrationId/snapshots/$storedSnapshotId'
    | '/admin/organization/link-rules/'
    | '/admin/organization/lookup-tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PasswordSetupRoute: typeof PasswordSetupRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRouteWithChildren
  StatisticsRoute: typeof StatisticsRoute
  TotpEnrolmentRoute: typeof TotpEnrolmentRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminOidcRoute: typeof AdminOidcRoute
  AlertGroupsAlertGroupIdRoute: typeof AlertGroupsAlertGroupIdRoute
  ConnectionsConnectionIdRoute: typeof ConnectionsConnectionIdRoute
  ConnectionsNewRoute: typeof ConnectionsNewRoute
  IntegrationsNewRoute: typeof IntegrationsNewRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
  RoutesNewRoute: typeof RoutesNewRoute
  AlertGroupsIndexRoute: typeof AlertGroupsIndexRoute
  ConnectionsIndexRoute: typeof ConnectionsIndexRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  AdminOrganizationSecurityRoute: typeof AdminOrganizationSecurityRoute
  AdminServiceAccountsServiceAccountIdRoute: typeof AdminServiceAccountsServiceAccountIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  IntegrationsIntegrationIdEditRoute: typeof IntegrationsIntegrationIdEditRoute
  AdminServiceAccountsIndexRoute: typeof AdminServiceAccountsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  IntegrationsIntegrationIdIndexRoute: typeof IntegrationsIntegrationIdIndexRoute
  AdminOrganizationLinkRulesLinkRuleIdRoute: typeof AdminOrganizationLinkRulesLinkRuleIdRoute
  AdminOrganizationLinkRulesNewRoute: typeof AdminOrganizationLinkRulesNewRoute
  AdminOrganizationLookupTablesLookupTableIdRoute: typeof AdminOrganizationLookupTablesLookupTableIdRoute
  AdminOrganizationLookupTablesNewRoute: typeof AdminOrganizationLookupTablesNewRoute
  IntegrationsIntegrationIdSnapshotsStoredSnapshotIdRoute: typeof IntegrationsIntegrationIdSnapshotsStoredSnapshotIdRoute
  AdminOrganizationLinkRulesIndexRoute: typeof AdminOrganizationLinkRulesIndexRoute
  AdminOrganizationLookupTablesIndexRoute: typeof AdminOrganizationLookupTablesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-setup': {
      id: '/password-setup'
      path: '/password-setup'
      fullPath: '/password-setup'
      preLoaderRoute: typeof PasswordSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totp-enrolment': {
      id: '/totp-enrolment'
      path: '/totp-enrolment'
      fullPath: '/totp-enrolment'
      preLoaderRoute: typeof TotpEnrolmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/oidc': {
      id: '/admin/oidc'
      path: '/admin/oidc'
      fullPath: '/admin/oidc'
      preLoaderRoute: typeof AdminOidcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-groups/': {
      id: '/alert-groups/'
      path: '/alert-groups'
      fullPath: '/alert-groups/'
      preLoaderRoute: typeof AlertGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-groups/$alertGroupId': {
      id: '/alert-groups/$alertGroupId'
      path: '/alert-groups/$alertGroupId'
      fullPath: '/alert-groups/$alertGroupId'
      preLoaderRoute: typeof AlertGroupsAlertGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/': {
      id: '/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof ConnectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/$connectionId': {
      id: '/connections/$connectionId'
      path: '/connections/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof ConnectionsConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/new': {
      id: '/connections/new'
      path: '/connections/new'
      fullPath: '/connections/new'
      preLoaderRoute: typeof ConnectionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/new': {
      id: '/integrations/new'
      path: '/integrations/new'
      fullPath: '/integrations/new'
      preLoaderRoute: typeof IntegrationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/new': {
      id: '/routes/new'
      path: '/routes/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof RoutesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/totp': {
      id: '/sign-in/totp'
      path: '/totp'
      fullPath: '/sign-in/totp'
      preLoaderRoute: typeof SignInTotpRouteImport
      parentRoute: typeof SignInRoute
    }
    '/admin/organization/security': {
      id: '/admin/organization/security'
      path: '/admin/organization/security'
      fullPath: '/admin/organization/security'
      preLoaderRoute: typeof AdminOrganizationSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/service-accounts/': {
      id: '/admin/service-accounts/'
      path: '/admin/service-accounts'
      fullPath: '/admin/service-accounts/'
      preLoaderRoute: typeof AdminServiceAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/service-accounts/$serviceAccountId': {
      id: '/admin/service-accounts/$serviceAccountId'
      path: '/admin/service-accounts/$serviceAccountId'
      fullPath: '/admin/service-accounts/$serviceAccountId'
      preLoaderRoute: typeof AdminServiceAccountsServiceAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$integrationId/': {
      id: '/integrations/$integrationId/'
      path: '/integrations/$integrationId'
      fullPath: '/integrations/$integrationId/'
      preLoaderRoute: typeof IntegrationsIntegrationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$integrationId/edit': {
      id: '/integrations/$integrationId/edit'
      path: '/integrations/$integrationId/edit'
      fullPath: '/integrations/$integrationId/edit'
      preLoaderRoute: typeof IntegrationsIntegrationIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organization/link-rules/': {
      id: '/admin/organization/link-rules/'
      path: '/admin/organization/link-rules'
      fullPath: '/admin/organization/link-rules/'
      preLoaderRoute: typeof AdminOrganizationLinkRulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organization/link-rules/$linkRuleId': {
      id: '/admin/organization/link-rules/$linkRuleId'
      path: '/admin/organization/link-rules/$linkRuleId'
      fullPath: '/admin/organization/link-rules/$linkRuleId'
      preLoaderRoute: typeof AdminOrganizationLinkRulesLinkRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organization/link-rules/new': {
      id: '/admin/organization/link-rules/new'
      path: '/admin/organization/link-rules/new'
      fullPath: '/admin/organization/link-rules/new'
      preLoaderRoute: typeof AdminOrganizationLinkRulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organization/lookup-tables/': {
      id: '/admin/organization/lookup-tables/'
      path: '/admin/organization/lookup-tables'
      fullPath: '/admin/organization/lookup-tables/'
      preLoaderRoute: typeof AdminOrganizationLookupTablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organization/lookup-tables/$lookupTableId': {
      id: '/admin/organization/lookup-tables/$lookupTableId'
      path: '/admin/organization/lookup-tables/$lookupTableId'
      fullPath: '/admin/organization/lookup-tables/$lookupTableId'
      preLoaderRoute: typeof AdminOrganizationLookupTablesLookupTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organization/lookup-tables/new': {
      id: '/admin/organization/lookup-tables/new'
      path: '/admin/organization/lookup-tables/new'
      fullPath: '/admin/organization/lookup-tables/new'
      preLoaderRoute: typeof AdminOrganizationLookupTablesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/$integrationId/snapshots/$storedSnapshotId': {
      id: '/integrations/$integrationId/snapshots/$storedSnapshotId'
      path: '/integrations/$integrationId/snapshots/$storedSnapshotId'
      fullPath: '/integrations/$integrationId/snapshots/$storedSnapshotId'
      preLoaderRoute: typeof IntegrationsIntegrationIdSnapshotsStoredSnapshotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SignInRouteChildren {
  SignInTotpRoute: typeof SignInTotpRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInTotpRoute: SignInTotpRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PasswordSetupRoute: PasswordSetupRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRouteWithChildren,
  StatisticsRoute: StatisticsRoute,
  TotpEnrolmentRoute: TotpEnrolmentRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminOidcRoute: AdminOidcRoute,
  AlertGroupsAlertGroupIdRoute: AlertGroupsAlertGroupIdRoute,
  ConnectionsConnectionIdRoute: ConnectionsConnectionIdRoute,
  ConnectionsNewRoute: ConnectionsNewRoute,
  IntegrationsNewRoute: IntegrationsNewRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
  RoutesNewRoute: RoutesNewRoute,
  AlertGroupsIndexRoute: AlertGroupsIndexRoute,
  ConnectionsIndexRoute: ConnectionsIndexRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  AdminOrganizationSecurityRoute: AdminOrganizationSecurityRoute,
  AdminServiceAccountsServiceAccountIdRoute:
    AdminServiceAccountsServiceAccountIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  IntegrationsIntegrationIdEditRoute: IntegrationsIntegrationIdEditRoute,
  AdminServiceAccountsIndexRoute: AdminServiceAccountsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  IntegrationsIntegrationIdIndexRoute: IntegrationsIntegrationIdIndexRoute,
  AdminOrganizationLinkRulesLinkRuleIdRoute:
    AdminOrganizationLinkRulesLinkRuleIdRoute,
  AdminOrganizationLinkRulesNewRoute: AdminOrganizationLinkRulesNewRoute,
  AdminOrganizationLookupTablesLookupTableIdRoute:
    AdminOrganizationLookupTablesLookupTableIdRoute,
  AdminOrganizationLookupTablesNewRoute: AdminOrganizationLookupTablesNewRoute,
  IntegrationsIntegrationIdSnapshotsStoredSnapshotIdRoute:
    IntegrationsIntegrationIdSnapshotsStoredSnapshotIdRoute,
  AdminOrganizationLinkRulesIndexRoute: AdminOrganizationLinkRulesIndexRoute,
  AdminOrganizationLookupTablesIndexRoute:
    AdminOrganizationLookupTablesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
