// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    public_id, name, time_zone, severity_label, severity_mapping, severity_styles, critical_is_urgent,
    instance_labels, retention_stored_snapshots_days, retention_alert_details_days,
    retention_alert_group_summaries_days, retention_audit_log_days, totp_required, oidc_token_grace_seconds,
    created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13, $14,
    $15, $15
)
RETURNING id
`

type CreateOrganizationParams struct {
	PublicID                         string
	Name                             string
	TimeZone                         string
	SeverityLabel                    string
	SeverityMapping                  []byte
	SeverityStyles                   []byte
	CriticalIsUrgent                 bool
	InstanceLabels                   []string
	RetentionStoredSnapshotsDays     int64
	RetentionAlertDetailsDays        int64
	RetentionAlertGroupSummariesDays int64
	RetentionAuditLogDays            int64
	TotpRequired                     string
	OidcTokenGraceSeconds            int64
	CreatedAt                        time.Time
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.PublicID,
		arg.Name,
		arg.TimeZone,
		arg.SeverityLabel,
		arg.SeverityMapping,
		arg.SeverityStyles,
		arg.CriticalIsUrgent,
		arg.InstanceLabels,
		arg.RetentionStoredSnapshotsDays,
		arg.RetentionAlertDetailsDays,
		arg.RetentionAlertGroupSummariesDays,
		arg.RetentionAuditLogDays,
		arg.TotpRequired,
		arg.OidcTokenGraceSeconds,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOutboundPolicy = `-- name: CreateOutboundPolicy :execrows
INSERT INTO outbound_policies (org_id, policy, allowed, denied, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id) DO NOTHING
`

type CreateOutboundPolicyParams struct {
	OrgID     int64
	Policy    string
	Allowed   []string
	Denied    []string
	UpdatedAt time.Time
}

// CreateOutboundPolicy writes the Organization's outbound address policy; it changes nothing when one exists.
func (q *Queries) CreateOutboundPolicy(ctx context.Context, arg CreateOutboundPolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, createOutboundPolicy,
		arg.OrgID,
		arg.Policy,
		arg.Allowed,
		arg.Denied,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrganization = `-- name: GetOrganization :one

SELECT id, public_id, name, time_zone, severity_label, severity_mapping, severity_styles, critical_is_urgent,
       instance_labels, retention_stored_snapshots_days, retention_alert_details_days,
       retention_alert_group_summaries_days, retention_audit_log_days, totp_required, oidc_token_grace_seconds
FROM organizations
ORDER BY id
LIMIT 1
`

type GetOrganizationRow struct {
	ID                               int64
	PublicID                         string
	Name                             string
	TimeZone                         string
	SeverityLabel                    string
	SeverityMapping                  []byte
	SeverityStyles                   []byte
	CriticalIsUrgent                 bool
	InstanceLabels                   []string
	RetentionStoredSnapshotsDays     int64
	RetentionAlertDetailsDays        int64
	RetentionAlertGroupSummariesDays int64
	RetentionAuditLogDays            int64
	TotpRequired                     string
	OidcTokenGraceSeconds            int64
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
func (q *Queries) GetOrganization(ctx context.Context) (GetOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getOrganization)
	var i GetOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.TimeZone,
		&i.SeverityLabel,
		&i.SeverityMapping,
		&i.SeverityStyles,
		&i.CriticalIsUrgent,
		&i.InstanceLabels,
		&i.RetentionStoredSnapshotsDays,
		&i.RetentionAlertDetailsDays,
		&i.RetentionAlertGroupSummariesDays,
		&i.RetentionAuditLogDays,
		&i.TotpRequired,
		&i.OidcTokenGraceSeconds,
	)
	return i, err
}

const getOutboundPolicy = `-- name: GetOutboundPolicy :one
SELECT policy, allowed, denied
FROM outbound_policies
WHERE org_id = $1
`

type GetOutboundPolicyRow struct {
	Policy  string
	Allowed []string
	Denied  []string
}

func (q *Queries) GetOutboundPolicy(ctx context.Context, orgID int64) (GetOutboundPolicyRow, error) {
	row := q.db.QueryRow(ctx, getOutboundPolicy, orgID)
	var i GetOutboundPolicyRow
	err := row.Scan(&i.Policy, &i.Allowed, &i.Denied)
	return i, err
}
