// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearTemplateError = `-- name: ClearTemplateError :many
UPDATE routes r
SET template_error_since = NULL, template_error = NULL, template_error_template = NULL
FROM (SELECT l.id
      FROM routes l
      WHERE l.org_id = $1 AND l.id = $2 AND l.template_error_template = $3::text
      FOR UPDATE SKIP LOCKED) locked
WHERE r.org_id = $1 AND r.id = locked.id
RETURNING r.public_id
`

type ClearTemplateErrorParams struct {
	OrgID    int64
	ID       int64
	Template string
}

// ClearTemplateError clears the template error of the Route when it is about the template given, once that template
// rendered again; the Route's row is skipped while another transaction holds it, as in SetTemplateError.
func (q *Queries) ClearTemplateError(ctx context.Context, arg ClearTemplateErrorParams) ([]string, error) {
	rows, err := q.db.Query(ctx, clearTemplateError, arg.OrgID, arg.ID, arg.Template)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var public_id string
		if err := rows.Scan(&public_id); err != nil {
			return nil, err
		}
		items = append(items, public_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupIDByPublicID = `-- name: GetGroupIDByPublicID :one
SELECT id
FROM alert_groups
WHERE org_id = $1 AND public_id = $2
`

type GetGroupIDByPublicIDParams struct {
	OrgID    int64
	PublicID string
}

// GetGroupIDByPublicID reads the internal id of an Alert Group by its public_id, for a preview.
func (q *Queries) GetGroupIDByPublicID(ctx context.Context, arg GetGroupIDByPublicIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getGroupIDByPublicID, arg.OrgID, arg.PublicID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPreviewRoute = `-- name: GetPreviewRoute :one
SELECT id, public_id, name, language, snooze_durations_seconds
FROM routes
WHERE org_id = $1 AND public_id = $2 AND deleted_at IS NULL
`

type GetPreviewRouteParams struct {
	OrgID    int64
	PublicID string
}

type GetPreviewRouteRow struct {
	ID                     int64
	PublicID               string
	Name                   string
	Language               string
	SnoozeDurationsSeconds []int64
}

// GetPreviewRoute reads a Route that is not deleted by public_id, for a preview.
func (q *Queries) GetPreviewRoute(ctx context.Context, arg GetPreviewRouteParams) (GetPreviewRouteRow, error) {
	row := q.db.QueryRow(ctx, getPreviewRoute, arg.OrgID, arg.PublicID)
	var i GetPreviewRouteRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Language,
		&i.SnoozeDurationsSeconds,
	)
	return i, err
}

const getRenderGroup = `-- name: GetRenderGroup :one


SELECT g.id, g.public_id, g.number, g.title, g.summary, g.status, g.severity_level, g.urgent, g.group_key_labels,
       g.group_key_values, g.common_labels, g.common_annotations, g.firing_alert_count, g.reopen_count,
       g.resolved_by_kind, g.resolve_reason, g.snooze_until, g.snooze_no_end, g.unclaimed, g.created_at,
       r.id AS route_id, r.public_id AS route_public_id, r.name AS route_name, r.language,
       r.snooze_durations_seconds, r.template_root_message, r.template_line, r.template_error_template,
       o.time_zone,
       coalesce(ou.name, '')::text AS owner_name,
       coalesce(su.name, ss.name, '')::text AS snoozed_by_name,
       coalesce(ru.name, rs.name, '')::text AS resolved_by_name
FROM alert_groups g
JOIN routes r ON r.org_id = g.org_id AND r.id = g.route_id
JOIN organizations o ON o.id = g.org_id
LEFT JOIN users ou ON ou.org_id = g.org_id AND ou.id = g.owner_user_id
LEFT JOIN users su ON su.org_id = g.org_id AND su.id = g.snoozed_by_user_id
LEFT JOIN service_accounts ss ON ss.org_id = g.org_id AND ss.id = g.snoozed_by_service_account_id
LEFT JOIN users ru ON ru.org_id = g.org_id AND ru.id = g.resolved_by_user_id
LEFT JOIN service_accounts rs ON rs.org_id = g.org_id AND rs.id = g.resolved_by_service_account_id
WHERE g.org_id = $1 AND g.id = $2
`

type GetRenderGroupParams struct {
	OrgID int64
	ID    int64
}

type GetRenderGroupRow struct {
	ID                     int64
	PublicID               string
	Number                 int64
	Title                  string
	Summary                pgtype.Text
	Status                 string
	SeverityLevel          string
	Urgent                 bool
	GroupKeyLabels         []string
	GroupKeyValues         []byte
	CommonLabels           []byte
	CommonAnnotations      []byte
	FiringAlertCount       int64
	ReopenCount            int64
	ResolvedByKind         pgtype.Text
	ResolveReason          pgtype.Text
	SnoozeUntil            pgtype.Timestamptz
	SnoozeNoEnd            bool
	Unclaimed              bool
	CreatedAt              time.Time
	RouteID                int64
	RoutePublicID          string
	RouteName              string
	Language               string
	SnoozeDurationsSeconds []int64
	TemplateRootMessage    pgtype.Text
	TemplateLine           pgtype.Text
	TemplateErrorTemplate  pgtype.Text
	TimeZone               string
	OwnerName              string
	SnoozedByName          string
	ResolvedByName         string
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright The Muster Authors
// Messages (C-12): the reads a message is rendered from — through the caller's transaction at the dispatcher's
// re-render step — the samples of dry runs and previews, and the template error state of a Route.
// GetRenderGroup reads what a message of an Alert Group shows: the Alert Group, its Route with the Route's
// templates, language, Snooze durations and template error, the Organization's time zone, and the names of its Owner,
// of who snoozed it and of who resolved it. It reads through the caller's transaction, so that a change the
// dispatcher made is seen before it commits.
func (q *Queries) GetRenderGroup(ctx context.Context, arg GetRenderGroupParams) (GetRenderGroupRow, error) {
	row := q.db.QueryRow(ctx, getRenderGroup, arg.OrgID, arg.ID)
	var i GetRenderGroupRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Number,
		&i.Title,
		&i.Summary,
		&i.Status,
		&i.SeverityLevel,
		&i.Urgent,
		&i.GroupKeyLabels,
		&i.GroupKeyValues,
		&i.CommonLabels,
		&i.CommonAnnotations,
		&i.FiringAlertCount,
		&i.ReopenCount,
		&i.ResolvedByKind,
		&i.ResolveReason,
		&i.SnoozeUntil,
		&i.SnoozeNoEnd,
		&i.Unclaimed,
		&i.CreatedAt,
		&i.RouteID,
		&i.RoutePublicID,
		&i.RouteName,
		&i.Language,
		&i.SnoozeDurationsSeconds,
		&i.TemplateRootMessage,
		&i.TemplateLine,
		&i.TemplateErrorTemplate,
		&i.TimeZone,
		&i.OwnerName,
		&i.SnoozedByName,
		&i.ResolvedByName,
	)
	return i, err
}

const getRenderSettings = `-- name: GetRenderSettings :one
SELECT o.time_zone, r.name, r.language, r.snooze_durations_seconds
FROM organizations o
JOIN routes r ON r.org_id = $1 AND r.is_default AND r.deleted_at IS NULL
WHERE o.id = $1
`

type GetRenderSettingsRow struct {
	TimeZone               string
	Name                   string
	Language               string
	SnoozeDurationsSeconds []int64
}

// GetRenderSettings reads the Organization's time zone and the Default route's language and Snooze durations, for a
// preview without a Route.
func (q *Queries) GetRenderSettings(ctx context.Context, orgID int64) (GetRenderSettingsRow, error) {
	row := q.db.QueryRow(ctx, getRenderSettings, orgID)
	var i GetRenderSettingsRow
	err := row.Scan(
		&i.TimeZone,
		&i.Name,
		&i.Language,
		&i.SnoozeDurationsSeconds,
	)
	return i, err
}

const getReplyEntry = `-- name: GetReplyEntry :one
SELECT coalesce(reason, '')::text AS reason, coalesce(replaced_label, '')::text AS replaced_label,
       coalesce(missed_count, 0)::bigint AS missed_count
FROM timeline_entries
WHERE org_id = $1 AND alert_group_id = $2 AND event_seq = $3::bigint
LIMIT 1
`

type GetReplyEntryParams struct {
	OrgID        int64
	AlertGroupID int64
	EventSeq     int64
}

type GetReplyEntryRow struct {
	Reason        string
	ReplacedLabel string
	MissedCount   int64
}

// GetReplyEntry reads the reason, the replaced label and the count of missed notices of the lifecycle event a Thread
// reply is about.
func (q *Queries) GetReplyEntry(ctx context.Context, arg GetReplyEntryParams) (GetReplyEntryRow, error) {
	row := q.db.QueryRow(ctx, getReplyEntry, arg.OrgID, arg.AlertGroupID, arg.EventSeq)
	var i GetReplyEntryRow
	err := row.Scan(&i.Reason, &i.ReplacedLabel, &i.MissedCount)
	return i, err
}

const getSnapshotBody = `-- name: GetSnapshotBody :one
SELECT b.body
FROM stored_snapshots s
JOIN snapshot_bodies b ON b.org_id = $1 AND b.body_sha256 = s.body_sha256 AND b.body_day = s.body_day
WHERE s.org_id = $1 AND s.public_id = $2 AND s.received_at >= $3::timestamptz
LIMIT 1
`

type GetSnapshotBodyParams struct {
	OrgID     int64
	PublicID  string
	NotBefore time.Time
}

// GetSnapshotBody reads the body of a Stored Snapshot by public_id within the retention of Stored Snapshots.
func (q *Queries) GetSnapshotBody(ctx context.Context, arg GetSnapshotBodyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSnapshotBody, arg.OrgID, arg.PublicID, arg.NotBefore)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const getSnapshotRetention = `-- name: GetSnapshotRetention :one
SELECT retention_stored_snapshots_days
FROM organizations
WHERE id = $1
`

// GetSnapshotRetention reads retention.stored_snapshots in days.
func (q *Queries) GetSnapshotRetention(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getSnapshotRetention, orgID)
	var retention_stored_snapshots_days int64
	err := row.Scan(&retention_stored_snapshots_days)
	return retention_stored_snapshots_days, err
}

const listAlertsByFingerprint = `-- name: ListAlertsByFingerprint :many
SELECT DISTINCT ON (a.fingerprint) a.fingerprint, a.labels, m.annotations, m.starts_at
FROM alert_group_alerts m
JOIN alerts a ON a.org_id = m.org_id AND a.id = m.alert_id
WHERE m.org_id = $1 AND m.alert_group_id = $2 AND a.fingerprint = ANY($3::text[])
ORDER BY a.fingerprint, m.id DESC
`

type ListAlertsByFingerprintParams struct {
	OrgID        int64
	AlertGroupID int64
	Fingerprints []string
}

type ListAlertsByFingerprintRow struct {
	Fingerprint string
	Labels      []byte
	Annotations []byte
	StartsAt    time.Time
}

// ListAlertsByFingerprint lists the Alerts of an Alert Group with the fingerprints a Thread reply names, newest
// first.
func (q *Queries) ListAlertsByFingerprint(ctx context.Context, arg ListAlertsByFingerprintParams) ([]ListAlertsByFingerprintRow, error) {
	rows, err := q.db.Query(ctx, listAlertsByFingerprint, arg.OrgID, arg.AlertGroupID, arg.Fingerprints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsByFingerprintRow{}
	for rows.Next() {
		var i ListAlertsByFingerprintRow
		if err := rows.Scan(
			&i.Fingerprint,
			&i.Labels,
			&i.Annotations,
			&i.StartsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenderAlerts = `-- name: ListRenderAlerts :many
SELECT a.fingerprint, a.labels, m.annotations, m.starts_at, m.ended_at, a.generator_url, m.state,
       count(*) OVER ()::bigint AS total
FROM alert_group_alerts m
JOIN alerts a ON a.org_id = m.org_id AND a.id = m.alert_id
WHERE m.org_id = $1 AND m.alert_group_id = $2 AND m.state IN ('firing', 'resolved')
ORDER BY m.state = 'firing' DESC, m.starts_at DESC, m.id DESC
LIMIT $3
`

type ListRenderAlertsParams struct {
	OrgID        int64
	AlertGroupID int64
	Lim          int32
}

type ListRenderAlertsRow struct {
	Fingerprint  string
	Labels       []byte
	Annotations  []byte
	StartsAt     time.Time
	EndedAt      pgtype.Timestamptz
	GeneratorUrl pgtype.Text
	State        string
	Total        int64
}

// ListRenderAlerts lists the Alerts of an Alert Group that a message shows — those still firing in it and those
// resolved in it, not those that moved on — firing first and newest first, at most lim of them, with how many there
// are in all.
func (q *Queries) ListRenderAlerts(ctx context.Context, arg ListRenderAlertsParams) ([]ListRenderAlertsRow, error) {
	rows, err := q.db.Query(ctx, listRenderAlerts, arg.OrgID, arg.AlertGroupID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRenderAlertsRow{}
	for rows.Next() {
		var i ListRenderAlertsRow
		if err := rows.Scan(
			&i.Fingerprint,
			&i.Labels,
			&i.Annotations,
			&i.StartsAt,
			&i.EndedAt,
			&i.GeneratorUrl,
			&i.State,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteSnapshots = `-- name: ListRouteSnapshots :many
SELECT s.public_id, b.body
FROM stored_snapshots s
JOIN snapshot_bodies b ON b.org_id = $1 AND b.body_sha256 = s.body_sha256 AND b.body_day = s.body_day
WHERE s.org_id = $1 AND $2::bigint = ANY(s.route_ids) AND s.source = 'webhook' AND s.state = 'processed'
  AND s.received_at >= $3::timestamptz
ORDER BY s.received_at DESC, s.id DESC
LIMIT $4
`

type ListRouteSnapshotsParams struct {
	OrgID     int64
	RouteID   int64
	NotBefore time.Time
	Lim       int32
}

type ListRouteSnapshotsRow struct {
	PublicID string
	Body     []byte
}

// ListRouteSnapshots lists the bodies of the most recent Stored Snapshots whose Alerts the Route took, newest first,
// within the retention of Stored Snapshots, for a dry run.
func (q *Queries) ListRouteSnapshots(ctx context.Context, arg ListRouteSnapshotsParams) ([]ListRouteSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listRouteSnapshots,
		arg.OrgID,
		arg.RouteID,
		arg.NotBefore,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRouteSnapshotsRow{}
	for rows.Next() {
		var i ListRouteSnapshotsRow
		if err := rows.Scan(&i.PublicID, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTemplateError = `-- name: SetTemplateError :many
UPDATE routes r
SET template_error_since = $1::timestamptz, template_error = $2::text, template_error_template = $3::text
FROM (SELECT l.id
      FROM routes l
      WHERE l.org_id = $4 AND l.id = $5 AND l.template_error IS NULL
      FOR UPDATE SKIP LOCKED) locked
WHERE r.org_id = $4 AND r.id = locked.id
RETURNING r.name
`

type SetTemplateErrorParams struct {
	Now      time.Time
	Error    string
	Template string
	OrgID    int64
	ID       int64
}

// SetTemplateError records that a template of the Route keeps failing, when no template error is recorded yet. The
// Route's row is skipped when another transaction holds it — grouping holds it for share — so that a render never
// waits for it; the next failing render tries again. It returns the Route's name when it recorded the error.
func (q *Queries) SetTemplateError(ctx context.Context, arg SetTemplateErrorParams) ([]string, error) {
	rows, err := q.db.Query(ctx, setTemplateError,
		arg.Now,
		arg.Error,
		arg.Template,
		arg.OrgID,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
